### ISSUE TITLE
[Reunião] Alinhamento da equipe de patrocínio pós-finalização do plano de patrocínio: 27 de fevereiro 2022

### ISSUE THREAD

**Issue by giuliocc** [pythonbrasil/pybr2022-org#100]
# Reunião sobre alinhamento da equipe de patrocínio pós-finalização do plano de patrocínio

- Data: 27/02/2022
- Participantes:
  - Flávia Viana (@Flaviasv)
  - Giulio Carvalho (@giuliocc)
  - Lahis Almeida (@wasp-lahis)

## Ata

- Temos um [quadro para a equipe de patrocínio](https://github.com/orgs/pythonbrasil/projects/3/views/7)
    - **Definição: Criar issues de Patrocínio com label `patrocínio`, garantindo, assim, que fique visível no quadro**
- **Definição: Criar documento com definições da equipe**
- **Definição: Cadastro de toda a equipe atual no Freshdesk**

### Kick off prospecção

- Definimos um mínimo absoluto de porcentagem de representatividade de empresas locais ou deixamos em aberto?
    - Giulio: Acho que podemos deixar em aberto. Podemos até buscar um certo número mas não deixaríamos de fechar patrocínios por conta disso
    - Lahis: Acho que faz sentido as pesssoas da equipe de patrocínio que são daqui ficarem responsáveis pelos contatos com as empresas regionais e assim conseguimos dar vazão aos contatos das empresas regionais (representatividade regional)
    - **Definição: Vamos manter uma porcentagem como objetivo, mas deixar em aberto**
    - **Definição: Preferencialmente, pessoas da equipe de patrocínio que sejam locais irão ser responsáveis pelas empresas locais**
- Porcentagem que buscamos de representatividade de empresas locais?
    - Lahis: Mínimo de 30%. Abaixo disso acho que não ficaria representativo
    - **Definição: A porcentagem objetivo de representatividade de empresas regionais é de pelo menos 30%, porém, a meta é aberta**
- Contato com as empresas deve ser feito utilizando o Freshdesk?
    - Giulio: Para manter a informação centralizada e o histórico da conversa registrado, devemos tentar ao máximo usar o Freshdesk
    - **Definição: Sempre que possível, utilizar o Freshdesk para contato com as empresas**
    - **Definição: Caso algum ponto importante seja discutido fora do Freshdesk, por exemplo em reunião, dar uma devolutiva por email para a empresa com os pontos que ficaram decididos na reunião, assim esses pontos importantes continuam registrados**
- Preenchimento da planilha de prospecção. Preenchemos com todas as empresas que gostaríamos de contatar ou apenas com as que a equipe atual tem capacidade?
    - Flávia: A gente devia colocar na lista apenas as empresas que a gente consegue já se colocar como "responsável", assim a gente consegue se organizar melhor, ao invés de fazer uma lista enorme de "possíveis contatos", que podem nem ser concluídos
    - **Definição: Vamos preencher até domingo que vem (06/03) as empresas que a equipe atual vai contatar**
- Prazo para traduções do plano de patrocínio
    - Lahis: Posso contatar amiga que sabe espanhol
    - Flávia: Posso ajudar na tradução de inglês e espanhol
    - **Definição: O prazo para traduções será dia 06/03**
    - **Definição: Criar dois documentos no Canva, um para inglês e outro para espanhol**

### Guia para contato e reuniões com patrocinadoras

- Como apresentaremos o Plano de Patrocínio para as empresas?
    - Giulio: A gente devia sempre tentar realizar agendamento de reunião para explicar melhor o Plano de Patrocínio e ter esse contato mais pessoal para tirar dúvidas e alinhar os interesses
    - **Definição: Ao entrar em contato ou ser contatado, demonstrar interesse em estabelecer o contato por videochamada e apontar que pode enviar o Plano de Patrocínio para a empresa antes da reunião agendada**
- Durante a reunião de apresentação do Plano
    - Deixar claro os benefícios que a Python BR proporciona à empresas patrocinadoras 
    - A patrocinadora será incentivada a ter seus funcionários submetendo atividades
        - A empresa não deve comprar nenhuma atividade (sem palestras, sem keynotes e sem tutoriais). Casos muito particulares podem ser analisados
    - Deixar claro o que faremos com o fomento que será adquirido 
    - Sempre ter o Código de Conduta em mente
    - **Definição: Fazer um guia para a equipe de patrocínio baseado [no que usaram ano passado](https://foregoing-snail-4ec.notion.site/PYBR-2021-Patroc-nio-1348c076242b4897b8288ae755c39d0c)**
    - **Definição: Podemos rejeitar um patrocínio se identificarmos que não será uma adição positiva ao evento**
    - **Definição: Na reunião, anotar dúvidas e definições em ata**
    - **Definição: Mandar devolutiva por email com tópicos importantes e ações a serem feitas abordados na reunião**
    - **Definição: Depois de sanar as dúvidas levantadas pela empresa, enviar email de resposta**

### Ações para serem realizadas

- [ ] #101
- [x] #102
- [ ] #103
- [ ] #104

**Comment by julianyraiol** [comment]
oi @pythonbrasil/time-patrocinio podemos fechar essa issue?
