### ISSUE TITLE
Criar template de email para cold-calling/contato inicial (@giuliocc)

### ISSUE THREAD

**Issue by giuliocc** [pythonbrasil/pybr2022-org#101]
Criar template de email para cold-calling/contato inicial

**Comment by wasp-lahis** [comment]
@pythonbrasil/time-patrocinio Bolamos o seguinte template:

> Olá <Nome destinatário>. Bom dia!
>
> Meu nome é < Nome remetente >. Faço parte da organização da Python Brasil 2022, maior evento sobre a linguagem de programação Python da América Latina.
> 
> Em 2021, o evento foi realizado durante uma semana para 6.078 participantes cadastrados e tivemos mais de 16.700 visualizações no primeiro dia! Segue o link da edição passada: https://2021.pythonbrasil.org.br/
> 
> Esse ano, a Python Brasil veio para Manaus! Será a primeira edição do evento no Norte do país. E estamos em busca de empresas que possam apoiar a PyBR 22. A/O < Nome da empresa > foi uma das empresas escolhidas pela organização pois < Motivos para escolhermos a empresa >.
> 
> Temos um Plano de Patrocínio que gostaríamos de apresentar para vocês. Há interesse em agendarmos uma videochamada para que possamos apresentá-lo e discutir uma possível colaboração?
> 
> Ficamos no aguardo do retorno. Desde já, obrigada!
> 
> Att,
> Lahis Almeida
> [Python Brasil 2021](https://2022.pythonbrasil.org.br/)

**Comment by wasp-lahis** [comment]
Oie @giuliocc, podemos fechar? ou vc ainda vai acrescentar alguma info

**Comment by giuliocc** [comment]
Fechou! Boa!

**Comment by wasp-lahis** [comment]
@rougeth
