### ISSUE TITLE
Criar documento com definições decididas pela equipe e guia para contato e reuniões com patrocinadoras (@wasp-lahis, @giuliocc)

### ISSUE THREAD

**Issue by giuliocc** [pythonbrasil/pybr2022-org#102]
Criar documento com definições decididas pela equipe e guia para contato e reuniões com patrocinadoras.

- [Template base 2021](https://foregoing-snail-4ec.notion.site/PYBR-2021-Patroc-nio-1348c076242b4897b8288ae755c39d0c)

**Comment by wasp-lahis** [comment]
O Documento criado pode ser acessado [**aqui**](https://foregoing-snail-4ec.notion.site/PYBR-2021-Patroc-nio-1348c076242b4897b8288ae755c39d0c).

**Comment by wasp-lahis** [comment]
Atualizei o link. Tinha colocado o errado TT

**Comment by wasp-lahis** [comment]
Oie @giuliocc, os últimos itens do Guia dependem de outras tasks, o que acha de deixarmos 'A definir', e fechar essa issue? Acredito que o Guia principal (para o momento atual) e as definições já estão todas lá.

**Comment by giuliocc** [comment]
Acho que podemos fechar sim. Boa! Parabéns <3
