### ISSUE TITLE
Criar apresentação de Plano de Patrocínio em Espanhol

### ISSUE THREAD

**Issue by giuliocc** [pythonbrasil/pybr2022-org#103]

**Comment by wasp-lahis** [comment]
Oie @julianyraiol, quando vc tiver um tempo, cria um link do canva p/ Plano de Patrocínio em Espanhol tb plss?

**Comment by julianyraiol** [comment]
oi @pythonbrasil/time-patrocinio, criei um [link](https://www.canva.com/design/DAE5lKXMFaY/share/preview?token=eN_5G3XRww9cibUdVuR_ew&role=EDITOR&utm_content=DAE5lKXMFaY&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton) como cópia da versão em pt-br

**Comment by IKVillanes** [comment]
Olá eu terminei de traduzir para o espanhol a versão que a @wasp-lahis compartilhou e esta [nesse Link](https://www.canva.com/design/DAE5lKXMFaY/share/preview?token=eN_5G3XRww9cibUdVuR_ew&role=EDITOR&utm_content=DAE5lKXMFaY&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton) se puderem dar uma olhada, só no final que tem uma tabela de preços que é imagem, não sei se isso também vai ser traduzido ou quem faz a arte/desenho, pois os preços são em R$  na tradução se mantém ou muda para USD$?

**Comment by wasp-lahis** [comment]
Vlw @IKVillanes!! Podemos levantar esse detalhe da tabela na Reunião Geral! Vou puxar assunto sobre os avanços do time de patrocínio e tiramos essa dúvida o/

**Comment by wasp-lahis** [comment]
Oie, @IKVillanes fiquei de ver o plano de patrocínio de 2021 para ter uma ideia melhor de quanto +- foi o ajuste para dollar. Nesse meio tempo, acho q vc poderia traduzir a aba espanhol [dessa planilha](https://docs.google.com/spreadsheets/d/1eQyoEUX16MBLoV9Kxgj2zNzpfHeuTv_-QIGprQjSPYg/edit?usp=sharing), o que acha?

**Comment by wasp-lahis** [comment]
Plano de Patrocínio em Espanhol (com valores brutos): [patrocinio_python_brasil_es](https://drive.google.com/drive/folders/1f9rUmmfSwFoAO_XJeMGP81fTCxmlmIrz?usp=sharing)

Vlw pessoal! <3
