### ISSUE TITLE
Criar apresentação de Plano de Patrocínio em Inglês

### ISSUE THREAD

**Issue by giuliocc** [pythonbrasil/pybr2022-org#104]

**Comment by wasp-lahis** [comment]
Oie @julianyraiol, quando vc tiver um tempo, cria um link do canva p/ Plano de Patrocínio em Inglês, pls? Seria fazer uma cópia dos slides do Plano de Patrocínio Nacional/Regional, pq daí conseguiríamos trabalhar em cima dele e mudar o idioma.

Decidimos concentrar na sua conta a geração dos links do canva hehe (no sentido de deixar mais organizado)

**Comment by julianyraiol** [comment]
oi @pythonbrasil/time-patrocinio, criei um [link](https://www.canva.com/folder/FAE5lEz8X-8) como cópia da versão em pt-br

**Comment by wasp-lahis** [comment]
@pythonbrasil/time-patrocinio Oi gente, traduzi o conteúdo dos [slides](https://www.canva.com/design/DAE5lckQXtg/share/preview?token=__V3YQybo9GCDQPCg76BAw&role=EDITOR&utm_content=DAE5lckQXtg&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton). Quem puder, dá uma revisada pls o/

Sobre os valores da tabela comparativa, vou me basear nessa [issue](https://github.com/pythonbrasil/pybr2021-org/issues/78#issuecomment-875123622) . O mesmo valerá para a tabela de valores do Plano em espanhol #103

**Comment by giuliocc** [comment]
No geral está excelente @wasp-lahis ! Vou tecer alguns comentários e me diz aí o que acha. A maioria são modificações que acho que deixam a leitura mais agradável. E se eu sugerir alguma coisa errada me perdoa rs.

Slide 2:
- ~Event location~ and ~care~ -> **Venue** and **safety guidelines**
  - Achei que apenas "care" ficou esquisito
- ~Participants number~ -> **Why sponsoring?**
- ~Why participate?~ -> **Number of participants**
- ~Sponsorship quotas~ -> Sponsorship **packages**

Slide 3: 
- ~have~ contact with -> **get in** contact with
- national and international ~community~ -> national and international **communities**
- where ~all people are~ welcome -> where **everyone is** welcome

Slide 4:
- Manaus is ~the headquarters of~ Python Brazil! -> Manaus is **hosting** Python Brazil!
- capital of Amazonas -> capital of **the state of** Amazonas 
  - Referência pra quem é de fora
- middle of the forest -> middle of the **Amazon** forest
  - Referência pra quem é de fora

Slide 5:
- People > ~Tecnology~ -> People > **Technology**

Slide 6:
- ~Event location~ and ~care~ -> **Venue** and **safety guidelines**
- hygiene of ~spaces~ -> hygiene of **surfaces**
  - Esse termo é mais utilizado em inglês pela OMS
- ~care for good ventilation of environments~ -> **attention to** good ventilation of environments

Slide 7:
- ~Within~ the current ~situation~ -> **Under** the current **scenario**
- streaming ~online and~ live all talks -> streaming live all talks
  - Acho que "streaming" já fica bem claro que seria online. Em português, "transmitir" acho que não dá a mesma clareza
- we will also have ~in-person and remote Job Fair~ -> we will also have **Job Fairs both in-person and remotely**
- will have Libras interpreters -> will have Libras **(Brazilian sign language)** interpreters
- translation in ~lectures~, keynotes -> translation in **talks**, keynotes
- keynotes and ~round tables~ -> keynotes and **roundtables**

Slide 8:
- ~Trail~ for Spanish speakers -> **Track** for Spanish speakers,

Slide 12:
- ~Why sponsored?~ -> **Why sponsoring?**
- stimulate ~national and international technological development~ -> stimulate **technological development in South America**
- ~National and international visibility~ -> **Visibility in South America**

Slide 13:
- ~Participants number~ -> **Number of participants**
- event becomes ~bigger~ every year -> event becomes **larger** every year
- more than 2,000 ~entries~ in the first 24 hours ~of disclosure~ -> more than 2,000 **registrations** in the first 24 hours **after the announcement**
- with the hybrid ~modality~! -> with the hybrid **model**!
- We ~project~ around -> We **expect** around
- @giuliocc criar visualizações em inglês

Slide 14:
- Mandar logo do Google pro fundo

Slide 15:
- ~Sponsorship quotas~ -> Sponsorship **packages**

Slide 16:
- Traduzir planilha, salvar planilha como .pdf ("Sem linhas de grade" no campo "Formatação") e converter para imagem

**Comment by wasp-lahis** [comment]
Oie @giuliocc, fiz as modificações: [link slides](https://drive.google.com/file/d/1SJO3IY6R-Y-WqTTLsCwOoS9pxWfGweYi/view?usp=sharing) 

Vlw!

**Comment by wasp-lahis** [comment]
Modifiquei alguns termos da Tabela Comparativa: [link](https://docs.google.com/spreadsheets/d/1eQyoEUX16MBLoV9Kxgj2zNzpfHeuTv_-QIGprQjSPYg/edit?usp=sharing)

Sobre os ingressos de **_Uso livre_**, entendi que são destinados aos funcionários das empresas patrocinadoras, então como sugestão deixei assim:
`Free use (tickets for company employees)`

@giuliocc  é isso mesmo? e desculpa se o entendimento estiver errado!

**Comment by giuliocc** [comment]
Acho que podemos omitir o "free use" nesse caso @wasp-lahis . Deixei apenas "Tickets for company employees" mesmo. Tudo bem assim?

**Comment by wasp-lahis** [comment]
Sim, vlw!

**Comment by wasp-lahis** [comment]
Plano de Patrocínio em Inglês (com valores brutos): [patrocinio_python_brasil_en](https://drive.google.com/drive/folders/1f9rUmmfSwFoAO_XJeMGP81fTCxmlmIrz?usp=sharing)

**Comment by wasp-lahis** [comment]
Oie @giuliocc, atualizei a tabela comparativa. Dps me diz se por esse link do canva vc tb consegue editar pls.
 
- [Slides (pdf)](https://drive.google.com/drive/folders/1f9rUmmfSwFoAO_XJeMGP81fTCxmlmIrz?usp=sharing)
- [Canva](https://www.canva.com/design/DAE5lckQXtg/uJ5jDy8kSakcdToG3qJfhQ/edit?utm_content=DAE5lckQXtg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

**Comment by giuliocc** [comment]
Não consegui @wasp-lahis . Requisitei o acesso aqui

**Comment by giuliocc** [comment]
Não vi que tinha um convite pro time. Aceitei e agora consigo acessar!
