### ISSUE TITLE
[Reunião] Designer: 14 de Março de 2022

### ISSUE THREAD

**Issue by PSFreitas** [pythonbrasil/pybr2022-org#116]
_[Remover antes de abrir o ticket] Este template deve ser editado com os itens a serem discutidos durante a reunião. Toda colaboração é bem vinda. Durante a reunião devem ser registradas as participantes e as decisões tomadas, caso hajam informações sensíveis, deve ser criado um arquivo no [Google Drive da organização da Python Brasil 2022](https://drive.google.com/drive/folders/18zvyKpV42k_n_8Sr4a7yo5KxyU_SFgen?usp=sharing) e o link inserido nessa issue. Após o encerramento, o grupo responsável pela reunião deve revisar as informações e fechar a issue em não mais do que uma semana._

# Reunião Designer: 14 de Março de 2022

Data:  14 de Março de 2022
Participantes:

- Tainah Valois
- Paulo Sergio
- Juliany Raiol
- Jailson Pereira
- Felipe Alencar
- Nayara Souza e Thaís Lopez (acompanharam pela gravação)

## Ata

Reunião para definir os próximos passos a serem dados em relação ao site. Na reunião debatemos sobre:

- Estrutura inicial do site
- Datas para a entrega do design da estrutura inicial do site

### Ações para serem realizadas

- [ ] Definir datas de submissão de palestras.
- [ ] Definir perguntas do FAQ
- [ ] Definir o código de conduta

**Comment by julianyraiol** [comment]
Arquivos o que será entregue na versão 0 do site:

- Data de início de inscrição
- link das redes sociais
- responsivo

![image](https://user-images.githubusercontent.com/9119004/159378709-16f0298a-f78e-4e32-9590-65555fc0e545.png)

**Comment by julianyraiol** [comment]
Arquivos o que será entregue na versão 1 do site:

- página sobre covid19
- página sobre faq
- página de código de conduta
- botão para submissão de palestras

![image](https://user-images.githubusercontent.com/9119004/159379055-bd090640-2e1f-4026-a6d8-0a8320cb0b70.png)
