### ISSUE TITLE
Definir Keynotes para o evento

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#117]
### Descrição
Adicionar sugestões de keynotes à [planilha](https://docs.google.com/spreadsheets/d/1xLNOMcxoTYjz9AyJMpA9fbTPa_izs0BW7nLfrC_DIF8/edit#gid=0)  até o dia 30.03.22

### Requisitos para a atividade ser considerada como concluída

Escolher por meio de votação os próximos 4 keynotes da Python Brasil. 

- Precisamos levar em consideração questões de representatividade de gênero, racial e regional, bem como a influência dessa pessoa na comunidade Python. 
- Pensar em keynotes da América Latina, visto que teremos uma trilha em espanhol.
- Pessoas que se comunicam por libras, visto que teremos tradução simultânea.

**Comment by wasp-lahis** [comment]
**Buser**  indicou o https://www.linkedin.com/in/avelinorun/ para Keynote (e já expliquei que não vendemos isso e cm é feita a escolha dos mesmxs). De qualquer forma, ela achou q seria interessante fazer essa recomendação. @julianyraiol @jailsonpj @anadulce @cecivieira @giuliocc

**Comment by cecivieira** [comment]
Os keynotes costumam ser pessoas que tem envolvimento com a comunidade
Python a nível nacional, américa latina ou global. Não conheço essa
indicação (o que não quer dizer nada.. só que eu não conheço).

**Comment by cecivieira** [comment]
Keynotes definidos
