### ISSUE TITLE
Definir as perguntas que estarão no formulário de submissão de palestras

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#118]
### Descrição
Preencher documento com [perguntas](https://docs.google.com/spreadsheets/d/1uETXZEYG9SR1-P74D7izo4DD_IffBN5eNuVOgPcy4XQ/edit#gid=0) para submissão

### Requisitos para a atividade ser considerada como concluída

- [ ] Preencher o documento para as perguntas que estarão no formulário
- [ ] Traduzir as perguntas para espanhol

**Comment by cecivieira** [comment]
@renan-assis-santos @anadulce por favor , abaixo do campo sobre ajuda financeira, coloca a informação que o preenchimento do formulário solicitando o auxílio financeiro/bolsa viagem é obrigatório

**Comment by renan-assis-santos** [comment]
@cecivieira temos o link para esse formulario?

**Comment by cecivieira** [comment]
@renan-assis-santos ainda não. A mensagem que sugiro é em caráter informativo para que a pessoa que está submetendo saiba que apenas sinalizar esse campo não é suficiente. 

Acredito que ela é importante pois problemas com palestrantes que não leem e-mail é MUITO comum, então mesmo que posteriormente a gente envie uns 10 e-mails falando para preencher o formulário de bolsa, é possível que ignorem por já terem selecionado esse campo na submissão. Então, informar já na submissão que a pessoa precisará obrigatoriamente solicitar a bolsa em formulário específico, a deixará em alerta para o recebimento de novas informações sobre essa etapa.

**Comment by renan-assis-santos** [comment]
@cecivieira beleza, a @anadulce adicionou no formulário. Acho que até conseguimos enviar emails para pessoas específicas a partir do próprio pretalx, talvez isso ajude
