### ISSUE TITLE
Sugestões de acessibilidade para o evento

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#12]
- interprete de libras em todas as trilhas
- auto descrição dos palestrantes
- descrição das imagens no slides

**Comment by julianyraiol** [comment]
- fazer post nas redes sociais da python brasil com videos na linguagem de sinais 
- incentivar a comunidade a fazer cursos de libras

**Comment by lskbr** [comment]
Vamos começar pelos custos. Teríamos que trazer as tradutoras para Manuas ou poderíamos fazer mais tarde quando o video fosse para o Youtube? Ver quanto custou em 2021.
Se quisermos tradução durante a conferência, como gravar? Quantos tradutores trazer?

**Comment by ctulio** [comment]
A UFAM tem um centro de tradução e interpretação de LIBRAS, acredito que possa ser um bom local para buscar referências na cidade.
https://ctrad.ufam.edu.br/equipe-ctrad.html
