### ISSUE TITLE
Criar formulário para recolher dados de keynotes

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#120]
## Descrição
Identificar todas as informações que precisamos das pessoas que serão Keynotes.

## Requisitos para a atividade ser considerada como concluída 

Preencher [formulário](https://docs.google.com/forms/d/1lC_xU3F3S0b6qMXt2ZXue2ybFQUBGemBdhgR2iEmmTs/edit) com as perguntas.

**Comment by wasp-lahis** [comment]
Oie pessoal, dei uma revisada! Acho que falta deixar mais inclusivo, por exemplo mudar '**da Keynote**' por **'do(a)' Keynote** ou então talvez '**dx**' **Keynote**.

O correto é '**a**' Python Brasil o/

### **Outras sugestões:**

**Informações para contato**
Dando início ao preenchimento do formulário dxs Keynotes, a Python Brasil precisa de algumas informações para entramos em contato com você durante sua estadia em Manaus e também para a divulgação dx Keynote nas redes sociais. Lembrando que os dados coletados ficarão disponíveis apenas para a organização e delatados ao final do evento. 

As demais frases é mais questão de artigo mesmo, por exemplo aqui: Como você gostaria de ser chamad**o**?
entra naquela mesma situação do o(a) ou x

**Comment by julianyraiol** [comment]
Oi @wasp-lahis e @renan-assis-santos, fiz as modificações. Podem revisar novamente?

**Comment by renan-assis-santos** [comment]
Boooa, tá ótimo pra mim!

**Comment by wasp-lahis** [comment]
Oi @julianyraiol, algumas sugestões:

- Fala para gente qual nome/sobrenome/apelido ou nome social você gostaria **de** usássemos na sua apresentação para o evento. -> **substituir por 'que'**
- Insira abaixo um e-mail válido e que você tem acesso, para que **a gente** faça contato com você por lá. Toda comunicação formal será via e-mail. -> **sugestão: possamos fazer contato**
- Além do e-mail para entrar em contato com você, vamos precisar do seu número de telefone. Estamos solicitando essa informação para entrarmos em contato em caso **de algo urgente**. -> **sugestão: caso surja alguma urgência**

**Comment by anadulce** [comment]
@julianyraiol fiz algumas alterações nos textos do formulário, e incluí uma sessão de dados pessoais para emissão de passagens/reserva do hotel, porque normalmente o evento custeia a viagem dos keynotes.
Se não for o caso dessa edição, pode deixar que eu apago também :)
