### ISSUE TITLE
Converter preço de cotas para Dolar - Plano de Patrocínio Inglês/Espanhol

### ISSUE THREAD

**Issue by wasp-lahis** [pythonbrasil/pybr2022-org#122]
### Descrição

Para fechar as tasks relacionadas ao Plano de Patrocínio (#103 e #104), precisamos converter o preço das cotas (em reais) para dólares.

### Requisitos para a atividade ser considerada como concluída

- Cálculo de conversão finalizado

**Comment by wasp-lahis** [comment]
Oie pessoal @rougeth @pythonbrasil/time-patrocinio @cecivieira 

Fiz um primeiro esboço dos valores das cotas de patrocínio em dolar: [link](https://docs.google.com/spreadsheets/d/1jwUy6lZ3eAXj-lEi-tXyekemFqS5-TtaZlQR2qCUcLY/edit?usp=sharing). Tomei como base a planilha de conversão do ano passado que o Rougeth me passou. O que acharam?

Tô em dúvida em relação ao [spread](https://pontospravoar.com/taxas-banco-cobra-compras-exterior-usando-cartao-credito/), vi que varia de 1% a 6% conforme o banco utilizado.. poderiam me dizer qual o banco que a pybr utiliza?

**Comment by rougeth** [comment]
Usamos Banco do Brasil.

------- Original Message -------

**Comment by giuliocc** [comment]
@wasp-lahis fiz um comentário na planilha.

Quando finalizar o cálculo, pode atualizar a página de "Referências" na planilha do Financeiro?

**Comment by wasp-lahis** [comment]
@pythonbrasil/time-patrocinio Ficou assim:
```
Platina: $28k
Ouro: 	 $18.5k
Prata:   $11.5k
Bronze:  $4.5k
```

Me baseei em:
- Lógica da planilha de 2021,  [Ref I](https://www.remessaonline.com.br/blog/melhor-banco-para-receber-dinheiro-do-exterior/), [Ref II](https://www.contabilizei.com.br/contabilidade-online/receber-dinheiro-do-exterior-brasil/)

Essa parte de recebimento de conta do exterior, taxas e etc, ainda tá meio obscuro p mim haha. Poderiam dar uma olhada e ver se faz sentido > <' ?

**Comment by giuliocc** [comment]
@wasp-lahis o valor do desconto apyb estava sendo calculado duas vezes. Nas colunas "Descontados Taxas Câmbio" e "Valor Líquido (Descontos, taxas, impostos)".

Também fiz as cotações em relação à média entre o início do ano e agora.

Adicionei o IOF, mas tô na dúvida se isso já estava incluso em "APyB impostos".

@pythonbrasil/apyb alguém consegue validar os cálculos?

**Comment by apast** [comment]
Pessoal, pela experiência nos últimos anos, o valor implícito dos impostos no valor fechado do patrocínio, nos trouxe um ponto a mais para explicar aos interessados 

Em duas conversas iniciais, no ano passado, com Mercado Livre e (entrega de mercados, Uber), trouxeram a pergunta se o IVA estava incluso.

Como sugestão, seria legal separarmos os valores das cotas e deixar a separação explícita:

US$ <valor> + taxes

Facilita explicar, e facilita a cobrança.

**Comment by giuliocc** [comment]
@apast massa! Então vamos estabelecer um valor bruto semelhante ao valor da cota em reais como valor da cota e explicitar a incidência de taxas.

Pra gente ter certeza que vai saber calcular direito e explicar direito ao chegar nessa etapa, pode tirar a dúvida se estaria correto o cálculo a seguir? Para um valor de cota de US$10000, numa cotação USD-BRL de R$5,00, seria cobrado de taxa:
- Spread = R$ 250,00 = US$50,00
- Swift = R$ 60,00 = US$12,00
- Taxa do banco exterior = US$65,00 (colocando a mediana entre 30 e 100)
- IOF (0,38%) = US$38,00
- Impostos APyB (4,5%) = US$450,00

Totalizando US$615,00. Tá tudo certo?

Ah, e quais são os "Impostos APyB"?

**Comment by julianyraiol** [comment]
oi @pythonbrasil/time-patrocinio entendi que conseguimos realizar essa conversão, podemos fechar a issue?

**Comment by wasp-lahis** [comment]
Oie @julianyraiol, os valores brutos já estão definidos sim. Então já estamos enviando para as empresas internacionais o/

Sobre as taxas, ainda estamos tentando entender melhor os 4.5% da Apyb. 

Atualizei a planilha do [financeiro](https://docs.google.com/spreadsheets/d/1g2qmJSoTrxiugwxSqHbMqEb9N0m2igjf9_xOO-0akAY/edit?usp=sharing), conforme cálculo do ano passado e as correções que vc sugeriu @giuliocc .

**Comment by giuliocc** [comment]
Esqueci de atualizar aqui. Mas o @muriloviana confirmou na última reunião que os 4,5% seria o que era cobrado para cobrir todos os impostos e taxas de câmbio.

Acho que podemos fechar a issue @wasp-lahis
