### ISSUE TITLE
[Reunião] Elaboração de proposta de colaboração com a Jornada Colaborativa: 20 de março de 2022

### ISSUE THREAD

**Issue by wasp-lahis** [pythonbrasil/pybr2022-org#125]
# Reunião Elaboração de proposta de colaboração com a Jornada Colaborativa

- Data: 20/03/2022
* Participantes:
   - Giulio Carvalho (@giuliocc)
   - Lahis Almeida (@wasp-lahis)

## Ata

_O objetivo da reunião foi elaborar proposta  de colaboração com a Jornada Colaborativa, levando em consideração os benefícios para ambas as partes.

- Proposta de colaboração
  - Ajuste em planilha de valores e slides do Plano de Patrocínio
  -  Sorteios de curso e livros foram considerados
  - Incremento dos valores das cotas, levando em conta aspectos como esforços a + na divulgação da Pybr22

- Slides de Patrocínio
  - Foi definido que sempre vamos mostrar os slides com a parceria da Jornada Colaborativa pois dá força ao nosso evento (dá visibilidade que já estamos com parcerias)

- Pendências
  - Confirmar como os livros da Jornada são vendidos
	- À preço de editora?
	- A partir de qual valor?
	- Como ficaria a precificação com a colaboração da Pybr22?

  - Alinhar divulgação dos novos benefícios (livros, cursos) com time de marketing
	- Posts antes e depois do evento

  - Pensar como parceria ficaria no Slide
	- Verificar se valores fazem sentido
	- Melhorar texto

### Ações para serem realizadas

- [x] Confirmar como os livros da Jornada são vendidos (@guigasque )
- [x] Questionar Jornada Colaborativa sobre se os valores estipulados fazem sentido (@guigasque)
- [x] Ajustar slide de parceria do Plano de Patrocínio (@lahiss)

**Comment by giuliocc** [comment]
[Na pasta no Drive](https://drive.google.com/drive/folders/15X0G28DFKuPCVA3OZhdXD5lUpKWtAGN5) temos a planilha que explica a proposta de parceria (valores, objetivo, etc.) e um Plano de Patrocínio com a apresentação da parceria (slide 17).
