### ISSUE TITLE
Solicitação de artes para a identidade visual do formulário de submissão de palestras

### ISSUE THREAD

**Issue by renan-assis-santos** [pythonbrasil/pybr2022-org#126]
### Campanha
Criação de identidade visual na ferramenta de submissão de palestras Pretalx
  
### Peça/publicidade solicitada
- Logo do Evento
- Banner para ficar na parte superior do formulário de submissão
- Cor principal do Evento ou existe a opção de ser um CSS personalizado

### Detalhamento do uso
Todas as três artes solicitadas estarão no formulário de submissão, a logo e o banner ficarão na parte superior e a cor principal (ou o CSS) será utilizada em todo o formulário. 
Segue um exemplo de imagem do formulário de submissão:
![Exemplo de arte no formulário de submissão](https://user-images.githubusercontent.com/61845573/159380889-c7006b41-a5ea-4659-88d4-6c006aa63df3.png)

### Data prevista para uso da arte
07/04 que seria a data da divulgação do formulário de submissão

### Quais informações devem aparecer na arte
Apenas as descritas acima

### Quais formatos necessários
Não existem especificações no site da Pretalx

### Locais para divulgação
Ferramenta de submissão

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Comment by renan-assis-santos** [comment]
@alencarftc @taivalois aqui está a solicitação de artes que comentei na reunião de design

**Comment by julianyraiol** [comment]
exemplo da pycon us: https://pretalx.com/pycon-2022/submit/7RlpVz/info/
![image](https://user-images.githubusercontent.com/9119004/159815653-79d5369f-c7b4-44b0-b4e5-55d01227f090.png)

**Comment by julianyraiol** [comment]
@renan-assis-santos  https://drive.google.com/drive/folders/1FESt1G07652O9fk3a6GzDlO8IO5tZjIL

**Comment by renan-assis-santos** [comment]
Valeeu @julianyraiol
cc @anadulce
Coloquei as artes no formulário de submissão e vi duas questões que seria bom analisarmos:
1. Sobre o logo da Python Brasil que fizeram teria possibilidade dele ter um fundo branco por trás? Eu usei o png que tinha no drive e fiz o upload no formulário, mas conflitou com o banner atrás. Acho que poderia ser um pouco maior também
![image](https://user-images.githubusercontent.com/61845573/160945300-493925ae-b749-4531-9608-e41d40653ce2.png)
2. Achei esse [Logo_sticker](https://drive.google.com/drive/folders/1mu0boS2p9RNehDnMb3Orezig3ucPMlwD) no drive das imagens, adicionei no formulario e ficou melhor, mas deixar a imagem um pouco maior ajudaria tbm
![image](https://user-images.githubusercontent.com/61845573/160948351-a51da589-6f15-440c-a2a1-2c5014fccc42.png)
4. Outro ponto é que a escolha de linguagem fica no canto superior direito do formulário. Essa escolha de linguagem não tem opção de trocar a cor dela é sempre em letras brancas :/ assim não sei uma solução sobre isso. 
Talvez mudar um pouco o banner, colocar algo de alguma cor que possa aparecer as letras brancas, inverter, não sei
No exemplo acima do PyCon US 2022 colocaram umas linhas horizontais e uma laranja que deu um contraste razoável na parte da troca das linguagens.
![image](https://user-images.githubusercontent.com/61845573/160945459-d4c2e758-a722-457d-9bfe-40b2bcf2acd0.png)
