### ISSUE TITLE
Criar tabelas na planilha de prospecção com metas de contato regionais, nacionais e internacionais

### ISSUE THREAD

**Issue by giuliocc** [pythonbrasil/pybr2022-org#128]
A planilha de prospecção está em #82.

**Comment by wasp-lahis** [comment]
@pythonbrasil/time-patrocinio criei uma aba **_'Metas de Patrocínio_**' na planilha de prospecção com as Metas de contato regional, nacional e internacional.

Fiquem à vontade para add mais empresas! e se vcs tiverem colegas que trabalham em alguma delas, avisem pls!

**Comment by giuliocc** [comment]
@wasp-lahis ótimo! Adicionei links entre a página de prospecção e a de metas pra não ter retrabalhos. Vê lá o que acha?

**Comment by giuliocc** [comment]
E também adicionei uma sugestão de metas pra cada tipo de localidade de empresas pra fechar até o fim do mês:

Regional - 20
Nacional - 20
Internacional (inglês) - 10
Internacional (espanhol) - 10

O que acham @pythonbrasil/time-patrocinio ?

**Comment by wasp-lahis** [comment]
@giuliocc ficou show! Sobre as quantidades por localidade, achei bacana tb!
