### ISSUE TITLE
Definir uma meta de cada categoria de patrocinadora a ser contatada e um prazo para finalizar os contatos

### ISSUE THREAD

**Issue by giuliocc** [pythonbrasil/pybr2022-org#129]
Definir uma meta de cada categoria de patrocinadora a ser contatada e um prazo para finalizar os contatos.

**Comment by wasp-lahis** [comment]
@pythonbrasil/time-patrocinio oie, 

lendo melhor essa issue, achei um pouco difícil estipular um prazo por categoria, já que nos não contatamos as empresas já definindo o tipo de categoria, pois isso fica à cargo das mesmas.

Tomando como base a issue #128, que tem meta de realizar os contatos listados até final de abril, **pensei de estipularmos
um prazo até início de Junho** para conseguir preencher todas cotas das categorias:

Platina - 1
Ouro    - 4
Prata   - 10
Bronze  - 10

O que acham? Junho fica muito apertado? 

Fiquem à vontade p sugerir outros prazos o/

**Comment by wasp-lahis** [comment]
Obs: Na vdd, a issue trata de estipular prazos p/finalizar contatos regionais, nacionais e internacionais (inglês e espanhol). E estamos discutindo isso atualmente na issue #128 .
