### ISSUE TITLE
Melhorias da logo do evento

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#13]
A logo atual foi desenvolvida pela [Bárbada Agnes](https://www.behance.net/barbaragnes) e possui a seguinte explicação:  

_"É a cúpula do teatro amazonas, sendo os losangos substituídos por peneiras etnicas com o Boitatá, serpente de fogo que protege os animais e as matas. a arte une um simbolo da arquitetural da cidade com a cultura amazônica, representados pelo folclore e artefatos indígenas."_

Após a apresentação da logo ao grupo, levantamos alguns pontos de melhoria como:

- Adicionar algum tom verde remetendo à Amazônia (Mônica Queiroz)
- Variação nas cores da cúpula (Juliany Raiol)

O @PSFreitas foi designer das logos do PyLadies e do PyData Manaus e se disponibilizou a ajudar a Bárbara na identidade visual do evento, visto que temos muito trabalho à frente.

**Comment by cecivieira** [comment]
Pelo que entendi na reunião, a logo já está resolvida e agora estão trabalhando em cima da identidade visual, certo?

Seria possível postar a logo aqui e fechar a issue, caso a informação acima seja verdadeira?

**Comment by PSFreitas** [comment]
A logo ainda não está feita, acabei não sendo claro, desculpe. 

Estamos levantando alguns materiais pra podermos dar prosseguimento a criação da logo e logo em seguida criarmos a identidade visual.

**Comment by PSFreitas** [comment]
Inclusive, olhando melhor para essa issue, vejo que ela não faz mais sentido uma vez que estamos criando uma logo nova do 0 e não trabalhando em melhorias em cima da antiga. 

Levando isso em consideração vou fechar e criar uma nova referente a tarefa que estamos executando no momento.
