### ISSUE TITLE
Patrocínio Instituto Eldorado

### ISSUE THREAD

**Issue by anabegnini** [pythonbrasil/pybr2022-org#132]
### Descrição
Acompanhamento das tarefas relacionadas ao possível patrocínio do [Instituto de Pesquisas Eldorado](https://www.eldorado.org.br/).

A planilha de prospecção das empresas pode ser visualizada em https://github.com/pythonbrasil/pybr2022-org/issues/82

### Requisitos para a atividade ser considerada como concluída

- Contrato assinado
- Patrocínio recebido em caixa
- Pendências pós evento concluídas
Ticket: [#8097](https://pythonbrasil.freshdesk.com/a/tickets/8097) Colaboração Python Brasil 2022 e Instituto de Pesquisas Eldorado

**Comment by julianyraiol** [comment]
@pythonbrasil/time-patrocinio conseguimos uma pessoa para acompanhar a @anabegnini na reunião da próxima segunda?

**Comment by anabegnini** [comment]
Enviado dia **24/03/2022**:

```
Olá, Boa tarde! Tudo bem? 
 
A **** me passou o contato de vocês. Meu nome é Ana Clara Begnini. Faço parte da organização da Python Brasil 2022, maior evento sobre a linguagem de programação Python da América Latina. 
 
Esse ano, a Python Brasil veio para Manaus! Será a primeira edição do evento no Norte do país. E estamos em busca de empresas que possam apoiar a PyBR 22. O Instituto de Pesquisas Eldorado foi uma das empresas escolhidas pela organização pois é uma das grandes referências em se tratando de Institutos de Pesquisa na Região Norte!

Em 2021, o evento foi realizado durante uma semana para 6.078 participantes cadastrados e tivemos mais de 16.700 visualizações no primeiro dia! Segue o link da edição passada: https://2021.pythonbrasil.org.br/
 
Temos um Plano de Patrocínio, contextualizando o evento e formatos de colaborações, que gostaríamos de apresentar para vocês. Vocês teriam interesse em agendarmos uma videochamada para que possamos apresentá-lo e discutir uma possível colaboração?
 
Ficamos no aguardo do retorno. Desde já, obrigada!
 
 Att,
 [Python Brasil 2022](https://2022.pythonbrasil.org.br/)
```
 
 
 
Recebido em **28/03/2022**:

```
Oi Ana Clara,
Tudo bem?
 
Podemos marcar uma call para você contar um pouco melhor para nós?
 
Abs, ***
```

Recebido em **28/03/2022**:

`Estou disponível para a conversa também`

**Comment by anabegnini** [comment]
Enviado dia **29/03/2022**:

```
Olá! tudo bem?

Qual dia vocês tem disponibilidade para a reunião?

Att,
Python Brasil 2022 
```

Recebido em **30/03/2022**:

```
Bom dia, eu posso sexta ou segunda a tarde
, abs
```

**Comment by anabegnini** [comment]
Enviado em **30/03/2022**:
```
Olá! Boa tarde!! 

A reunião poderia ser as 17h (Manaus) da segunda-feira (dia 04/04)? Caso não, qual horário fica melhor na pra vocês na segunda a tarde?

Obrigada pela disponibilidade!!!

Atenciosamente,
Python Brasil 2022  
```

Recebido em **30/03/2022**:
`Pra mim ok`

Recebido em **30/03/2022**:
`Oi Ana, pf, preciso que seja mais cedo. QQ horário depois d 14hr`

**Comment by anabegnini** [comment]
Enviado em **31/03/2022**:

```
Olá!

Pode ser as 15horas (Manaus)?

Obrigada!!

Atenciosamente,
Python Brasil 2022   
```

Recebido em **31/03/2022**:
`Por mim ok `

**Comment by anabegnini** [comment]
Enviado dia **01/04/2022**:

```
Olá! Boa noite!!! Tudo bem?

Combinado!! Então às 15hrs (Manaus) na segunda dia 04/04. Segue o link da reunião: https://meet.google.com/akz-hxkj-ttx

Qualquer coisa, podemos modificar o horário da reunião.

​Em anexo enviamos o plano de patrocínio que será apresentado na segunda-feira.

Obrigada pela disponibilidade!!!

Atenciosamente,
Python Brasil 2022    
```

**Comment by giuliocc** [comment]
@anabegnini aconteceu a reunião? Pela [ata](https://docs.google.com/document/d/1m-6Gat1OdjizucHecBK7FXAJ3T7VLTD3tFOc9OZ_OL4/edit) entendi que tivemos que reagendar

**Comment by anabegnini** [comment]
Reunião vai ser reagendada assim que o Eldorado retornar com as informações de quando vão poder marcar a reunião

**Comment by wasp-lahis** [comment]
## Recebido em 22/09:

> Olá, bom dia!
>  
> Para fins de contratação da cota cupuaçu para o Instituto de Pesquisas Eldorado - MANAUS, solicito o envio dos documentos relacionados abaixo:
>  
> - Estatuto Social;
> -  Formulário de compliance devidamente preenchido;
> -  Minuta de contrato no formato word.
>  
> Qualquer dúvida, é só sinalizar!


## Enviado em 22/09:

> Olá ---, Bom dia!
> 
> Tudo bem?
> 
> Em anexo a minuta de contrato no formato word ^^. Você poderia dar mais detalhes do que seria o item de Estatuto Social e  Formulário de compliance, por favor? Se já tiverem um template desses documentos, podemos assiná-los também.
> 
> Fico no aguardo. Desde já ,obrigada!
> 
> Att,

## Recebido em 22/09:

> Oi Lahis,
>  
> Segue o formulário que deve ser preenchido e assinado.
>  
> Quanto ao Estatuto Social, ele é como se fosse a certidão de nascimento da pessoa jurídica.
>  
> Encaminhar também a Ata de Eleição da Diretoria, caso não  no Estatuto não conste o nome dos representas legais.
>  
> Se preferir, pode também pode me ligar no ----.


Oie @pythonbrasil/apyb, dado o contexto dos emails desse comentário, poderiam preencher o documento [Formulário de Compliance](https://docs.google.com/document/d/18xC8wahTEAMW7j6xPFMeLbaQRsfe8Mha/edit?usp=sharing&ouid=104240651414053856255&rtpof=true&sd=true), por favor? Acredito que no capo assinatura deva ir a assinatura da @anadulce (senão penso que pode dar o mesmo B.O de não passar pelo juridico da empresa como foi com a Luizalabs) 

 Sobre o ***Estatuto Social*** o @muriloviana ficou de dar um olhada e sobre a **Ata de Eleição** ele já tinha me passado previamente tbm.

**Comment by muriloviana** [comment]
Opa, preencherei! Confesso que passei batido por essa informação, fiquei apegado na parte que eles comentaram sobre o estatuto social 😅

**Comment by wasp-lahis** [comment]
Oie @muriloviana @pythonbrasil/apyb, acha que talvez até sexta rola o preenchimento do form de Compliance?

**Comment by wasp-lahis** [comment]
Status patro: https://docs.google.com/spreadsheets/d/1tnj6Um90g6FueWCAqZip4QvbLc9XXQdSRHXltFK2F34/edit?usp=sharing
