### ISSUE TITLE
Patrocínio da Turing

### ISSUE THREAD

**Issue by giuliocc** [pythonbrasil/pybr2022-org#135]
### Descrição

Acompanhamento das tarefas relacionadas ao possível patrocínio da [Turing](https://turing.com/).

A planilha de prospecção das empresas pode ser visualizada em #82 .

### Requisitos para a atividade ser considerada como concluída

- Contrato assinado
- Patrocínio recebido em caixa
- Pendências pós evento concluídas
Ticket: [#8090](https://pythonbrasil.freshdesk.com/a/tickets/8090) "PYthonBR + Turing"

**Comment by giuliocc** [comment]
Mensagens:

### 23/03/2022

```
*****

bem, estou na Turing.com procurando comunidades pra apoiar e eventos pra patrocinar?

Vamos marcar uma call e bater o papo sobre, inclusive o Python Conf que vai ter em outubro?
```

### 29/03/2022

```
Olá, *****!

Sou o Giulio e faço parte da equipe que está cuidando do patrocínio para a Python Brasil 2022. Vamos conversar!

Como estão seus horários? Nos próximos dias posso na sexta 01/04 17h-19h, segunda 04/04 14h-17h e quarta 06/04 9h-12h (horário de Brasília). 

Atenciosamente,
Giulio Carvalho.
Python Brasil 2022
```

### 30/03/2022
```
Vamos dia 01?

me manda um invite?
```
```
Vamos! Vou mandar pras 17h.

Atenciosamente,
Giulio Carvalho
Python Brasil 2022
```

**Comment by giuliocc** [comment]
Perguntas que precisamos responder para a Turing:

1. Qual o tamanho dos estandes?
2. Branding dos estandes será customizado ou padronizado?
3. Links das redes sociais
4. Qual o alcance das redes sociais?
5. Senioridade de pessoas de eventos anteriores?

@anadulce @rougeth @cecivieira @muriloviana a pergunta 5 tá fácil de responder?

A 1 e 4 vamos trazer na reunião hoje.

@thaty-maru qualquer novidade pode atualizar por aqui

**Comment by giuliocc** [comment]
@thaty-maru a gente discutiu hoje na reunião geral e é o que podemos devolver para a Turing:

1. Ainda não sabemos dizer. Ainda é necessário visitar o espaço e orçar com quem monta estande
2. Padronizado, a empresa não precisará se preocupar com problemas de logística
3. e 4.
- [Twitter](https://twitter.com/pythonbrasil): 23,3 mil seguidoras
- [Instagram](https://www.instagram.com/pythonbrasil/): 23,3 mil seguidoras
- [Facebook](https://www.facebook.com/pythonbrasil): 28,3 mil seguidoras
5. Resposta anterior do rougeth

**Comment by thaty-maru** [comment]
Foi respondido para a Márcia sobre as informações levantadas.

```
Olá, Marcia!



Desculpe pela demora, mas seguem as informações solicitadas na call de apresentação:

1. Qual o tamanho dos estandes?
R.: Ainda não sabemos dizer. Ainda é necessário visitar o espaço e orçar com quem monta a estrutura

2. Branding dos estandes será customizado ou padronizado?
R.: Padronizado, a empresa não precisará se preocupar com problemas de logística

3. Links das redes sociais / 4. Qual o alcance das redes sociais?
R:
- [Twitter](https://twitter.com/pythonbrasil): 23,3 mil seguidoras
- [Instagram](https://www.instagram.com/pythonbrasil/): 23,3 mil seguidoras
- [Facebook](https://www.facebook.com/pythonbrasil): 28,3 mil seguidoras

5. Senioridade de pessoas de eventos anteriores?
R.: 
Das pessoas inscritas em 2021:

~10% se consideram no nível avançado
~47% se consideram no nível intermediário
~32% se consideram no nível iniciante
Dados: https://github.com/pythonbrasil/dados/blob/main/dados/python-brasil-2021/inscri%C3%A7%C3%B5es-palestras.csv
Análises: https://pythonbrasil.pybropendata.app/

Para mais informações e dúvidas não hesitem em nos contatar.
Atenciosamente,

Thatianne Maruyama

Python Brasil 2022


Ticket: https://pythonbrasil.freshdesk.com/helpdesk/tickets/8090

```

**Comment by wasp-lahis** [comment]
@pythonbrasil/time-patrocinio  Oiee gente, cm está esse contato? Lembro q parecia promissor 

Não sei quanto tempo vc estipularam para eles retornarem, mas talvez seja uma boa mandar um email perguntando se eles já tem uma posição sobre a colaboração o/

**Comment by thaty-maru** [comment]
Enviei um novo e-mail lembrando-os do nosso contato e perguntando sobre a posição deles quanto à proposta de patrocínio.

### 25/04/2022
```
Olá, -----! Tudo bem?


Faz um tempinho que entramos em contato com vocês sobre as dúvidas que ficaram sobre nossa reunião de apresentação, e gostaria de saber se você já tem alguma posição sobre a proposta de patrocínio, ou se vocês ainda têm alguma dúvida.
​
Estamos à disposição para quaisquer questionamentos e aguardamos o retorno para uma possível parceria.  


Atenciosamente,

Thatianne Maruyama

Python Brasil 2022


Ticket: https://pythonbrasil.freshdesk.com/helpdesk/tickets/8090

```

**Comment by wasp-lahis** [comment]
## Enviado em 13/07:

```
Olá, ---!

Tudo bem?

Conseguiram avaliar se será possível a colaboração entre Turing e Python Brasil?
Ficamos no aguardo de um retorno de vocês o/

Atenciosamente,
Python Brasil 2022
```
