### ISSUE TITLE
Campanha para patrocínio do evento em redes sociais (@pythonbrasil/time-patrocinio )

### ISSUE THREAD

**Issue by giuliocc** [pythonbrasil/pybr2022-org#136]
### Descrição

Em #123 foi decicido movimentar as redes sociais chamando possíveis patrocinadoras para o evento apresentando que temos plano de patrocínio (versão em inglês e espanhol também).

### Requisitos para a atividade ser considerada como concluída
- Desenho da campanha
- Criação de artes
- Peças publicadas

**Comment by giuliocc** [comment]
Precisaremos trocar essa ideia @pythonbrasil/time-design @pythonbrasil/time-patrocinio e galerinha da comunicação @jailsonpj

**Comment by luzfcb** [comment]
Lembre-se que vocês podem usar o https://twitter.com/pynorte e canal no `@pynorte` no telegram para anunciar também. (posso dar acesso para quem quiser usar para postar)

Dito isto, ainda não há informações sobre como patrocinar no https://2022.pythonbrasil.org.br/ 
Nota: desculpe se isso já foi decidido em outros lugar, mas eu não estou acompanhando as discussões da organização do evento.

**Comment by wasp-lahis** [comment]
Oiee gente @pythonbrasil/time-comunicacao @pythonbrasil/time-design 

quando vcs teriam um tempo para reunir com o @pythonbrasil/time-patrocinio ? Estamos com algumas ideias de posts para atrair patrocinadores 💸  💸  💸 

sexta às 19h (Manaus) é um bom horário?

**Comment by wasp-lahis** [comment]
Reunião de planejamento realizada em #165
