### ISSUE TITLE
Criar FAQ para o site e postagem em redes sociais

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#140]
### Descrição
Lista dúvidas e respostas sobre possíveis dúvidas que surgirão sobre o evento

### Requisitos para a atividade ser considerada como concluída

Popular esse [documento](https://docs.google.com/document/d/1C6W9b4PPPJ_2U65KSba4r1YFriz1Zz6B2wpyS53hznA/edit) com pelo menos 5 principais dúvidas.

FAQ de 2021: https://2021.pythonbrasil.org.br/perguntas-frequentes

**Comment by wasp-lahis** [comment]
Oie pessoal, dei uma revisada! Acredito que tem mais perguntas que podem ser utilizadas com base no ano passado, como as relacionados ao Job Fair e patrocínio por exemplo o/

**ps**: o correto mesmo é '**a**' Python Brasil

**Comment by menezesgabriel** [comment]
Oie, tentei trazer para o doc as novas perguntas;
eu também acho super válido utilizar as perguntas do ano passado, principalmente as relacionadas aos tipos de atividades, como o job fair, sprints etc.
Vou adicionar aos documento as perguntas pertinentes do ano passado.
