### ISSUE TITLE
Criar documento sobre cuidado com a saúde

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#141]
### Descrição
Criar documento sobre cuidados com a saúde, listar vacinas a serem tomadas para vir até Manaus, locais de vacinação. 
Regras do evento: uso de máscara em ambientes fechados, distribuição de álcool em gel.

Documento será adicionado ao site e servirá como base para campanhas nas redes sociais

### Requisitos para a atividade ser considerada como concluída

Adicionar texto a esse [documento](https://docs.google.com/document/d/1P7iUycJswTU6RfoXoimUcpiVSauNlYZlEUfgjDziF64/edit)

Exemplo da [PyconUS](https://us.pycon.org/2022/attend/health-safety-guidelines/)
Exemplo da [Pycon Itália](https://pycon.it/en/covid-19?__typename=Page&slug=covid-19)

**Comment by cecivieira** [comment]
Issue relacionada #6

**Comment by alynnefs** [comment]
pull request em andamento: https://github.com/pythonbrasil/pybr2022-site/pull/50
