### ISSUE TITLE
Chamada de palestras

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#15]
Definir data para a abrir o formulário de palestras o quanto antes, tendo em vista que as pessoas selecionadas precisarão comprar uma passagem para vir à Manaus

**Comment by rougeth** [comment]
Issue com as tarefas para submissão https://github.com/pythonbrasil/pybr2022-org/issues/47. @julianyraiol podemos fechar essa?

**Comment by julianyraiol** [comment]
oi @rougeth podemos sim :smile_cat:
