### ISSUE TITLE
Escolha do local para evento

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-org#154]
### Descrição
Definir local a ser realizado o evento, sendo possível múltiplos locais.

### Requisitos para a atividade ser considerada como concluída

- Definição de local para tutoriais
- Definição de local para sprints
- Definição de local para palestras e keynotes

**Comment by cecivieira** [comment]
Conforme explicitado na issue #62 há um diálogo com a secretaria de turismo do Estado para uso do Centro de Convenções Vasco Vasquez.
Foi enviada solicitação formal e atualmente estamos no seguinte estágio:

@julianyraiol :
"oi pessoas, a amazonastur retornou sobre o agendamento do local.

em outubro eles conseguiram agendar somente os dias 17 a 22, os outros dias já estão agendados. 

em novembro eles tem disponível de 01 a 08
conseguimos adiantar a reunião para falar sobre?"

**Comment by cecivieira** [comment]
de: @anadulce 

Bem, existem dois pontos e precisamos tomar uma decisão urgentemente:
De 17 a 22 de outubro é mais próximo (dentro) da data já divulgada.
De 1 a 8 de novembro nos dá dois dias a mais, só que fora do intervalo já divulgado.
Gostaríamos de mais tempo para organização, mas não sei o quanto isso deve pesar na nossa decisão.

**Comment by cecivieira** [comment]
Os tutoriais poderiam ser em outro local também, assim teríamos os 2 dias para montar o espaćo e reduziríamos o custo de aluguel

**Comment by cecivieira** [comment]
de: @julianyraiol 

a UEA fica bem próximo do Vasco Vasques e o IFAM-Centro é bem localizado

**Comment by julianyraiol** [comment]
- Sugestão 1: [Escola Superior de Tecnologia](https://www.google.com/maps/place/Escola+Superior+De+Tecnologia+-+EST%2FUEA/@-3.0916466,-60.0194236,17z/data=!3m1!4b1!4m5!3m4!1s0x926c1aa5ab5c0415:0xf94cde9065387a9a!8m2!3d-3.0916466!4d-60.0172349)

https://est.uea.edu.br/

**Comment by jailsonpj** [comment]
- Sugestão 4: Sebrae Lab

**Comment by cecivieira** [comment]
@anadulce terminasse de atualizar o [plano de trabalho](https://docs.google.com/document/d/1B4hKUM2-IGbQfdntY3a8uBp4KA14dybe-7YhS42xB7c/edit?pli=1#heading=h.61w9e8gk3yca)?

@julianyraiol a reunião de hoje com a secretária da AmazonasTur será aberta para participação de outras pessoas?

**Comment by julianyraiol** [comment]
Oi @cecivieira, será aberto para outras pessoas, vou gerar um link e enviar no canal #geral-org do discord. O horário foi ajustado para às 11h (manaus)

**Comment by cecivieira** [comment]
De: @julianyraiol 
Reunião com vasco vasques em 20 abr. 2022

A alocação é feita por metro quadrado do vasco vasques, o uso das áreas deve ser enviado no email

Descrever quais salões serão utilizados, questão de cadeira e mesa, o vasco vasques pode disponibilizar sofa, mesa de centro, cadeiras, mesas

painéis de led, palco seria contratado fora a parte

existe planta com distribuição de tomadas? a giulia pede mais uma planta com a arquitetura

o vasco vasques tem gerador, mas o ar condicionado não

o local é entregue limpo, contratação nosso de limpeza

8 a 10 dias para a solicitação

o que seria necessário falar com a amazonastur?

    o gestor do setor teria a permissão de dar o valor
    diretor é o Ian

mandar um email da pre reserva com as informações para a solicitação do local, podemos pedir descontos também

o valor do site não está valendo, o site tá desatualizado

ela vai preparar um orçamento para o uso do evento

**Comment by cecivieira** [comment]
@julianyraiol foi enviado o ofício solicitando o espaço?
Falasse com a pessoa que tas em contato? Qual a previsão para retorno?

**Comment by julianyraiol** [comment]
Oi @cecivieira, enviei ainda agora o ofício para a secretaria. A pessoa que nos reunimos na quarta-passada enviou um e-mail pedindo para agendarmos o contato com o presidente da AmazonasTur. Mandei como anexo um arquivo zip da [pasta](https://drive.google.com/drive/u/0/folders/1Akep8Og3ORZu_BqLa6WjFKeKOh4jn0Uy)

Mais detalhes no [link](https://docs.google.com/document/d/1oC8GcSoLPD-8rdGyBRJJDbNPf6u7P-oeMBuC11lcJrs/edit)

**Comment by cecivieira** [comment]
Orçamento do Vasco Vasquez:
https://cdn.discordapp.com/attachments/905625030833111101/973572588267790376/ORCAMENTO_-_Python_Brasil_2022.pdf

**Comment by cecivieira** [comment]
Dúvidas:
- É fornecida a internet? Qual a descrição técnica?
- Explicitar responsabilidade do estacionamento

**Comment by cecivieira** [comment]
- Informar a Polícia militar e civil sobre realização do evento

**Comment by julianyraiol** [comment]
Foi enviado um email no dia 17.05 perguntando sobre o espaço

```
Oi ----! Boa tarde.

Na sexta passada enviamos os documentos para contrato e solicitamos também a alteração dos dias para reserva.

A AmazonasTur precisa de mais alguma informação da nossa parte? Estamos disponíveis.

Obrigada pela colaboração.
```

**Comment by julianyraiol** [comment]
Resposta ainda no dia 17.05

```
Boa tarde Juliany, como vai? 

Acuso recebimento dos documentos. Ademais, informo que por conta da diminuição das datas do evento, conforme solicitado em seu e-mail anterior, o processo está em nosso gabinete presidencial para análise e providências. 

Sigo a disposição.  

```

**Comment by julianyraiol** [comment]
Mandei outro e-mail hoje 23.05

```
Oi -----! Bom dia. Tudo bem?

Nós temos uma posição sobre a solicitação do novo orçamento?
```

**Comment by julianyraiol** [comment]
Oi gente, caso a gente ainda continue sem um posicionamento deles até quarta-feira (25.05), gostaria de voltar a comunicação com o Plaza e agilizarmos o contrato por lá ao invés da AmazonasTur.

O que acham?

**Comment by lahiss** [comment]
Oie, acho uma boa! Pessoal da AmazonasTur tá bem devagar. Mesmo a gente querendo pagar eles não mostram muito interesse  : /

**Comment by cecivieira** [comment]
Parece uma boa ideia retomar o contato com o Plaza, caso não tenhamos
resposta da AmazonasTur até o final dessa semana.

**Comment by julianyraiol** [comment]
Gostei bastante da proposta do Plaza, só precisamos de um ajuste nas datas
- montagem: 19 de outubro
- evento: 20 a 23

**Comment by renan-assis-santos** [comment]
@julianyraiol 
Solicitei a alteração nas datas e qual a documentação necessária

**Comment by julianyraiol** [comment]
obrigada @renan-assis-santos

**Comment by renan-assis-santos** [comment]
Segue a proposta com os dias atualizados e os documentos necessários para fechar o contrato
[PROPOSTA SALÃO TOTAL - EVENTO PYTHON BRASIL 31.05.pdf](https://github.com/pythonbrasil/pybr2022-org/files/8809658/PROPOSTA.SALAO.TOTAL.-.EVENTO.PYTHON.BRASIL.31.05.pdf)
![image](https://user-images.githubusercontent.com/61845573/171291167-f90cc206-9e1d-45b6-afd8-3e3875f8b4a9.png)

**Comment by julianyraiol** [comment]
oi @pythonbrasil/apyb nesse caso seria pessoa física ou jurídica?

**Comment by renan-assis-santos** [comment]
Segue a planta do Manaus Plaza
[PLANTACOMERCIAL.PDF](https://github.com/pythonbrasil/pybr2022-org/files/8819195/PLANTACOMERCIAL.PDF)

**Comment by julianyraiol** [comment]
Oi pessoas, ontem fomos ao Plaza para fazer a visita. Como plano B ele é uma opção boa. Ele também é um shopping e a praça de alimentação está sendo reformada. Como algo negativo, percebemos que a estrutura física do local não está tão boa assim. O ar condicionado da cozinha não está funcionando. No salão A, as 4 salas que podemos montar suportam de 100 a 150 pessoas apenas. Se tentarmos aumentar para 250, ficaria desconfortável.

![image](https://user-images.githubusercontent.com/9119004/172388491-71b7bd4d-a15c-4e03-9ed2-fd863e78fde7.png)

[drive](https://drive.google.com/drive/u/0/folders/1vibLhlKKf0f7pAJUUlM7YXv69Cn9H5Jn)

**Comment by julianyraiol** [comment]
A área da galeria é bem legal, daria para colocar os estandes, tem cerca de 30 na esquerda e na direita corredor. Poderíamos adicionar os estandes lá. 

![image](https://user-images.githubusercontent.com/9119004/172389478-cbb87283-e0ea-4bb3-a7b1-6321b4f2e76e.png)

**Comment by julianyraiol** [comment]
Ainda continuei a conversa com a AmazonasTur conforme combinado na última reunião #200. Na troca de mensagens com a Giuliana, ela disse que poderíamos pagar os 20% (R$ 6.488,31), eles emitiriam um recibo e agendaríamos um dia para assinar o contrato. 

Uma das opções foi pagar os 20% no mesmo dia da assinatura do contrato, entretanto, poderia levar mais tempo porque depende da agenda do presidente. 

Ah, não teríamos o espaço do  foodtruck, porém, nesse momento a prioridade seria o espaço para palestras. 

Apesar do problema de comunicação que temos com eles, acredito que o Centro de Convenções Vasco Vasques é o melhor local em relação à infraestrutura, mesmo que o Plaza seja mais ágil.

**Comment by jailsonpj** [comment]
Nosso principal requisito é um lugar para todas as atividades do evento. Acho que Foodtruck não é uma prioridade, ficar sem ele não vai gerar impacto.

**Comment by julianyraiol** [comment]
Estou preocupada em relação ao tempo, poderíamos efetuar o pagamento dos 20%, pegamos o recibo e aguardamos a assinatura do contrato. O que acham?

**Comment by julianyraiol** [comment]
Vou perguntar dela @jailsonpj, assim que tiver um retorno mando aqui.

**Comment by julianyraiol** [comment]
Ela afirmou que sim, com pagamento do valor inicial, o contrato é feito. Fiquei com dúvida sobre a questão na nota fiscal/recibo, se irão ser enviados por email ou vamos ter que ir lá buscar, já perguntei aqui.

**Comment by julianyraiol** [comment]
A resposta que recebi perguntando sobre a nota fiscal. 

```
[16:32, 08/06/2022] : enviando o depósito vcs podem enviar por email e solicitar
[16:33, 08/06/2022] : não sei te informar sobre prazos pois essa parte é com nosso financeiro
```

Em resumo, é preciso fazer o depósito, enviar um email dcap@amazonastur.am.gov.br; daf@amazonastur.am.gov.br e esperar o envio da nota fiscal.

**Comment by julianyraiol** [comment]
o que vocês acham? seguimos mesmo a AmazonasTur?

**Comment by lahiss** [comment]
Oie Ju, acho que a melhor alternativa parece ser o Vasco Vasques mesmo., no meu ponto de vista. O plaza parece não atender bem a qtde de publico que estamos esperando.

**Comment by renan-assis-santos** [comment]
Acho justo ser o Vasco Vasques também. Eu tinha esperanças do Plaza, mas era torcendo pra vcs irem lá e falarem "ah, até cabe vai", mas se n foi isso então melhor ficar cm o Vasco Vasques msm
