### ISSUE TITLE
Atualizar assinatura do FreshDesck

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-org#155]
### Descrição
Substituir assinatura atual do FreshDesk por: "Organização da Python Brasil 2022"

### Requisitos para a atividade ser considerada como concluída

- Assinatura atualizada

**Comment by cecivieira** [comment]
A assinatura aparece para mim desse jeito:

![image](https://user-images.githubusercontent.com/30605862/164092604-b903290b-c2c1-40c7-aa0d-56f16c256330.png)

**Comment by rougeth** [comment]
Essa configuração parece ser feita em cada perfil no Freshdesk. Acho que não é global.

**Comment by cecivieira** [comment]
Blz

Acredito que essa assinatura foi colocada como padrão por @anadulce , mas
vou dá uma olhada no meu perfil.

**Comment by rougeth** [comment]
@anadulce chegou a dar uma olhada nessa issue? Podemos fechá-la?
