### ISSUE TITLE
Atualizar minuta de contrato de patrocínio para esta edição

### ISSUE THREAD

**Issue by giuliocc** [pythonbrasil/pybr2022-org#156]
### Descrição

A minuta de contrato utilizada na Python Brasil 2021 deve ser atualizada para esta edição. O formato deve se manter genérico para poder ser adequado às especificidades de cada patrocínio.

### Requisitos para a atividade ser considerada como concluída

- Minuta de contrato validada pela Big Kahuna e responsável financeiro da APyB

**Comment by giuliocc** [comment]
@julianyraiol @pythonbrasil/apyb atualizei a minuta de contrato para esta edição:

https://docs.google.com/document/d/1otwAGDZihbY-xPKrTjc9NlYaSFzLpo0V/edit?usp=sharing&ouid=112466627726490084178&rtpof=true&sd=true

Podem verificar rapidinho se está tudo ok? No geral alterei o formato do evento, datas, foro da comarca e anexo do plano de patrocínio.

**Comment by wasp-lahis** [comment]
@giuliocc @julianyraiol @pythonbrasil/apyb @anadulce 

Oie pessoal, algumas dúvidas:

- No contrato (seção DO OBJETO), estamos afirmando que o evento será no período de **17 e 23 de outubro de 2022**, mas, atualmente, estamos negociando com a Secretaria de Turismo de 18-22/10/22. Minha dúvida é: especificar no contrato as datas 17 e 23 de outubro poderia dar algum problema futuro?

- Essa primeira dúvida se repete para a seção DO PRAZO. Lá especificamos 23 de outubro para o término do contrato.

**Comment by wasp-lahis** [comment]
**Respostas às minhas perguntas:** 
-  Atualmente, estamos negociando locação do Vasco Vasques para dia 18-22/10/22, mas os outros dias pré-estabelecidos para o evento (17, 18 e 23) ainda aconteceram, mas em outros lugares (a definir), conforme acordado em #153
- Portanto, as datas no contrato não são um problema, pois, mesmo se mudarmos o local do evento, vai acontecer de 17 a 23/10/22

**Comment by wasp-lahis** [comment]
@giulio, pessoal da Apyb ficou de passar uma data de quando poderão dar um retorno sobre a análise da minuta do contrato.

@pythonbrasil/apyb @julianyraiol pessoal, como o texto tem muita coisa do ano passado, que já foi previamente analisada, será se realmente requer auxilio jurídico nesse momento? Pergunto mais pela questão da JusBrasil ter pedido o quanto antes a minuta.

**Comment by rougeth** [comment]
Eu **acho** que a revisão do contrato não deveria bloquear o acerto com a Jus. Se vocês tiverem alguma dúvidas específica sobre o modelo, coloquem nessa issue (ou aqui também, vou monitorar as duas issues) https://github.com/apyb/tarefas/issues/57, que levaremos para o advogado.

**Comment by julianyraiol** [comment]
oi @wasp-lahis também concordo com o que o @rougeth falou, podemos adiantar com a Jus

**Comment by rougeth** [comment]
Inclusive, o contrato fechado ano passado com a Jus deve ter sido baseado nesse modelo também.

**Comment by wasp-lahis** [comment]
**Minuta base para patrocínios internacionais (Inglês):** [link](https://docs.google.com/document/d/11D3AeS8RaJwJrEp0NbXmagkpH5KslE9s/edit?usp=sharing&ouid=104240651414053856255&rtpof=true&sd=true)

**Comment by wasp-lahis** [comment]
Modelo Minuta Nacional/Regional atualizado: https://docs.google.com/document/d/1otwAGDZihbY-xPKrTjc9NlYaSFzLpo0V/edit?usp=sharing&ouid=104240651414053856255&rtpof=true&sd=true

ps: atualizei a tabela de cotas (Anexo I)

**Comment by julianyraiol** [comment]
adicionei minha assinatura @wasp-lahis
