### ISSUE TITLE
Python Brasil 2022 & Luizalabs

### ISSUE THREAD

**Issue by wasp-lahis** [pythonbrasil/pybr2022-org#157]
### Descrição
Acompanhamento das tarefas relacionadas ao possível patrocínio do [Luizalabs](https://carreiras.magazineluiza.com.br/times/Luizalabs/).

A planilha de prospecção das empresas pode ser visualizada em #82 

### Requisitos para a atividade ser considerada como concluída
- Contrato assinado
- Patrocínio recebido em caixa
- Pendências pós evento concluídas

Ticket: [#8157](https://pythonbrasil.freshdesk.com/a/tickets/8157) Patrocínio Python Brasil 2022 & Luizalabs

**Comment by wasp-lahis** [comment]
## Enviado em 20/04/2022: 

```
Olá ----, Boa tarde!

Tudo bem? 
 
Meu nome é Lahis. Faço parte da organização da Python Brasil 2022, maior evento sobre a linguagem de programação Python da América Latina. 
 
Esse ano, a Python Brasil veio para Manaus! Será a primeira edição do evento no Norte do país. E estamos em busca de empresas que possam apoiar a PyBR 22. A Luizalabs foi uma das empresas escolhidas pela organização pois é uma das grandes referências em se tratando de tecnologia e inovação no país. Além de já ter apoiado nosso evento em edições passadas.

Em 2021, o evento foi realizado durante uma semana para 6.078 participantes cadastrados e tivemos mais de 16.700 visualizações no primeiro dia! Segue o link da edição passada: https://2021.pythonbrasil.org.br/
 
Temos um Plano de Patrocínio, contextualizando o evento e formatos de colaborações, que gostaríamos de apresentar para vocês. Vocês teriam interesse em agendarmos uma videochamada para que possamos apresentá-lo e discutir uma possível colaboração?
 
Ficamos no aguardo do retorno. Desde já, obrigada!
 
Att,
Lahis Almeida
[Python Brasil 2022](https://2022.pythonbrasil.org.br/)
````

**Comment by RicardoRDaCruz** [comment]
-------------------------------------------------------------------------------------------------------------------------------------------
-Linkedin-

Ricardo Ribeiro da Cruz enviou a seguinte mensagem em 16/06 às 14:03

Oi Alencar, tudo bem? 
 
Meu nome é Ricardo. Posso conversar com você sobre a Luizalabs?
 
Faço parte da organização da Python Brasil 2022, maior evento sobre a linguagem de programação Python da América Latina.
 
A Python Brasil será sediada em Manaus esse ano! Será a primeira edição do evento no Norte do país e a primeira edição presencial em dois anos. E estamos em busca de empresas e organizações que possam apoiar a Python Brasil 2022.

Buscamos a Luizalabs pois é um dos expoentes na aplicação de tecnologia no Brasil, e além de possuir valores bastante alinhados com os que o evento preza. Sua presença na Python Brasil 2022 contribuiria bastante com o fomento da inovação e desenvolvimento tecnológico da região.
 
Gostaríamos de apresentar um Plano de Patrocínio por email e lá, agendar uma conversa para discussão, poderia me encaminhar para esse meio?
 
Att,

Ricardo R da Cruz

--------------------------------------------------------------------------------------------------------------------------------------------
-Linkedin-

Alencar Oliveira enviou as seguintes mensagens em 16/06 às 15:19

boa tarde...para essas questões de patrocínio acho que vc pode ter mais sucesso contactando diretamente algum diretor diretamente...vou passar alguns aqui:(Editada)

Thiago Jesus Catoto 
email: [catoto@luizalabs.com](mailto:catoto@luizalabs.com)

André Falata
email: [fatala@luizalabs.com](mailto:fatala@luizalabs.com)(Editada)

--------------------------------------------------------------------------------------------------------------------------------------------
-Linkedin-

Ricardo Ribeiro da Cruz enviou as seguintes mensagens em 16/06 às 15:47

Certo, Alencar. Muito obrigado

Nós entraremos em contato com eles

---------------------------------------------------------------------------------------------------------------------------------------------Freshdesk-

Ricardo Ribeiro da Cruz enviou um e-mail para catoto@luizalabs.com em 16 Jun 2022 às 6:05 PM
De: support@pythonbrasil.freshdesk.com
Cc: fatala@luizalabs.com

Olá Thiago e André, tudo bem?

Meu nome é Ricardo. O Alencar Oliveira indicou os contatos de vocês para tratarmos da Python Brasil 2022,  o maior evento Latino-Americano com ênfase na linguagem de programação Python. 

Em 2021, o evento foi realizado durante uma semana para 6.078 participantes cadastrados e tivemos mais de 16.700 visualizações no primeiro dia! Segue o link da edição passada: https://2021.pythonbrasil.org.br/.
A Python Brasil será sediada em Manaus esse ano! Será a primeira edição híbrida do evento após a pandemia em além disso, a primeira na  Região Norte. E estamos em busca de empresas e organizações que possam apoiar a Python Brasil 2022. 

Buscamos a Luizalabs pois é um dos expoentes na aplicação de tecnologia no Brasil, e possui valores bastante alinhados com os que o evento preza. Essa sinergia já aconteceu na edição de 2021, quando a Luizalabs apoiou o evento, Sua presença na Python Brasil 2022 contribuiria bastante com o fomento da inovação e desenvolvimento tecnológico da região. 

Temos um Plano de Patrocínio que gostaríamos de apresentar para vocês, Há interesse em agendarmos uma videochamada para que possamos apresentá-lo e discutir uma possível colaboração? 
             
             Ficamos no aguardo do retorno. Desde já, obrigado!

Atenciosamente,
Ricardo
Python Brasil 2022

---------------------------------------------------------------------------------------------------------------------------------------------Linkedin-

Ricardo Ribeiro da Cruz enviou a seguinte mensagem em 16/06 às 11:09

Oi Camila, tudo bem? 
 
Meu nome é Ricardo. Posso conversar com você sobre a Luizalabs?
 
Faço parte da organização da Python Brasil 2022, maior evento sobre a linguagem de programação Python da América Latina.
 
A Python Brasil será sediada em Manaus esse ano! Será a primeira edição do evento no Norte do país e a primeira edição presencial em dois anos. E estamos em busca de empresas e organizações que possam apoiar a Python Brasil 2022.

Buscamos a Luizalabs pois é um dos expoentes na aplicação de tecnologia no Brasil, e além de possuir valores bastante alinhados com os que o evento preza. Sua presença na Python Brasil 2022 contribuiria bastante com o fomento da inovação e desenvolvimento tecnológico da região.
 
Gostaríamos de apresentar um Plano de Patrocínio por email e lá, agendar uma conversa para discussão, poderia me encaminhar para esse meio?
 
Att,

Ricardo R da Cruz

---------------------------------------------------------------------------------------------------------------------------------------------Linkedin-

Camila D. enviou as seguintes mensagens em 16/06 às 15:36

Claro, vamos falar!!! Será um prazer!!!

[camila@luizalabs.com](mailto:camila@luizalabs.com)

---------------------------------------------------------------------------------------------------------------------------------------------Linkedin-

Ricardo Ribeiro da Cruz enviou as seguintes mensagens em 16/06 às 15:48

Certo Camila, muito obrigado

Nós entraremos em contato.

---------------------------------------------------------------------------------------------------------------------------------------------Freshdesk-

Ricardo Ribeiro da Cruz adicionou uma anotação privada em 16 Jun 2022 às 6:10 PM

Assunto: Luizalabs & Python Brasil

Descrição:
Olá Camila, tudo bem?

Como tinha falado contigo, temos um Plano de Patrocínio contextualizando o evento e os formatos de colaboração, ele segue em anexo. Também gostaríamos de agendar uma conversa para tirar dúvidas e discutir uma possível colaboração. Qual dia e horário ficaria melhor pra você?

Desde já, obrigado pela atenção.

Atenciosamente,

Ricardo R. da Cruz
Python Brasil 2022

---------------------------------------------------------------------------------------------------------------------------------------------Freshdesk-

Camila Silva relatado por e-mail  em Sex, 17 Jun 2022 às 9:23 AM

Fala Ricardo, bom dia!  Muito obrigada pelo seu contato!!!

Estou adicionando a [+BEATRIZ DE FIGUEIREDO BUCHALLA](mailto:beatriz.buchalla@magazineluiza.com.br) , que hoje nos apoia em Employer Branding em gestão de pessoas, eu faço parte do time de tecnologia, mas me coloco à disposição para apoiar também.

---------------------------------------------------------------------------------------------------------------------------------------------Freshdesk-

Ricardo Ribeiro da Cruz respondeu em Sex, 17 Jun 2022 às 8:51 PM

Para: camila.silva@luizalabs.com
Cc: beatriz.buchalla@magazineluiza.com.br, camila@luizalabs.com

Olá, Camila e Beatriz!

Maravilha, nós também agradecemos pela atenção e retorno. Esperamos poder conversar, alinhar-nos e tirar dúvidas. Vocês têm alguma data que seja melhor para vocês? Qualquer dúvida, estamos à disposição.

Att,
Ricardo R. da Cruz
Python Brasil

---------------------------------------------------------------------------------------------------------------------------------------------Linkedin-

Ricardo Ribeiro da Cruz enviou a seguinte mensagem em 16/06 às 13:53

Oi Robson, tudo bem? 
 
Meu nome é Ricardo. Posso conversar com você sobre a Luizalabs?
 
Faço parte da organização da Python Brasil 2022, maior evento sobre a linguagem de programação Python da América Latina.
 
A Python Brasil será sediada em Manaus esse ano! Será a primeira edição do evento no Norte do país e a primeira edição presencial em dois anos. E estamos em busca de empresas e organizações que possam apoiar a Python Brasil 2022.

Buscamos a Luizalabs pois é um dos expoentes na aplicação de tecnologia no Brasil, e além de possuir valores bastante alinhados com os que o evento preza. Sua presença na Python Brasil 2022 contribuiria bastante com o fomento da inovação e desenvolvimento tecnológico da região.
 
Gostaríamos de apresentar um Plano de Patrocínio por email e lá, agendar uma conversa para discussão, poderia me encaminhar para esse meio?
 
Att,

Ricardo R da Cruz

---------------------------------------------------------------------------------------------------------------------------------------------Linkedin-

Robson Santos, D.Sc. enviou as seguintes mensagens em 17/06 às 09:27

Oi, Ricardo, como vai?
Que boa notícia saber deste evento em Manaus.
Por gentileza, envie e-mail para [robson.santos@luizalabs.com](mailto:robson.santos@luizalabs.com).
Um abraço!

Farei a informação circular internamente até o time de apoio a eventos.

---------------------------------------------------------------------------------------------------------------------------------------------Linkedin-

Ricardo Ribeiro da Cruz enviou as seguintes mensagens às em 17/06 às 09:29

Opa, Robson. Muito obrigado.

Nós entraremos em contato

---------------------------------------------------------------------------------------------------------------------------------------------Linkedin-

Robson Santos, D.Sc. enviou a seguinte mensagem em 17/06 às 09:29

Perfeito. Já temo site do evento? Ou landing page?

---------------------------------------------------------------------------------------------------------------------------------------------Linkedin-

Ricardo Ribeiro da Cruz enviou a seguinte mensagem em 17/06 às 09:31

Temos sim, é [2022.pythonbrasil.org.br](http://2022.pythonbrasil.org.br/)

---------------------------------------------------------------------------------------------------------------------------------------------Freshdesk-

Ricardo Ribeiro da Cruz adicionou uma anotação privada em Sex, 17 Jun 2022 às 11:40 AM

Assunto: Luizalabs & Python Brasil

Descrição:
Olá Robson, tudo bem?

Como tinha falado contigo, temos um Plano de Patrocínio contextualizando o evento e os formatos de colaboração, ele segue em anexo. Também gostaríamos de agendar uma conversa para tirar dúvidas e discutir uma possível colaboração. Qual dia e horário ficaria melhor pra você?

Desde já, obrigado pela atenção.

Atenciosamente,

Ricardo R. da Cruz
Python Brasil 2022

**Comment by wasp-lahis** [comment]
## Recebido em 20/07:

> - Nome do contato 
> - Telefone do contato 
>- Email do contato 

```
 Lahis, tudo bem?

Essas infos vão na NF ? Qual o objetivo? Só para saber de quem colocar?

Abs e obrigada
```

**Comment by muriloviana** [comment]
@wasp-lahis são os dados de contato financeiro da empresa, para caso alguma pendência seja necessária. Esses dados irão na NFe como contato do tomador do serviço

**Comment by wasp-lahis** [comment]
## Recebido em 21/07:
```
Bom dia! Tudo bem? 

Aguardando retorno para saber qual contato incluímos. 
Lembrando que precisamos da nota ainda hoje para adiantarmos o pagamento. 

Abs, 
```

## Enviado em 21/07:
```
Olá Luciana, Bom dia!

Validamos suas dúvidas com o restante da organização e os dados de contato são preferencialmente do financeiro da empresa, para caso tenhamos que entrar em contato no caso de alguma pendência. Esses dados irão na NFe como contato do tomador do serviço. Precisamos dos dados por ser um procedimento obrigatório na geração de nota fiscal. 
​
Att,
```

**Comment by wasp-lahis** [comment]
## Recebido em 21/07
```
OI Boa tarde! 

Segue:

- Nome do contato - ---
- Telefone do contato -  --
- Email do contato - ---

ficamos no aguardo da nota ainda hoje, conforme conversamos.

Muito Obrigada.

Abs.
````

## Enviado em 21/07:

```
Olá, ---!

Obrigada pelas informações. Vamos fazer o possível para enviar ainda hoje. Caso não consigamos, por ter ficado bem em cima do prazo, dou retorno por email o/

Att,
```

@pythonbrasil/apyb conseguem dar uma força? Ela está pedindo a NFe p/ hj TT. Se vocês acharem que não vai rolar, poderiam me dar um prazo p que eu responda pfvr?

**Comment by wasp-lahis** [comment]
## Recebido em 21/07:

```
Verifiquei aqui e pode nos enviar até amanhã que ainda conseguimos subir no sistema esse mês ;)

Abs; 
```

**Comment by wasp-lahis** [comment]
Mt obrigada gente!!

**Comment by wasp-lahis** [comment]
## Enviado 21/07:

```
Olá ---, Boa tarde!

​Segue a NFe para a cota Cobre.

Qualquer dúvida, não hesitem em nos contatar!
[]s
```

**Comment by wasp-lahis** [comment]
Recebemos o din din da Luizalabs (cobre)? Na real, fiquei na dúvida se eles pagarão nesse mes ainda ou no prox... antes de perguntar deles, achei melhor por aq primeiro

**Comment by rougeth** [comment]
Issue da LuizaLabs na APyB - https://github.com/apyb/tarefas/issues/117

**Comment by wasp-lahis** [comment]
# Enviado em 25/07:

```
Olá ---, Boa noite!

Tudo bem?
​
Ficamos na dúvida se deu tudo certo em subir no sistema de vocês o pagamento. Poderiam confirmar se está tudo ok e uma data aproximada para a efetivação, por favor?

Para que já comecemos a divulgar a parceria entre Python Brasil e Luizalabs <3, precisaremos de algumas informações (logos e textos) de vocês. Poderiam preencher nosso [formulário de coleta de informações](https://docs.google.com/forms/d/e/1FAIpQLScPNZ26umrahbSPjcpAvIB1UJiQJlcnRsdnBQIx8bOkdm-YDA/viewform?usp=sf_link), por favor? Selecionando o pacote Cobre.

Ficamos no aguardo!
```

**Comment by wasp-lahis** [comment]
## Recebido em 26/07:

```
Olá boa tarde! Tudo  bem?

Sobre o pagamento subimos no sistema, mas não foi aprovado pois a nota enviada está com item 802 de treinamento, mas é referente a patrocinio, conseguem nos enviar outra nota até amanhã, que é nosso último dia para solicitação de pagamentos do mês.

Sobre as informações estamos preenchendo e logo enviamos de volta.

Dúvidas à disposição.

Abs e obrigada.
```

Oie @pythonbrasil/apyb vocês conseguem? Desculpem o prazo, mas ela não avisou antes : / . Só mandou email agora pq eu perguntei mesmo --"

**Comment by wasp-lahis** [comment]
## Recebido em 28/07:



> Lahis, bom dia! Tudo bem?
> 
> Alguma dúvida com esse e-mail? Vai conseguir emitir a outra nota hoje ainda? 
> 
> Estou à disposição. 
> 
> Abs, 


Essa é a **abençoada** que comentei ontem.

**Comment by muriloviana** [comment]
@wasp-lahis não temos esse CNAE "patrocínio", inclusive acho que nem existe ele rs. As opções que temos são:
- Treinamento (usado para todos os patrocinadores)
- Assessoria em informática
- Assessoria e consultoria em informática 
- Analise e desenvolvimento de sistemas
- Analises, exames, pesquisas e informações

<img width="564" alt="Screen Shot 2022-07-28 at 10 16 08" src="https://user-images.githubusercontent.com/6524275/181514959-f97446d8-86f2-4248-89b2-626a4839f984.png">

Seria o caso de ver se alguma dessas preenche os requisitos deles.

P.S. O Luizalabs já patrocínou eventos com a APyB e pagou NF com o CNAE de Treinamento, enfim ¯\_(ツ)_/¯

**Comment by wasp-lahis** [comment]
Vlw!! bem, n sei pq eles estão embassando agora haha ¬¬" , mas respondi conforme seu texto:

> Olá ----, Bom dia!
> 
> Tudo bem?
> 
> Falei com nosso time responsável por gerar as NFe e eles retornaram que não temos o CNAE "patrocínio". As opções que temos são:
>- Treinamento (utilizado para todos os demais patrocinadores de edições passadas e a corrente da Python Brasil)
>- Assessoria em informática
>- Assessoria e consultoria em informática
>- Analise e desenvolvimento de sistemas
>- Analises, exames, pesquisas e informações
> ​
>Poderiam avaliar se alguma dessas opções preenche o requisito de vocês? 
> ​
>Voluntários mais antigos da Python Brasil mencionaram que a Luizalabs já patrocinou eventos com a APyB (pessoa Jurídica da Python Brasil) e pagou a NF com o CNAE de Treinamento mesmo. Poderia verificar?
> 
> Ficamos no aguardo.
> Att,

**Comment by wasp-lahis** [comment]
## Recebido em 28/07:

 :shipit: :shipit:

> Lahis, deu certo com a nota já enviada. Não precisa emitir outra.
> 
> Não consegui falar com vc por outro canal,  qquer coisa me chama.
> 
> Abs;

**Comment by muriloviana** [comment]
Maravilha! Nada como um "Meteu essa? Que papinho" 😂

**Comment by wasp-lahis** [comment]
> Maravilha! Nada como um "Meteu essa? Que papinho" 😂

ahuahhuauhau essa moça é só o migué

**Comment by wasp-lahis** [comment]
oie gente, o din din da Luizalabs caiu em nossa conta?

**Comment by muriloviana** [comment]
@wasp-lahis caiu sim, no dia 01/08 🎉

**Comment by wasp-lahis** [comment]
Status do patro: https://docs.google.com/spreadsheets/d/1tnj6Um90g6FueWCAqZip4QvbLc9XXQdSRHXltFK2F34/edit?usp=sharing
