### ISSUE TITLE
Patrocínio Python Brasil + Stream

### ISSUE THREAD

**Issue by thaty-maru** [pythonbrasil/pybr2022-org#161]
### Descrição

Acompanhamento das tarefas relacionadas ao possível patrocínio da [Stream](https://getstream.io).

A planilha de prospecção das empresas pode ser visualizada em #82 .

### Requisitos para a atividade ser considerada como concluída

- Contrato assinado
- Patrocínio recebido em caixa
- Pendências pós evento concluídas
Ticket: [#8165](https://pythonbrasil.freshdesk.com/a/tickets/8165) "Stream Inc sponsorship"

**Comment by thaty-maru** [comment]
### Recebido em 25/04/2022

'''
Hello,

I am reaching out on behalf of [Stream](http://getstream.io/), enterprise-grade chat and activity feeds for every app! 

We are interested in Bronze sponsorship for the upcoming October event, please let us know the best way to proceed. 

Thanks!
----
'''

**Comment by thaty-maru** [comment]
### Enviado em 25/04/2022

```
Hi, -----!

We are happy to hear of your interest in sponsoring our event.
May we appoint a meeting to expose our plans, what includes in the Bronze Plan, and answer any questions you may have?
We look forward to your return.

Regards,

Thatianne Maruyama
```

**Comment by thaty-maru** [comment]
### Recebido no dia 02/05/2022

```
Hello Thatianne & Marco

Thank you for your time last week. 

Stream would like to move forward with bronze sponsorship. 

The team won't need all three tickets offered for company employees (most likely just one). We would like to offer the remaining two tickets to the social sponsorship (minority groups). Could we receive an additional social shout-out in exchange for this? 

Once confirmed, I will provide billing information and marketing materials. 

Best regards,
-----
```

**Comment by wasp-lahis** [comment]
Obs: Não coloquei uma clausula para 1 card no twitter a mais pq eles não tem mais direito a ingressos da cota Cobre para fazer essa troca.

**Comment by wasp-lahis** [comment]
## Recebido em 12/05:

````
Hi Lahis,

Please find the Company Registration Number, 47-2494521.

I have signed and attached the Sponsorship Agreement. Looks great!

We still need 1 ticket, as ------ plans to attend and represent Stream. 

----- & Team
````

**Comment by wasp-lahis** [comment]
## Enviado 13/05:

````
Hi ----!

Thanks! We have updated the agreement with Stream's Company Registration Number.

Unfortunately, the Cuprum package doesn't include tickets, but PyBR 2022 will reserve a ticket for ------ and, as soon as registration opens, you can buy it ^^.

Thanks so much for the support! On Monday 16, Python Brasil will sign all the fields and we will send the signed contract to you!
​

Best Regards,
````

**Comment by wasp-lahis** [comment]
@pythonbrasil/apyb @pythonbrasil/time-patrocinio  @cecivieira  Oie pessoal, estou com algumas dúvidas:
- Quem assina no campo APyb? 
- Sobre o invoice, nós que enviamos p empresa, correto? Pretendo me basear no modelo da Ebury

Coloquei como data de fechamento de contrato segunda 16/05.

**Comment by wasp-lahis** [comment]
## Recebido em 13/05:

```
Great, thanks for the update! 

We are thrilled to sponsor. I'll keep an eye out for the contract. 
```

**Comment by rougeth** [comment]
> Quem assina no campo APyb?

A Ju.

> Sobre o invoice, nós que enviamos p empresa, correto? Pretendo me basear no modelo da Ebury

Sim, [esse aqui](https://docs.google.com/document/d/1j0UwPbZrN1E8W3zdclzyIxaFPgztjLAATSdsPAizFX0/edit#heading=h.e41acwcdlup6) é o guia de como gerar o invoice.

**Comment by wasp-lahis** [comment]
Obrigada @rougeth !!

Sobre os campos de testemunhas, vcs recomendam que as 2 assinaturas sejam da PyBR mesmo? Ou por exemplo, teria que ser uma da Stream e outra da PyBR

**Comment by julianyraiol** [comment]
vou assinar aqui @wasp-lahis

**Comment by julianyraiol** [comment]
adicionei minha assinatura @wasp-lahis não sei se ficou bom k

**Comment by wasp-lahis** [comment]
Dei uma olhada no Formulário do invoice, fiquei com dúvida sobre:

Algumas dúvidas sobre o invoice:

- Código do Evento: **pybr2022** ?
-  Responsável pelo Evento: é a Ju mesmo ou alguém da Apyb?

**Comment by wasp-lahis** [comment]
@julianyraiol tá chibata!! qual ferramenta tu usou?

**Comment by julianyraiol** [comment]
assinei no papel, usei scanner de telefone pra converter em pdf e depois cortei a imagem kkkk @wasp-lahis

**Comment by julianyraiol** [comment]
@wasp-lahis acredito que seja eu a pessoa responsável, te mandei as minhas informações pelo discord

o código do evento é pybr2022

**Comment by wasp-lahis** [comment]
Vlww! vou gerar com a data para segunda!

**Comment by wasp-lahis** [comment]
![Captura de tela 2022-05-13 182416](https://user-images.githubusercontent.com/7443249/168396740-192979d4-e89f-4442-9d1d-7fac5328aa34.png)

**Comment by wasp-lahis** [comment]
@pythonbrasil/apyb A Ju comentou que não recebeu o email com o invoice. Vocês receberam?

**Comment by wasp-lahis** [comment]
## Enviado em 16/05:

```
Hi ------, Good Morning!

I am attaching the Python Brasil invoice, with date May 16, and the signed contract. In cc, I put  invoices@getstream.io and @Thuy Nguyen ^^.

Can you let us know when you pay?

Many thanks!
Regards,
````

**Comment by wasp-lahis** [comment]
@julianyraiol @pythonbrasil/apyb @anadulce @cecivieira
Olá pessoal, Bom dia! A Stream mandou 3 pdfs, um deles é p entendermos qual dos outros dois devemos preencher. Seguindo essa imagem, acredito que o nosso caso é o item 2, correto? Com a confirmação de vocês, posso seguir com o preenchimento do forms mais adequado.

![Captura de tela 2022-05-17 092215](https://user-images.githubusercontent.com/7443249/168821752-3af3336f-c76a-4dab-a80f-f6211781512a.png)

**Comment by julianyraiol** [comment]
Oi @wasp-lahis eu acredito que seja o item 2

**Comment by thaty-maru** [comment]
Sim, fazemos parte do item 2, então temos que preencher o formulário W-8BEN-E.

**Comment by wasp-lahis** [comment]
Oie @pythonbrasil/apyb , a partir da seção 5 foge do meu conhecimento. Poderiam me ajudar a preencher? Completei aquilo que consegui.

O Formulário W-8BEN-E semi-preenchido da Stream está [aqui](https://drive.google.com/drive/folders/1q0tRnoMCJnbe9BZjfUg-aMHmj0tEUmru?usp=sharing).

Conseguem ver isso o quanto antes? A Stream pediu que respondessem o mais breve para evitar atrasos no pagamento.

```
Hello,

We have received your invoice and are processing it. Please complete and return the appropriate W-8 based on the overview attached. In addition, I have sent you an invitation to complete your account information in [bill.com](http://bill.com/). Please do so as soon as possible to avoid delay in payment.

Best regards,
```

**Comment by wasp-lahis** [comment]
@pythonbrasil/apyb  Sobre a plataforma de pagamento, preciso de duas informações:

- IBAN
- Tipo de Conta

![Captura de tela 2022-05-17 125733](https://user-images.githubusercontent.com/7443249/168869592-6e2f96ae-c834-4b37-89ac-9e12b8b59cae.png)

**Comment by wasp-lahis** [comment]
Blz! Vlw @julianyraiol . O tipo de conta é opcional, então vou submeter o/

**Comment by julianyraiol** [comment]
Sobre o formulário a @pythonbrasil/apyb poderia ajudar melhor

**Comment by wasp-lahis** [comment]
Submeti:

![Captura de tela 2022-05-17 130832](https://user-images.githubusercontent.com/7443249/168871228-d183b335-da8d-48ff-b0e7-95a45e60bd29.png)

**Comment by wasp-lahis** [comment]
## Enviado em 17/05:

```
Hi ----!

Thank you for sending the forms and payment platform ^^.

We have already filled in all the fields on Bill.com. We are now filling out the W-8BEN-E form and will send it out as soon as possible.


Regards,
```

**Comment by wasp-lahis** [comment]
## Enviado em 18/05:

```
Hi -----!

We filled out form W-8 BEN-E! Let us know if there's any problem. 

Thank you!

Regards,
```

**Comment by rougeth** [comment]
Até ontem, 30 de Maio, não chegou nada da Stream na conta da APyB.

**Comment by wasp-lahis** [comment]
## Enviado em 31/05:

```
Hi --- and ---, Good afternoon!

[Python Brasil 2022 call for papers](https://pretalx.com/python-brasil-2022/) are open! You can submit talks, sprints and tutorials. We would like to point out that there is no limitation of people per company for submission. To compose the program, we value the quality of the content, diversity of themes and people's cultural background (sexuality, gender identity, race, region of origin).


About our collaboration, we have not received the payment yet, could you please check?


Let us know if you have any questions.
Best,
```

**Comment by lahiss** [comment]
## Recebido em 01/06:

@pythonbrasil/apyb **Poderiam verificar, por favor?**

```
Hello,

Please see the payment status below, you should have received payment on 05/24/22. 
Please check with your bank and let me know if you still haven't received it.
```

![WhatsApp Image 2022-06-01 at 09 55 16](https://user-images.githubusercontent.com/97697324/171421810-a2cb5803-e66f-48c6-95e7-130a447626d5.jpeg)

**Comment by lahiss** [comment]
@pythonbrasil/apyb Oie gente, bom dia! Conseguiram ir no BBrasil dar uma olhada nisso?

**Comment by wasp-lahis** [comment]
@pythonbrasil/apyb Oie gente! sabem dizer cm ficou isso?  : p

**Comment by rougeth** [comment]
@wasp-lahis ainda não conseguimos aceitar o recebimento do patrocínio no BB, porém, a treta ta no nosso lado, a Stream fez a transferência corretamente (não lembro se isso já estava claro).

**Comment by wasp-lahis** [comment]
## Para fica registrado esse calculo **($900 -> reais):** 

![IMG_4331](https://user-images.githubusercontent.com/7443249/174841844-5201283d-0f93-4964-8883-1893ba31ecdf.jpg)

**Comment by wasp-lahis** [comment]
## Enviado em 21/06:


Hi ---!

Could you check if the attached image and post text is ok for you? We intend to post on our social networks (instagram, twitter and Facebook)

Post text (feel free to add more text, ex: [Jusbrasil](https://www.instagram.com/p/CfCPgNSrhnu/)):
```
Thanks to Stream Inc. for sponsoring and helping to build Python Brasil 2022 💛
---
Build real-time chat in less time with Stream’s API & SDK solutions.
```

We would like to tag you on our social media ^^. Do you confirm that these addresses below are from Stream?
Instagram: https://www.instagram.com/getstream_io/
Facebook: https://www.facebook.com/getstream.io/
Twitter :  https://twitter.com/getstream_io/

Obs: The Cuprum package covers only one post for our social networks, but we decided to give you two more posts (during and at the end of Python Brasil) for free!

Best,
Lahis Gomes de Almeida
Python Brasil 2022

## Recibido em 21/06:
```
Hey Lahis!

It all looks great. Thanks for the extra posts!

---
```


@menezesgabriel : p

**Comment by menezesgabriel** [comment]
@lahiss haha beleza, será postado amanhã!

**Comment by wasp-lahis** [comment]
Status do patro: https://docs.google.com/spreadsheets/d/1tnj6Um90g6FueWCAqZip4QvbLc9XXQdSRHXltFK2F34/edit?usp=sharing
