### ISSUE TITLE
Colocar Ideias de Posts - Campanha de patrocínio

### ISSUE THREAD

**Issue by wasp-lahis** [pythonbrasil/pybr2022-org#166]
Conforme #165, o documento com ideias de posts para as redes sociais está [**AQUI**](https://docs.google.com/document/d/1PsLidccGMi4Dx9RPsi3nXGaeQTInlv7opFINYbV9Iew/edit?usp=sharing).

**Comment by wasp-lahis** [comment]
@pythonbrasil/time-patrocinio @pythonbrasil/time-comunicacao @pythonbrasil/time-design  @pythonbrasil/apyb 

Oiee gente, criamos essa issue para ir colocando ideias para posts que possam nos ajudar a conseguir mais patrocinadores para o evento. Fiquem a vontade p ir jogando ideias aqui!!!

Já temos [esse documento](https://docs.google.com/document/d/1PsLidccGMi4Dx9RPsi3nXGaeQTInlv7opFINYbV9Iew/edit?usp=sharing) com algumas ideias iniciais.

**Comment by wasp-lahis** [comment]
Ideia - Divulgar:
> **Lightning talk na PyCon US convidando o povo para a Python Brasil**

Link do [light talking](https://www.canva.com/design/DAE_ZmN_v08/Z03rt1R-sYTnZWO1uVbqeQ/edit?utm_content=DAE_ZmN_v08&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) da Ceci <3 

@cecivieira, teria algum vídeo tb?

![-6014770384727029751_121](https://user-images.githubusercontent.com/7443249/166163323-b9393194-eaa5-4cf7-bc8b-542fc5bc7387.jpg)

**Comment by cecivieira** [comment]
Não foram feitos vídeos 😢

**Comment by wasp-lahis** [comment]
:bulb: :bulb: Ideia - Divulgar: 

> ** Chamada de Patrocínio**

Exemplos:

- Pycon Italia: https://twitter.com/pyconit/status/945597637360865280
- Pycon US 22: https://twitter.com/webology/status/1491474658159468544

**Comment by wasp-lahis** [comment]
:bulb: Ideia - Divulgar:

> **Apresentação da PyBR feita pelo Jailson no Hub da JusBrasil**

@jailsonpj Quando tiver um tempo, põe um foto na issue plss, tipo que nem a da Ceci na Pycon

**Comment by wasp-lahis** [comment]
@julianyraiol, @jailsonpj  e @menezesgabriel talvez seja uma boa falar dessa campanha no Onboarding de Comunicação. Alguns voluntários já deram ideias bem parecidas com as que tínhamos listado e acho que poderiam contribuir mais tb.
