### ISSUE TITLE
[Ideia] Sprint mentorada para iniciantes

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-org#168]
### Descrição
Realizar uma sessão de sprint mentorada para iniciantes. Algo similar a isso: https://us.pycon.org/2022/events/mentored-sprints/

Slides da sessão:
https://speakerdeck.com/trallard/mentored-sprints-2022-kickoff

### Requisitos para a atividade ser considerada como concluída

- Definir sobre realização

**Comment by jailsonpj** [comment]
@cecivieira Tenho uma duvida ... os computadores ficariam sob nossa responsabilidade ou cada participante leva seu notebook?

**Comment by cecivieira** [comment]
Acho que o cenário ideal é um abiente misto, com máquinas disponibilizadas,
pois o nosso público alvo é o povo da Semana de Tecnologia.

**Comment by jailsonpj** [comment]
blzinha
