### ISSUE TITLE
Reenviar Plano de Patrocínio Atualizado para as empresas já contatadas

### ISSUE THREAD

**Issue by wasp-lahis** [pythonbrasil/pybr2022-org#179]
### Descrição
Reenviar Plano de Patrocínio Atualizado para as empresas já contatadas

### Requisitos para a atividade ser considerada como concluída

- Planos enviados.

**Comment by wasp-lahis** [comment]
Ceci: "terminei de colocar os contatos das patrocinadoras na planilha de monitoramento" @anadulce

**Comment by wasp-lahis** [comment]
Não é necessário mandar o Plano atualizado para:

- Stream
- Jus Brasil
- Carta
- Buser
- Bemol Digital
- Ambev Tech
- Isaac
- Sidia 
- Thoughworks
- Github
- Quansight
- Gympass
- B2W

**Comment by wasp-lahis** [comment]
++

- Cesar
- Itriad
- Eldorado
- QI Tech
- Idwall

**Comment by wasp-lahis** [comment]
+ Creathus

**Comment by anadulce** [comment]
* Contabilizei

**Comment by anadulce** [comment]
* Sólides
* Cornershop
* Loadsmart
* Turing
* Banco Inter
* SiDi
* Luizalabs
* Bossabox

Não enviei: 
* Jornada Colaborativa -> achei que não fazia sentido.
* QuantumBlack -> comunicação em inglês, não arrisco :)
* Microsoft -> Tem uma nova data de contato (julho), não faz sentido contatar agora
* Alexandria -> foi mandado via Telegram 
* Trusted Health -> foi mandado via Telegram 
* Creditas -> acabou de mandar e-mail solicitando reunião (melhor não enviar o e-mail agora)

**Comment by wasp-lahis** [comment]
+ QuantumBlack

**Comment by wasp-lahis** [comment]
Muito Obrigada pessoal por ajudarem nessa saga de reenvio dos Planos!! @julianyraiol @anadulce @cecivieira
