### ISSUE TITLE
Divulgação Python Brasil 2022 nas redes sociais

### ISSUE THREAD

**Issue by menezesgabriel** [pythonbrasil/pybr2022-org#181]
### Campanha
*Divulgação Python Brasil nas redes sociais*

### Peça/publicidade solicitada
1. *O que é a Python Brasil?* 
2. *Post sobre a cidade de Manaus*
3. *Divulgação das datas do evento*

### Detalhamento do uso
*Artes para divulgação nas redes sociais*

### Data prevista para uso da arte
*De 16/05/22 à 20/05/22*

### Quais informações devem aparecer na arte
*conteúdo* :https://docs.google.com/document/d/1T3QvaQb_36JgVy9ligZoU4mxakjApU8QIcxKT8ncRNo/edit?usp=sharing

### Formatos necessários
- [ ] Quadrado (feed do instagram);
- [ ] Retangular (instagram story).

### Locais para divulgação
- [ ] Redes sociais (twitter, facebook e instagram);

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Planilha de programação das postagens:** https://docs.google.com/spreadsheets/d/1udIOySuO2AHUNoIJXknj0dEL45Q1q6-9/edit#gid=1770463003
**Banco de imagem dos eventos anteriores**: https://www.flickr.com/photos/pythonbrasil/

**Comment by menezesgabriel** [comment]
O que é a Python Brasil? -> Entregue e publicado,

**Comment by jailsonpj** [comment]
Divulgação da data do evento já foi publicada.
