### ISSUE TITLE
Patrocínio CI&T

### ISSUE THREAD

**Issue by jailsonpj** [pythonbrasil/pybr2022-org#182]
### Descrição
Acompanhamento das tarefas relacionadas ao possível patrocínio da GitHub.

A planilha de prospecção das empresas pode ser visualizada em https://github.com/pythonbrasil/pybr2022-org/issues/82

### Requisitos para a atividade ser considerada como concluída
- Contrato assinado
- Patrocínio recebido em caixa
- Pendências pós evento concluídas

**Comment by wasp-lahis** [comment]
Oie @jailsonpj, mt obrigada! Se der bom dela querer agendar reunião, abre um ticket lá no freshdesk para rastrearmos o contato o/

**Comment by jailsonpj** [comment]
Mandei mensagem novamente para Thais, e ela me disse que até semana que vem me envia uma mensagem para marcarmos uma reunião.

**Comment by jailsonpj** [comment]
[Thais] Boa tarde, Jailson! Tudo joia e você?
Temos um prazo máximo pra fechar o patrocínio?
Estou aguardando uma definição de budget ainda

O que posso responder? @wasp-lahis @thaty-maru

**Comment by lahiss** [comment]
@jailsonpj Tínhamos conversado até julho +-, mas acho que temos que avaliar o quanto de grana teremos até lá para redefinir ou não esse prazo.

o @rougeth tinha comentando que  em 2019, fecharam patrocínio uma semana antes do evento.

Acho que só temos que tomar cuidado p não jogar essa conversa de **'até outubro**' pq precisamos de grana por agora, principalmente. (opinião pessoal)

O que acham @julianyraiol @pythonbrasil/time-patrocinio?

**Comment by thaty-maru** [comment]
@jailsonpj a gente não estipulou uma data limite, mas avisa que nos anos anteriores os patrocínios foram bem concorridos, e que não reservamos cotas. Isso vai dar uma pressão maior pra eles não deixarem pra última hora.

**Comment by jailsonpj** [comment]
**[Jailson]** Oi Thais, bom ... o evento acontecerá em Outubro, o quanto antes do evento a gente conseguir fechar o patrocínio é melhor para organização . Por conta das despesas com local, brindes, limpeza, som e etc.
Por isso estamos correndo para fechar patrocínios antes do mês do evento por conta dos custos

**[Thais Lopes, 2:28 PM]**
Claro, entendo
Vou correr com isso e te retorno o quanto antes

**[Jailson Pereira Januario, 2:44 PM]**
poxaaaa, muito obrigado pela ajuda

**Comment by wasp-lahis** [comment]
Olare @jailsonpj, a moça te resp?
