### ISSUE TITLE
Post de divulgação para voluntárias

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#183]
### Descrição
Fazer tradução para espanhol e inglês.

link para edição no canva: https://www.canva.com/design/DAFAfv6RVcs/BFgcpE3vnobVb-03_1DTkw/edit?utm_content=DAFAfv6RVcs&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by cecivieira** [comment]
@IKVillanes traduzir
tu poderia revisar?

**Comment by IKVillanes** [comment]
Olá @cecivieira revisei e mudei algumas palavras e adicionei o ultimo que faltou.
Eu voltei do Perú essa semana, então agora posso ajudar mais, me avise onde posso ajudar.

**Comment by IKVillanes** [comment]
Adicionei os post em inglês também podem dar um review?

**Comment by julianyraiol** [comment]
oi @IKVillanes obrigada! temos o formulário de submissão de palestras, você poderia revisar? vou criar a issue e marcar você, brigada! :heart_decoration:

**Comment by julianyraiol** [comment]
oi @IKVillanes está aqui na issue https://github.com/pythonbrasil/pybr2022-org/issues/187

**Comment by julianyraiol** [comment]
feito
