### ISSUE TITLE
Traduzir texto do site para Espanhol

### ISSUE THREAD

**Issue by wasp-lahis** [pythonbrasil/pybr2022-org#184]
### Descrição
Traduzir texto do site para espanhol.

### Requisitos para a atividade ser considerada como concluída

- Campos textuais do site traduzidos.

**Comment by wasp-lahis** [comment]
A versão beta do site: https://v1-gatsby--stg-pybr-2022.netlify.app/

Quando vcs tiverem um tempo, poderiam traduzir p espanhol? @IKVillanes  @cecivieira 

Aqui está a loc do docs: https://docs.google.com/document/d/1mMwPMrbu8ifPA0at0HhFO56J4pV4cByYsTWp1Q-7cnI/edit?usp=sharing

**Comment by IKVillanes** [comment]
Oi @wasp-lahis fiz as duas paginas que tinha o site, me diz se esta ok ou se está faltando algo.

**Comment by wasp-lahis** [comment]
Oie @IKVillanes ficou muito bom! Obrigada <3

Faltou só o textinho do topo da página:

````
17 A 23 DE OUTUBRO 2022
#PYBR2022
A submissão de palestras para o Python Brasil 2022 pode ser feita pelo botão abaixo.

SUBMETA SUA PALESTRA AQUI"
````


@julianyraiol, vc vê mais algum ajuste?

**Comment by IKVillanes** [comment]
Oi @wasp-lahis essa parte já tem tradução no mesmo site, porem vou adicionar no google-docs por acaso precise.

**Comment by renan-assis-santos** [comment]
Ah @IKVillanes eu coloquei no docs para facilitar, mas se tá tudo bem traduzir pela própria plataforma, então a vontade ^^

**Comment by IKVillanes** [comment]
Oi @renan-assis-santos terminei de fazer a tradução para o espanhol, só tenho uma duvida sobre um paragrafo, deixei a pergunta no docs. O resto esta em azul o texto em espanhol. Me avisa se faltou algo.

**Comment by renan-assis-santos** [comment]
Oi @IKVillanes sua sugestão ficou bem melhor mesmo, atualizei o português com o que você escreveu em espanhol. Já passei tudo para a plataforma, só faltou uma frase que eu e a @anadulce adicionamos agora a pouco. Conseguiria traduzir para a gente?

"Essa pergunta serve apenas de orientação para o time de organização. É necessário preencher a solicitação de auxílio financeiro, num formulário que será divulgado posteriormente, com mais detalhes sobre a sua solicitação. Se atente para não perdê-lo!"

**Comment by IKVillanes** [comment]
Oi @renan-assis-santos no docs apaguei só uma palavra que estava duplicada. Deixei um comentário lá
O texto em espanhol seria:

"Esta pregunta solo sirve como guía para el equipo de organización. Será necesario completar la solicitud de ayuda financiera, en un formulario que será publicado futuramente, con más detalles sobre su solicitud. No te olvides de enviarlo, cuando esté disponible.

**Comment by renan-assis-santos** [comment]
Beleza, obrigado @IKVillanes !
