### ISSUE TITLE
Patrocínio Ebury

### ISSUE THREAD

**Issue by giuliocc** [pythonbrasil/pybr2022-org#185]
### Descrição
Acompanhamento das tarefas relacionadas ao possível patrocínio da [Ebury](https://ebury.com/).

A planilha de prospecção das empresas pode ser visualizada em #82 

### Requisitos para a atividade ser considerada como concluída
- Contrato assinado
- Patrocínio recebido em caixa
- Pendências pós evento concluídas

Ticket: [#8233](https://pythonbrasil.freshdesk.com/a/tickets/8233) "Ebury & Python Brasil 2022"

**Comment by giuliocc** [comment]
### 18/05/22

```
Olá, *****!

Sou o Giulio Carvalho e faço parte da organização da Python Brasil.

Ficamos muito felizes com nossa parceria com a Ebury ano passado pois tivemos a oportunidade de realizar um ótimo evento para a comunidade Python durante um forte período de pandemia com a ajuda de vocês!

Gostaríamos de estender esta parceria para este ano, desta vez num evento híbrido (presencial e online) sediado em Manaus. Se tiverem interesse, poderíamos marcar uma videochamada mas também já deixo em anexo nosso Plano de Patrocínio deste ano para que possam avaliar.

Grande abraço!
Giulio Carvalho,
Python Brasil 2022
```

```
Olá, *****!

Desculpe o incoveniente segundo email, mas notei que talvez pra vocês seja melhor um Plano de Patrocínio em inglês, então estou o anexando neste email também.

Atenciosamente,
Giulio Carvalho
Python Brasil 2022
```

**Comment by RicardoRDaCruz** [comment]
-Linkedin-
*********** enviou a seguinte mensagem em 22/06 às 19:24


Oi ********, tudo bem? 
 
Meu nome é *********. Posso conversar com você sobre a Ebury?
 
Faço parte da organização da Python Brasil 2022, maior evento sobre a linguagem de programação Python da América Latina.
 
A Python Brasil será sediada em Manaus esse ano! Será a primeira edição do evento no Norte do país e a primeira edição presencial em dois anos. E estamos em busca de empresas e organizações que possam apoiar a Python Brasil 2022.
 
Buscamos a Ebury pois é um dos expoentes na aplicação de tecnologia no Brasil, além de possuir valores bastante alinhados com os que o evento preza. Sua presença na Python Brasil 2022 contribuiria bastante com o fomento da inovação e desenvolvimento tecnológico da região.
 
Gostaríamos de apresentar um Plano de Patrocínio por email e lá, agendar uma conversa para discussão, poderia me encaminhar para esse meio?
 
Att,

**************
----------------------------------------------------------------------------
-Linkedin-
****************** enviou as seguintes mensagens em 22/06 às 19:27

Opa

Ano passado a Ebury patrocinou a Python Brasil

acho que esse ano ia também, não acompanhei esse assunto 

----------------------------------------------------------------------------------------
-Linkedin-
******************** enviou a seguinte mensagem em 22/06 às 20:34


Entendi. muito obrigado. Você consegue me encaminhar pra uma pessoa da Ebury que tenha tido contato com esse assunto?
