### ISSUE TITLE
Revisar texto em espanhol do formulário de submissão

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#187]
### Descrição
Revisão do texto em espanhol do [Formulário de Submissão](https://pretalx.com/orga/event/python-brasil-2022/cfp/text)

**Comment by julianyraiol** [comment]
Oi @IKVillanes enviei um convite para acesso à plataforma para o seu e-mail o/

**Comment by IKVillanes** [comment]
Acabei de criar uma conta e logo já reviso e aviso aqui quando terminar.
