### ISSUE TITLE
Patrocínio Mercado Livre (Espanhol)

### ISSUE THREAD

**Issue by wasp-lahis** [pythonbrasil/pybr2022-org#190]
### Descrição
Acompanhamento das tarefas relacionadas ao possível patrocínio do Mercado Livre, **patrocinador do ano passado** ([ticket](https://pythonbrasil.freshdesk.com/a/tickets/7118))

A planilha de prospecção das empresas pode ser visualizada em #82 

### Requisitos para a atividade ser considerada como concluída
- Contrato assinado
- Patrocínio recebido em caixa
- Pendências pós evento concluídas

Ticket: ---

**Comment by wasp-lahis** [comment]
Oiee @IKVillanes! Antes de mandar o email para o Mercado Livre, precisamos atualizar o Plano de Patrocínio Espanhol:

**- Slide 11 - Job Fair
- Slide 14 -  Redes sociais e Senioridade
- Slide 17 - Tabela de cotas**

O canvas editável está em: [nesse Link](https://www.canva.com/design/DAE5lKXMFaY/share/preview?token=eN_5G3XRww9cibUdVuR_ew&role=EDITOR&utm_content=DAE5lKXMFaY&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton)

**Comment by wasp-lahis** [comment]
[Tabela Comparativa de Cotas Editável](https://docs.google.com/spreadsheets/d/1xZjozuQM1wK5Q2tfhVm2Z4YWRkkoh0KWR_jvgrUner0/edit?usp=sharing)

Em verde, estão as palavras/frases que precisão de tradução.

**Comment by wasp-lahis** [comment]
### Email para tradução:

```
Olá -----, Boa tarde!

Tudo bem?

Meu nome é Lahis Almeida. Faço parte da organização da Python Brasil 2022.

Esse ano, a Python Brasil veio para Manaus! Será a primeira edição do evento no Norte do país. E estamos em busca de empresas que possam apoiar a PyBR 22.  O Mercado Livre foi uma das empresas escolhidas pela organização pois é uma das grandes referências em se tratando de tecnologia e inovação na América Latina. Além de já ter apoiado nosso evento em edições passadas (https://2021.pythonbrasil.org.br/)

Temos um Plano de Patrocínio, contextualizando o evento e formatos de colaborações, que gostaríamos de apresentar para vocês. Vocês teriam interesse em agendarmos uma videochamada para que possamos apresentá-lo e discutir uma possível colaboração?
 
Ficamos no aguardo do retorno. Desde já, obrigada! 

Atenciosamente,
```

**Comment by wasp-lahis** [comment]
@IKVillanes, se vc se sentir a vontade, podemos mandar o email com o seu nome! Posso te ajudar a utilizar o freshdesk e td mais.

Me avisa o/

**Comment by cecivieira** [comment]
A empresa demonstrou interesse em patrocinar . [Ticket 8246](https://pythonbrasil.freshdesk.com/a/tickets/8246)

```
Temos interesse em que o MELI seja patrocinador da Python Brasil mais uma vez sendo que python é um dos linguagens mais usados pelos nossos desenvolvedores e gostamos muito da dinâmica do ano passado. Por tanto, gostaríamos repetir a experiência sendo sponsors do nível Prata segundo o plano de patrocínio. ainda tem cota para esse nível? 

É possível marcarmos uma reunião para conhecer mais do evento?

Em cópia temos ao Fernando e ao Diogo do meu time que apoiam fortemente no fortalecimento de comunidade de desenvolvedores dentro do MELI.


```

**Comment by IKVillanes** [comment]
Oi @wasp-lahis sobre as atividades:

- A tabela só fiz un ajuste, pois quase tudo já estava em espanhol :) colorei de azul o que revisei.
- Os slides 11 e 14 também já estão em espanhol
- O slide 17 seria copiar a tabela atualizada certo? pode verificar se faltou algo? se esta ok, copio a nova tabela
- Sobre o e-mail pode ser meu nome no tem problema. O texto e-mail no espanhol seria:

¡Hola buenas tardes!

Esperamos que todo este bien.

Mi nombre es Karina Villanes. Soy parte de la organización Python Brasil 2022.

¡Este año, Python Brasil llegó a Manaus! Será la primera edición del evento en el Norte del país. Y estamos buscando empresas que puedan apoyar PyBR 22. Mercado Livre fue una de las empresas elegidas por la organización porque es uno de los grandes referentes en tecnología e innovación en América Latina. Además de haber apoyado nuestro evento en ediciones pasadas (https://2021.pythonbrasil.org.br/)

Disponemos de un Plan de Patrocinio, contextualizando el evento y los formatos de colaboración, que quisieramos presentar ante ustedes. ¿Les interesaría programar una videollamada para que podamos presentar y discutir una posible colaboración?
 
Aguardamos su respuesta. ¡Desde ya gracias!

Atentamente,

**Comment by wasp-lahis** [comment]
Oie @IKVillanes!! Ficou show <3 !

Sobre o contato do Mercado Livre, eles mandaram email hj mostrando interesse em patrocinar a PyBR! Esse ano a reunião será em Português!

Vou criar uma task para mapearmos o contato de outras empresas da América Latina, que costumam apoiar eventos da comunidade Python!
