### ISSUE TITLE
Mapear contatos internacionais (Espanhol)

### ISSUE THREAD

**Issue by wasp-lahis** [pythonbrasil/pybr2022-org#193]
### Descrição
Mapear contatos de possíveis empresas patrocinadoras (espanhol)

### Requisitos para a atividade ser considerada como concluída
- Tabela de Mapeamento
- Add Mapeamento às metas de Patrocínio

**Comment by wasp-lahis** [comment]
@IKVillanes Um ótimo ponto de partida é anotarmos as empresas que apoiaram a [**Pycon Argentina 2021**](https://eventos.python.org.ar/events/pyconar2021/)

Vou montar um docs e aew poderemos nos organizar para começar os contatos.

**Comment by IKVillanes** [comment]
Oi @wasp-lahis posso criar o docs e a gente monta a info juntas ou já tem um docs?

**Comment by wasp-lahis** [comment]
@IKVillanes desculpe a demora! [Aqui está o docs](https://docs.google.com/document/d/16ywozv5gKJCl2xJ0Kzlkd4ZMKVnxC1NfbbDYxtxhLWk/edit?usp=sharing)

Vamos montar juntas <3

Hj às 18h (horário de Manaus) tem **Onboarding de Patrocínio**. Seria massa se vc pudesse ir ^^ . Caso não possa, marcamos outro dia o/

**Comment by wasp-lahis** [comment]
Oie, @IKVillanes preenchi uns 3 contatos. Podemos tentar contatar pelo site da empresa, buscando pelo linkedin ou ambos. 

Quando tiver disponibilidade me avisa o/

Acho que temos que deixar o e-mail de contato frio mais atrativo para essas empresas do restante da America Latina. Vou tentar bolar algo até sexta. Se tiver ideia legal de texto, fica a vontade tb o/
