### ISSUE TITLE
Contatar LabCodes (patrocinou a PyBR em 2018 e 2019)

### ISSUE THREAD

**Issue by rougeth** [pythonbrasil/pybr2022-org#195]

**Comment by rougeth** [comment]
E-mail enviado.

**Comment by RicardoRDaCruz** [comment]
---------------------------------------------------------------------------------------------------------------------------------------------Linkedin-

Ricardo Ribeiro da Cruz enviou a seguinte mensagem em 16/06 às 18:40

Oi Vitória, tudo bem? 
 
Meu nome é Ricardo. Posso conversar com você sobre a Labcodes?
 
Faço parte da organização da Python Brasil 2022, maior evento sobre a linguagem de programação Python da América Latina.
 
A Python Brasil será sediada em Manaus esse ano! Será a primeira edição do evento no Norte do país e a primeira edição presencial em dois anos. E estamos em busca de empresas e organizações que possam apoiar a Python Brasil 2022.
 
Buscamos a Labcodes pois é um dos expoentes na aplicação de tecnologia no Brasil, e além de possuir valores bastante alinhados com os que o evento preza. Sua presença na Python Brasil 2022 contribuiria bastante com o fomento da inovação e desenvolvimento tecnológico da região.
 
Gostaríamos de apresentar um Plano de Patrocínio por email e lá, agendar uma conversa para discussão, poderia me encaminhar para esse meio?
 
Att,
 
Ricardo R da Cruz
sexta-feira

---------------------------------------------------------------------------------------------------------------------------------------------Linkedin-

Vitória Melquiades enviou a seguinte mensagem em 16/06 às 14:44

Olá, estou bem sim e você?
Que massa esse evento, a pessoa mais indicada da Labcodes para falar com você é o Fernando Lins ;)

Espero ter ajudado ;)

---------------------------------------------------------------------------------------------------------------------------------------------Linkedin-

Ricardo Ribeiro da Cruz enviou as seguintes mensagens em 16/06às 14:45

Opa, certo. Muito obrigado.

Ajudou sim. Buscaremos entrar em contato com ele.

---------------------------------------------------------------------------------------------------------------------------------------------Linkedin-
Vitória Melquiades enviou a seguinte mensagem às 14:47

Maravilha ;)

---------------------------------------------------------------------------------------------------------------------------------------------Linkedin-

Ricardo Ribeiro da Cruz enviou a seguinte mensagem em 16/06 às 18:19

Oi Fernando, tudo bem? 
 
Meu nome é Ricardo. Posso conversar com você sobre a Labcodes?
 
Faço parte da organização da Python Brasil 2022, maior evento sobre a linguagem de programação Python da América Latina.
 
A Python Brasil será sediada em Manaus esse ano! Será a primeira edição do evento no Norte do país e a primeira edição presencial em dois anos. E estamos em busca de empresas e organizações que possam apoiar a Python Brasil 2022.
 
Buscamos a Labcodes pois é um dos expoentes na aplicação de tecnologia no Brasil, e além de possuir valores bastante alinhados com os que o evento preza. Sua presença na Python Brasil 2022 contribuiria bastante com o fomento da inovação e desenvolvimento tecnológico da região.
 
Gostaríamos de apresentar um Plano de Patrocínio por email e lá, agendar uma conversa para discussão, poderia me encaminhar para esse meio?
 
Att,
 
Ricardo R da Cruz

Fernando Lins enviou a seguinte mensagem em 17/06 às 16:51

Oi Ricardo, tudo bem?

A gente já teve o contato com alguém da organização ou da APyB que nos enviou o plano de patrocínio.

A gente ainda não decidiu se vai patrocinar.

---------------------------------------------------------------------------------------------------------------------------------------------Linkedin-

Ricardo Ribeiro da Cruz enviou as seguintes mensagens em 17/06 às 18:29

Opa Fernando. Tudo bom

Certo, muito obrigado

Qualquer dúvida, estamos à disposição
