### ISSUE TITLE
Patrocínio ThoughtWorks

### ISSUE THREAD

**Issue by wasp-lahis** [pythonbrasil/pybr2022-org#197]
### Descrição
Acompanhamento das tarefas relacionadas ao possível patrocínio da [ThoughtWorks](https://www.thoughtworks.com/pt-br).

A planilha de prospecção das empresas pode ser visualizada em #82 

### Requisitos para a atividade ser considerada como concluída
- Contrato assinado
- Patrocínio recebido em caixa
- Pendências pós evento concluídas

Ticket: [#8196](https://pythonbrasil.freshdesk.com/a/tickets/8196) Thoughtworks & Python Brasil

**Comment by wasp-lahis** [comment]
## Recebido em 10/05:

```
Olá Marco, tudo bem?
Meu nome é ----- e faço parte da Thoughtworks! 
Gostaríamos de estar presente na Python Brasil deste ano como patrocinadoras. Conseguimos marcar um papo pra entender melhor algumas dúvidas que ficamos e como poderemos apoiar? 

Só me passar algumas opções de horário que eu agendo aqui :) 

Obrigada,
```

## Enviado em 10/05:
````
Olá, ----!

Meu nome é Juliany Raiol. Faço parte do time responsável pelo Patrocínio da Python Brasil, assim como o Marco, a Lahis e outras pessoas voluntárias!

Fico muito grata por seu contato e pela Thoughtworks desejar apoiar a Python Brasil esse ano. 

Essa semana temos os seguintes horários:
Quarta 11/05 | 10h ou 14:30h 
Quinta 12/05 | 14:30h 
Sexta 13/05 | 10h ou 19h

Fico no aguardo do seu retorno! Desde já muito obrigada.

Em anexo segue o nosso plano de patrocínio para mais detalhes. 

Atenciosamente,
````

## Recebido em 10/05:

```
Oie! Essa semana está um pouco difícil conseguir horário. 

Segue algumas propostas pra semana que vem: 
Quarta-feira, dia 18, às 11h30
Quinta-feira, dia 19, às 10h

Consegue em algum desses? Caso sim, aí já marco aqui :) 

Obrigada! 
-----
```

(....) demais emails foram de confirmação da reunião

**Comment by wasp-lahis** [comment]
## Enviado em 23/05:

```
Olá pessoal, Boa tarde! Tudo bem?

Consultamos a organização sobre os pontos levantados na reunião de ontem, e seguem as respostas.

Temos a previsão de abrir a submissão de atividades no dia 25 de maio, na quarta-feira da semana que vem. E não existe limitação de pessoas por empresa para submissão. Para compor a programação prezamos pela qualidade do conteúdo, diversidade de temas e sócio cultural das pessoas (sexualidade, identidade de gênero, raça, região de origem).

As pessoas que tiverem atividades aprovadas podem solicitar auxílio financeiro para cobrir custos de ingressos, hospedagem, deslocamento e alimentação. Dado a grande quantidade de solicitações de auxílio, nosso objetivo principal será prover que pessoas que tiverem atividades aprovadas e não tenham condições de arcar com todos os gastos do evento possam participar.

Devido ao Luciano Ramalho ter sido Keynote em 2019, nosso último evento presencial, em Ribeirão Preto - SP, e não ser uma prática repetir Keynotes, não há possibilidade de que isso se repita este ano. Além disso, como já destacado em nossa reunião com a TW, keynotes são escolhidos pela organização do evento e sua nomeação não está inclusa nos benefícios do plano de patrocínio.

Em relação à proposta de realizar o lançamento de um livro durante a Python Brasil, a organização do evento tem um parecer positivo. Tendo em vista a relevância de Luciano na comunidade Python, consideramos oportuno e relevante para o evento e seus participantes ter o contato direto com ele. Então, seria bastante interessante organizar uma sessão de autógrafos, de maneira análoga à que foi realizada em 2019, com data e horários divulgados como parte da programação do evento.

Os estandes serão fornecidos com a identidade visual da empresa e materiais básicos, a serem definidos mediante a contratação do serviço por parte da organização. Traremos mais detalhes sobre isso em breve.

Caso vocês tenham mais alguma dúvida além das elencadas acima, ou caso algum esclarecimento não tenha sido suficiente, não hesitem em nos contatar novamente!

​
Atenciosamente,
```

**Comment by wasp-lahis** [comment]
## Recebido em 23/05:

```
Oi Lahis, tudo bem?
Obrigada pela resposta! 
Adicionando a ----- aqui também :)
```

**Comment by wasp-lahis** [comment]
## Enviado em 31/05:

```
Olá ---- e ---, Boa tarde!

Passando para avisar que as[ chamadas para palestras, sprints e tutoriais da Python Brasil 2022 estão abertas](http://www.pretalx.com/python-brasil-2022/cfp). Gostaríamos de ressaltar que não existe limitação de pessoas por empresa para submissão. Para compor a programação, prezamos pela qualidade do conteúdo, diversidade de temas e sócio cultural das pessoas (sexualidade, identidade de gênero, raça, região de origem). 

Sobre uma possível colaboração entre a Thoughtworks e a Python Brasil, vocês já tem um posicionamento? Aguardamos com interesse ^^.
```

**Comment by wasp-lahis** [comment]
## Enviado 01/06:

```
Oi -----, tudo bem?
Muito obrigada por avisar! Vamos divulgar aqui internamente :) 

Sobre o patrocínio, temos super interesse sim :) 
Estamos só aguardando algumas respostas internamente em relação a budget! 
Te retorno logo sobre isso! 

Obrigada! 
```

**Comment by wasp-lahis** [comment]
(....)

## Recebido em 06/07/2022:

```
Oi Juliany, tudo bem?
Segue o contrato revisado e com as alterações do nosso time de legal. 
```

@pythonbrasil/apyb @julianyraiol  Poderiam avaliar, pfvr? https://pythonbrasil.freshdesk.com/a/tickets/8416

**Principais pontos de atenção:**
- data de pagamento TT
- prazo de inadimplência
- mudança de comarca

**Comment by cecivieira** [comment]
Ju,

É possível incluir uma cláusula prevendo multa para recisão do contrato.
Desse jeito, ainda que a empresa desista do contrato já assinado, o evento
recebe a multa.
No entanto, de forma geral, não é possível cancelar o pagamento de um
serviço já prestado. Ou seja, se depois de iniciar a contrapartida para a
partocinadora ela não pode se negar a realizar o pagamento de um serviço
que já iniciou.

**Comment by wasp-lahis** [comment]
## Enviado em 07/07/2022:

```
Olá ---, Boa tarde!

Estamos avaliando as alterações da minuta e surgiu uma dúvida: 
seria possível a TW realizar o pagamento antes de outubro?
Acreditamos que impactaria menos nosso evento, dado o valor do pacote. Poderiam avaliar, por favor?
 
[]s,
Python Brasil 2022
```

**Comment by wasp-lahis** [comment]
## Enviado em 13/07:

```
Olá ---, Bom dia!

Tudo bem?

Segue a minuta em pdf com as modificações que sugeriram. 
A partir do OK de vcs, iremos mandar a minuta via docusign para assinatura. 
Para isso, precisaremos do nome e email do responsável da TW pela assinatura de patrocinio de eventos e
 de mais uma testemunha do lado de vocês tb o/

Qualquer dúvida, não hesite em nos contatar.
Atenciosamente,
```

**Comment by wasp-lahis** [comment]
Minuta enviada para assinatura o/
@anadulce @julianyraiol

**Comment by wasp-lahis** [comment]
## Recebido em 14/07:

```
Oi Lahis, tudo bem?
Uma dúvida: Vocês finalizaram o cadastro no nosso site, conforme foi enviado pra vocês? 

Chequei com o time, e a gente vai conseguir fazer o pagamento adiantado, mas o seu cadastro precisa estar certinho aqui! 

Obrigada! 
```

@julianyraiol @pythonbrasil/apyb @anadulce O cadastro foi solicitado [nesse ticket](https://pythonbrasil.freshdesk.com/a/tickets/8390). Sabem dizer se já foi feito? Poderiam dar uma olhada pls?

**Comment by wasp-lahis** [comment]
@julianyraiol @pythonbrasil/apyb  @anadulce Oie gente,  seria bem massa ter esse din din antes de outubro.. poderiam dar uma olhada, por favor? Estou na dúvida se já fizemos isso pq esse cadastro tb é preciso para o patro da python nordeste.

Sobre o contrato da cota ouro, faltam as assinaturas do nosso lado (@anadulce e @julianyraiol ). Quando tiverem um tempo, poderiam assinar?

**Comment by julianyraiol** [comment]
oi @wasp-lahis, acabei de assinar o/

**Comment by wasp-lahis** [comment]
## Enviado em 26/07:

```
Olá ---, Boa tarde!

Tudo bem? 

Gostaríamos de agradecer novamente a confiança e interesse da TW em nosso evento!! Como próximos passos, precisaremos de algumas informações (logos e textos) da TW para fornecermos as contrapartidas ^^. Poderiam preencher nosso [formulário de coleta de informações](https://docs.google.com/forms/d/e/1FAIpQLScPNZ26umrahbSPjcpAvIB1UJiQJlcnRsdnBQIx8bOkdm-YDA/viewform?usp=sf_link)? Selecionando o pacote Ouro.

Se já quiserem adiantar a logo e texto para as redes sociais, site e assinatura do email, fiquem a vontade tb ^^!

Sobre o cadastro, você poderia nos confirmar se deu tudo certo, por favor? Ficamos na dúvida também sobre a data de pagamento.

Abs,
```

**Comment by wasp-lahis** [comment]
# Enviado em 02/08:

```
Olá ---, Boa noite!

Tudo bem?

Passando para avisar sobre os ingressos da Python Brasil 2022. 

Os cupons dos ingressos de uso livre do pacote Ouro (x10) são:​

(...)

 Os 10 colaboradores escolhidos por vocês, devem acessar nosso site e adquirir os ingressos por meio destes cupons. Link: https://www.eventbrite.com/e/python-brasil-2022-registration-356802725557
​
​
Sobre os assets, continuamos no aguardo. Caso já queiram adiantar o envio da Logo, para já anunciarmos a parceria entre Python Brasil e TW, fiquem a vontade também!

Ticket: https://pythonbrasil.freshdesk.com/helpdesk/tickets/8196
Abs,
```

**Comment by wasp-lahis** [comment]
## Recebido em 03/08:
```
Oi Lahis, tudo bem?
Já vou preencher esse formulário! 

Tudo certo com o cadastro. Criei aqui a ordem de compra pra vocês: ----
É só enviar a nota com essa ordem de compra para --- e o pagamento é feito em até 15 dias. 

Obrigada!
```

## Enviado em 03/08:
```
Olá, ---!

Obrigada pelas informações! Para gerar a nota fiscal, vamos precisar de mais três informações da TW:
- Nome do contato 
- Email do contato 
- Nº de celular/telefone
​
Essas informações são geralmente do financeiro, mas fiquem a vontade para indicar quem acharem mais apropriado. A Jusbrasil, por exemplo, nos passou as infos de quem estávamos trocando email mesmo.

Abs
```

**Comment by wasp-lahis** [comment]
Olá @pythonbrasil/apyb solicitei a NFe da TW (Ouro), ponto de atenção:

> É só enviar a nota com essa ordem de compra para [invoices-br@thoughtworks.com](mailto:invoices-br@thoughtworks.com) e o pagamento é feito em até 15 dias. 

(Ela deu a entender que depende mais da gente agora)

**Comment by wasp-lahis** [comment]
## Enviado em 09/08:
```
Olá, Bom dia!

Passando para enviar a NFe do patrocínio ouro da Python Brasil fechado com a TW (em anexo). Já fomos cadastrados no sistema de vocês e nossa ordem de compra é ----. 

Poderiam avisar quando o pagamento for efetuado, por gentileza?

Att,
```

**Comment by wasp-lahis** [comment]
##Enviado em 11/08:

```
Olá, Bom dia!

Passando para enviar a NFe do patrocínio ouro da Python Brasil fechado com a TW (em anexo). Já fomos cadastrados no sistema de vocês e nossa ordem de compra é ----. 

Enviamos anteriormente este email para o ----- , mas a --- pediu que contatássemos vocês. 
​
Poderiam nos ajudar? 

Att,
```

**Comment by wasp-lahis** [comment]
## Recebido em 12/06:

```
Olá Lahis,

Está tudo certinho e a nota já foi aprovada.
```

## Enviado em 12/06:
```
Olá,

Maravilha! Quando efetuarem o pagamento poderiam nos avisar, por gentileza?

Abs
```

**Comment by wasp-lahis** [comment]
## Recebido em 22/08:

> Boa tarde, Lahis!
> 
> O cadastro da Associação Python foi feito em nosso sistema com forma de pagamento por boleto bancário. Entretanto, não localizei o boleto no valor de R$ 80.000,00 em nosso DDA. Você pode nos enviar um boleto para pagamento da nota com data de vencimento em 31/08/2022, por favor?

## Enviado em 22/08:

> Olá, ---!
> 
> Tudo bem?
> ​
> O boleto em anexo atenderia vocês? Ficamos no aguardo de retorno.
> 
> Abs,

## Recebido em 22/08:

> Boa noite!
> 
> O anexo que você enviou só tem a nota fiscal.
> 
> 
> Abraço,

**Oie @pythonbrasil/apyb a TW tá querendo que geremos um boleto com validade 31/08. Poderiam dar uma olhada? A NFe não foi o suficiente TT**

**Comment by muriloviana** [comment]
@wasp-lahis acredito que a gente deva ter cadastrado incorretamente a forma de pagamento, pois nossa conta no BB não nos permite gerar boletos. Ou seja, teríamos que contratar este serviço junto ao banco para receber o patrocínio.

Consegue verificar com eles se podemos alterar esse cadastro para receber este valor via transferência bancária (TED)? Pode me colocar "diretoria@python.org.br" em cópia que qualquer coisa a gente já agiliza futuras interações nesta conversa.

**Comment by wasp-lahis** [comment]
> @wasp-lahis acredito que a gente deva ter cadastrado incorretamente a forma de pagamento, pois nossa conta no BB não nos permite gerar boletos. Ou seja, teríamos que contratar este serviço junto ao banco para receber o patrocínio.
> 
> Consegue verificar com eles se podemos alterar esse cadastro para receber este valor via transferência bancária (TED)? Pode colocar "[diretoria@python.org.br](mailto:diretoria@python.org.br)" em cópia que qualquer coisa a gente já agiliza futuras interações nesta conversa.

## Enviado em 22/08:

> Olá, ----!
> 
> Nossa atual conta no BB não nos permite gerar boletos, infelizmente. É possível alterar esse cadastro no sistema para receber o valor via transferência bancária (TED) ou pix? 
> 
> Ficamos no aguardo de seu retorno.

**Comment by muriloviana** [comment]
@wasp-lahis conseguimos alterar o perfil da Associação junto a TW, acredito que agora vai! Tu consegue pingar eles informando da alteração e solicitando o pagamento?

**Comment by wasp-lahis** [comment]
Oie @muriloviana ontem solicitei que eles mudassem p TED ou pix. Hoje retornaram com essas alterações no cadastro já. Acredito que está tudo certo, só fiquei na dúvida do quanto/se isso impactou na data de pagamento antiga 24/08. Mandei email perguntando:

> Olá pessoal, Boa tarde!
> 
> Obrigada por terem alterado o cadastro. Devido a essas modificações, ficamos na dúvida de qual seria a nova data de pagamento do patrocínio.
> 
> Ficamos no aguardo de um retorno!
> 
> Abs,

**Comment by wasp-lahis** [comment]
## Recebido em 26/08:

```
Boa tarde, Lahis!

O pagamento das notas será feita na próxima quarta-feira, 31/08/2022.
```

**Comment by wasp-lahis** [comment]
Status patro: https://docs.google.com/spreadsheets/d/1tnj6Um90g6FueWCAqZip4QvbLc9XXQdSRHXltFK2F34/edit?usp=sharing
