### ISSUE TITLE
LGPD

### ISSUE THREAD

**Issue by lskbr** [pythonbrasil/pybr2022-org#20]
- O que teremos que informar aos usuários do sistema?
- Compartilharemos alguma informação com os patrocinadores?
- O que acontece com os dados após a conferência?

**Comment by luzfcb** [comment]
Aqui um "Guia de Boas Práticas - Lei Geral de Proteção de Dados Pessoais (LGPD)" (atualizado em 08/2020)

https://www.gov.br/governodigital/pt-br/seguranca-e-protecao-de-dados/guia-boas-praticas-lgpd

**Comment by luzfcb** [comment]
Curso gratuito (2h de carga horária) https://www.ev.org.br/cursos/lei-geral-de-protecao-de-dados-lgpd
