### ISSUE TITLE
Realizar orçamentos para kit participante 

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#201]
### Descrição

- Procurar gráficas que façam peças em larga escala
- Entrar em contato com empresas locais e de outros estados para fazer o orçamento de itens para as pessoas participantes.

[Planilha](https://docs.google.com/spreadsheets/d/1XKYHh9feDZC3V1ZlrYHWi72Rh-DGtwYFo-BzZPEEUo8/edit#gid=0) para controle.

Exemplo que [camisa](https://drive.google.com/drive/folders/1iOuzl-O8fdCNyNyS19EptN-NTao9MJyI) 

### Requisitos para a atividade ser considerada como concluída

Verificar preços de alguns itens como:

- Camisa
- Corda e crachá
- Ecobag
- Caneca

Issue relacionada #60

**Comment by renan-assis-santos** [comment]
Coloquei aqui na planilha de orçamentos (na 3ª aba) os contatos que o pessoal do Manaus Plaza me passaram
https://docs.google.com/spreadsheets/d/1XKYHh9feDZC3V1ZlrYHWi72Rh-DGtwYFo-BzZPEEUo8/edit#gid=152492784

**Comment by julianyraiol** [comment]
Orçamento estandes
[PROPOSTA LUME x Juliany Raiol (1).pdf](https://github.com/pythonbrasil/pybr2022-org/files/8884834/PROPOSTA.LUME.x.Juliany.Raiol.1.pdf)
