### ISSUE TITLE
Patrocínio BotCity

### ISSUE THREAD

**Issue by wasp-lahis** [pythonbrasil/pybr2022-org#218]
### Descrição
Acompanhamento das tarefas relacionadas ao possível patrocínio do [BotCity](https://www.botcity.dev/)

A planilha de prospecção das empresas pode ser visualizada em #82 

### Requisitos para a atividade ser concluída
- Contrato assinado
- Patrocínio recebido em caixa
- Pendências pós evento concluídas

Ticket: [8349](https://pythonbrasil.freshdesk.com/a/tickets/8349) Patrocínio Python Brasil

**Comment by wasp-lahis** [comment]
## Recebido em 14/06:
```
Boa tarde pessoal, tudo bem?

Sou da BotCity, uma plataforma de automação em Python + visão computacional, com SDKs open source e licença community.

Temos interesse em patrocinar o Python Brasil e queria tirar algumas dúvidas em relação às cotas com vocês.

Podemos fazer um call no começo da semana que vem?

Obrigado!

```

## Enviado em 14/06:

```
Olá, ----!

​Tudo bem?

Massa! Podemos reunir sim! Aqui está nossa agenda da semana que vem:

- Seg 20/06 | 9h ou 14h (Brasília)   
- Ter 21/06  | 8h, 9h, 14h (Brasília ) 
- Qua 22/06 | 8h, 9h, 14h ou 18h  (Brasília ) 
- Qui 23/06 | 14h (Brasília ) 
- Sexta 24/06 | 8h, 9h ou 17h (Brasília )  

Fica a vontade para sugerir horários tb!
[]s
Atenciosamente,
Python Brasil 2022
```

**Comment by wasp-lahis** [comment]
## Recebido em 15/06:

```
Oi Lahis, tudo bem? Vamos na segunda às 14? Vocês me mandam um invite por favor?

Obrigado!
```

## Enviado em 15/06:

```
Olá, ----!

Combinado na Segunda 20/06 às 14h (Brasília)! Segue o link da chamada.
​
Até lá!
Att,
```

**Comment by wasp-lahis** [comment]
(...)

# Recebido em 13 Jul 2022:
```
Oi Thatianne, tudo bem? Desculpe a demora!

Estamos discutindo aqui para subir para a cota prata, mas estamos com o orçamento um pouco reduzido. Vocês acreditam que seria possível fechar a cota prata em torno de R$ 35k?

Obrigado e desculpe a demora!
````

# Recebido em 19/07:

```
Bom dia pessoal! Estamos programando o envio do time para o evento, e gostaria de saber se vocês tem algum retorno do que propusemos em aumentar a cota!

Obrigado,
```

## Enviado em 19/07:

```
Olá Lorhan, Bom dia!

Não será possível fecharmos a cota prata por esse valor, infelizmente.

Att,
Python Brasil 2022
```

**Comment by wasp-lahis** [comment]
## Recebido em 23/07:

## Enviado em 27/07:
```
Olá, ---!

Maravilha!! Obrigada pelo interesse e confiança em nosso evento! A Python Brasil 2022 vai ser massa!!

O estande orçado até o momento, inclui: 
  - Locação e montagem de estandes com 9m² de área (3 x 3m), com perfis de alumínio anodizado, placa MDF com carpete, iluminação e 01 tomada.  
​
-----, em breve retornaremos com o Manual do Expositor (layout e demais intruções) ^^.

-----, para que nosso time possa gerar a minuta e enviar para análise de vocês, precisaremos das seguintes informações:

- Razão Social
- CNPJ
- Endereço completo
- Inscrição municipal

Já para gerar a NFe, após assinatura do contrato, precisaremos:

- Nome de contato de pessoa responsável pelo financeiro
- Telefone de contato de pessoa responsável pelo financeiro
- Email de contato de pessoa responsável pelo financeiro

Ficamos noa aguardo.
Att,
```

**Comment by wasp-lahis** [comment]
## Recebido em 19/08:

```
Boa tarde, Lahis!
Tudo bem?

Por gentileza poderia me confirmar os dados para depósito.

Pois os dados informados na Nota Fiscal e contrato estão acusando inexistente, na hora efetuar o pagamento.
```
![bWcWJg8nP8GATXim8YlRsWlHLbZIiIafTQ](https://user-images.githubusercontent.com/7443249/185676175-348b2405-3521-4489-8017-a6ca383bbed6.png)


Oie @pythonbrasil/apyb, podem dar uma olhada? Não consegui identificar o que pode estar errado. Os dados bancários parecessem certo TT

**Comment by muriloviana** [comment]
@wasp-lahis agência que eles tentaram fazer a transferência tá errada 😅. O correto é 0089, o número 2 é o dígito da agência, o que geralmente não é utilizado para TED, apenas para transferências entre o mesmo banco.

Segue os dados para pagamento:
RAZÃO SOCIAL: ASSOCIAÇÃO PYTHON BRASIL
CNPJ: 09.344.485/0001-05
1 - BANCO DO BRASIL 
Cc: 78126-6
Agência: 0089-2

**Comment by wasp-lahis** [comment]
> @wasp-lahis agência que eles tentaram fazer a transferência tá errada 😅. O correto é 0089, o número 2 é o dígito da agência, o que geralmente não é utilizado para TED, apenas para transferências entre o mesmo banco.
> 
> Segue os dados para pagamento: RAZÃO SOCIAL: ASSOCIAÇÃO PYTHON BRASIL CNPJ: 09.344.485/0001-05 1 - BANCO DO BRASIL Cc: 78126-6 Agência: 0089-2

vlwzão!!

**Comment by wasp-lahis** [comment]
Oie gente, recebemos o pix da Botcity?

**Comment by wasp-lahis** [comment]
[Todos os benefícios](https://docs.google.com/spreadsheets/d/1tnj6Um90g6FueWCAqZip4QvbLc9XXQdSRHXltFK2F34/edit?usp=sharing) da cota foram fornecidos
