### ISSUE TITLE
Patrocínio Google

### ISSUE THREAD

**Issue by wasp-lahis** [pythonbrasil/pybr2022-org#228]
### Descrição
Acompanhamento das tarefas relacionadas ao possível patrocínio do Google

A planilha de prospecção das empresas pode ser visualizada em #82 

### Requisitos para a atividade ser concluída
- Contrato assinado
- Patrocínio recebido em caixa
- Pendências pós evento concluídas

Ticket: [8320](https://pythonbrasil.freshdesk.com/a/tickets/8320)  Python Brazil 2022 + Google

**Comment by wasp-lahis** [comment]
## Enviado em 23/05:

```
Hi . How are you?
My name is Thatianne Maruyama. I'm part of the organization of Python Brasil 2022, the largest conference about the Python programming language in Latin America.

In 2021, the event attracted 6078 registered attendees and spanned an entire week. Also, we had more than 16700 visualization on the first day! Here is the link for the landing page of the last edition (it's in Portuguese): https://2021.pythonbrasil.org.br/


This year, Python Brasil is going to Manaus! It will be the first edition the northern part of the country, closer to our South American neighbors. We are looking for companies and organizations which can sponsor the conference. Google was selected because it has already sponsored out event in 2019, so we thought it would be great to keep the partnership.

We have a Sponsoring Plan which we would like to present to you. Are you interested in arranging a meeting for us to present it and discuss a possible collaboration? I'm sending the presentation attached, so you can analyze previously.

Looking forward to hearing from you. Thanks in advance!


Best regards,
```

## Recebido em 02/06:

```
Hi Thatianne,

Nice to hear from you. I'm reviewing the sponsorship plan for Python Brasil on behalf of Google. I think we need a bit more information about the conference and the initiatives.
Would you be available for a video chat about this? 
Can you find an open time slot in my calendar for us to talk? Thank you
```

**Comment by wasp-lahis** [comment]
(...)

## Recebido 30/07:
```
Hi Juliany,

Looks like the contract has been signed.  Let's put a due date of August 1st.  In addition to the invoice, please also send the w8-benE, or equivalent documentation if you are a non-profit.  

Let me know if there's anything else I can assist with.

Thank you,
```

**Comment by wasp-lahis** [comment]
## Recebido em 05/07:

```
Hi Juliany,

Hope you had a great weekend.  Just wanted to send a quick reminder to see
if you can send over the invoice as well as the w8-ben-e so that we can process the payment.

Thank you,
----
```

**Comment by wasp-lahis** [comment]
@pythonbrasil/apyb  podem dar uma força na geração do invoice do google (R$ 50K, USD 10.000 | cota prata)? Eles solicitaram tem 1 semana e hoje cobraram de novo TT 

Eles pediram p colocar a data de pagamento para 1º de agosto: 
```Let's put a due date of August 1st.```

a Data de pagamento tem que ser a mesma data de emissão? Se sim, já gero de novo aqui

**Comment by wasp-lahis** [comment]
## Enviado em 05/07:

```
Hi ----!

Excuse us for the delay in our response. W8-ben-e document is attached.

The invoice is being generated for the payment date August 1st and we will send it until Friday.

Let us know if you have any doubts!

Best,
Python Brasil 2022
```

**Comment by rougeth** [comment]
> a Data de pagamento tem que ser a mesma data de emissão?

Eu entendo que não.

Essa era a única dúvida? Como podemos ajudar com o invoice?

**Comment by wasp-lahis** [comment]
Oie @rougeth, obrigada! Era só essa dúvida mesmo. Eu solicitei o invoice ontem. Quando vcs tiverem um tempo, podem mandar p Ju?

**Comment by wasp-lahis** [comment]
# Enviado 11/07: 

```
Hi Lahis!

I scheduled the wire.  It should be initiated on Monday and arrive by July 15th.  If you don't see it in your account by the 16th please let me know and I can make some inquiries or process it again if there was an error.

Thanks!
```

**Comment by wasp-lahis** [comment]
## Enviado em 13/07:

```
Hi ----!

Thanks! We'll let you know when the payment arrives here o/

As the next steps in our collaboration, we need you to complete the asset collection form, selecting the Silver package: [link.](https://forms.gle/HfXYu23KXKLP8LD7A)

If you already want to attach the Google logo and the text (200-700 characters) for us to share on Python Brasil's social networks, feel free ^^.

Thank you! and let us know if you have any questions.
Best,
Python Brasil 2022
```

**Comment by wasp-lahis** [comment]
## Recebido em 14/07:

>Hi Lahis,
>Attached please find our logos and our [branding guidelines here](https://about.google/brand-resource->center/guidance/sponsorships/#sponsorships). Please note the full color logo should be used on a light background. For our >website URL you can use the following: https://opensource.google/.
 
>Here is our company description: **_Google believes that open source is good for everyone. By being open and freely available, it enables and encourages collaboration and the development of technology._**
 
>--- will be your contact for activating the remaining benefits.  Please do not hesitate to contact us if you have any questions.
>Thank you,

No texto acima, tem algumas recomendações para p/ o uso da logo do Google. A logo está em: [link](https://drive.google.com/drive/folders/1986QZhstN12NPHsdkJhfToXhbuPiERru?usp=sharing)

@pythonbrasil/time-comunicacao @menezesgabriel quando tiverem um tempo, podem bolar o post para a cota prata?

@richardson-souza @pythonbrasil/time-site quando tiverem um tempo, poderiam add a logo no site da PyBR?

**Comment by wasp-lahis** [comment]
Oie @pythonbrasil/apyb, o din din do Goole caiu na nossa conta (silver)? O prazo era sexta passada. O carinha de lá comentou que se não tivesse caído deveríamos entrar em contato com ele

**Comment by muriloviana** [comment]
@wasp-lahis o dinheiro caiu sim, precisamos (APyB) fechar o câmbio para liberar em caixa. Logo, o envio da remessa do Google foi feito certinho, agora depende de nós (APyB) 👍

**Comment by wasp-lahis** [comment]
## Enviado em 18/07:

```
Hi --- and ---!

We have received the sponsorship payment successfully!! We would like to thank Google and team for contributing to this year's edition of Python Brasil!! It will be great! 

About brand exposure, could you check if the attached image and post text is ok for you? We intend to post on our social networks (instagram, twitter and facebook)

Post text:
Thanks to @google for sponsoring and helping to build Python Brasil 2022 

[PT]Obrigado à Google por patrocinar e ajudar a construir a Python Brasil 2022 

[ES]Gracias a Google por patrocinar y ayudar a construir Python Brasil 2022 
---
[EN] Google believes that open source is good for everyone.
By being open and freely available, it enables and encourages collaboration and the development of technology.

[PT]O Google acredita que o código aberto é bom para todos.
Por ser aberto e disponível gratuitamente, permite e incentiva a colaboração e o desenvolvimento de tecnologia.

[ES]Google cree que el código abierto es bueno para todos.
Al ser abierto y de libre acceso, permite y fomenta la colaboración y el desarrollo de tecnología.

We would like to tag you on our social media ^^. Do you confirm that these addresses below are from Google?
Instagram: https://www.instagram.com/google/
Facebook: https://www.facebook.com/GoogleBrasil
Twitter :  https://twitter.com/googlebrasil

​Google logo on the our website <3 : https://2022.pythonbrasil.org.br/

Best,
Lahis Almeida
Python Brasil 2022
```

**Comment by wasp-lahis** [comment]
## Recebido em 18/07:

```
Hi Lahis,

The messaging looks great.
For the social media tagging, please use the following accounts instead:

Instagram: https://www.instagram.com/google/ 
Facebook: https://www.facebook.com/GoogleOpenSource/ 
Twitter : https://twitter.com/GoogleOSS

Thank you.
```

@menezesgabriel @pythonbrasil/time-comunicacao

**Comment by menezesgabriel** [comment]
@wasp-lahis Publicado hoje dia 19/07/2022 com todas as alterações solicitadas.

**Comment by wasp-lahis** [comment]
Oie @pythonbrasil/apyb, vocês saberiam informar quanto recebemos de fato do Google? Estávamos estimando receber por volta de ~45k por conta dos impostos e taxas : /

**Comment by muriloviana** [comment]
@wasp-lahis o valor recebido, sem o desconto da taxa de 10% da APyB, foi de R$53.830,65 (cinquenta e três mil oitocentos e trinta reais e sessenta e cinco centavos) no dia 18/07/2022.

Link da NFe, SWIFT e comprovante de recebimento: https://drive.google.com/file/d/1Q09UVAVYe0OuuMfGTRyovxxKUamXSoSg/view?usp=sharing

**Comment by wasp-lahis** [comment]
# Enviado em 01/08:
```
Hi folks!

We have some good news about Python Brazil tickets sale:

For our sponsors, we will freeze the sale of tickets at the 1st lot (R$ 220.00), regardless of the current lot. It works like this:
For better control and security, we will create promotional codes according to the number of tickets you wish to purchase. We can sell individually or you can indicate a number of employees and we will generate a NF/invoice for payment!

​We continue to wait for the requested assets and if you have any doubt, let us know o/
​
Best,
````

**Comment by wasp-lahis** [comment]
[Todos os benefícios](https://docs.google.com/spreadsheets/d/1tnj6Um90g6FueWCAqZip4QvbLc9XXQdSRHXltFK2F34/edit?usp=sharing) da cota foram fornecidos
