### ISSUE TITLE
Patrocínio AWS

### ISSUE THREAD

**Issue by wasp-lahis** [pythonbrasil/pybr2022-org#229]
### Descrição
Acompanhamento das tarefas relacionadas ao possível patrocínio do Amazon

A planilha de prospecção das empresas pode ser visualizada em #82 

### Requisitos para a atividade ser concluída
- Contrato assinado
- Patrocínio recebido em caixa
- Pendências pós evento concluídas

Ticket: TODO

**Comment by wasp-lahis** [comment]
Oie @rougeth, acha que pode dar certo ainda o patro da AWS?

**Comment by rougeth** [comment]
Não sei @wasp-lahis :/ Não tive resposta deles ainda.

**Comment by rougeth** [comment]
Não vai rolar.
