### ISSUE TITLE
Transmissão online

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#23]
Utilizar o streamyard para realizar a transmissão ao vivo.

**Comment by lskbr** [comment]
- 2020 foi gratis
- 2021 foi pago?
Se formos pagar, quanto custaria?

**Comment by lskbr** [comment]
- Temos empresas em Manaus que fazem isso?
- Temos ideia do custo?
- Podemos organizar algo na própria comunidade?
- 
Eu pensei em microfones sem fio, ou num sistema que grave o som da palestra + tripés para filmar.

**Comment by julianyraiol** [comment]
Estamos falando sobre isso na [issue 38](https://github.com/pythonbrasil/pybr2022-org/issues/38)
