### ISSUE TITLE
Parceria Packt

### ISSUE THREAD

**Issue by thaty-maru** [pythonbrasil/pybr2022-org#235]
### Descrição
Acompanhamento das tarefas relacionadas à parceria com a Packt

A planilha de prospecção das empresas pode ser visualizada em #82 

### Requisitos para a atividade ser concluída
- Contrato assinado
- Patrocínio recebido em caixa
- Pendências pós evento concluídas

Ticket: [8170](https://pythonbrasil.freshdesk.com/a/tickets/8170)  PythonBR 2022 | Packt partnership offer.

**Comment by wasp-lahis** [comment]
Oie @menezesgabriel aqui estão os assets da Packt (texto, logo e redes sociais): 

https://drive.google.com/drive/folders/1shbEIcyllSjhrUID1bC9YrG-OEK-6f1N?usp=sharing

**Comment by wasp-lahis** [comment]
não deu certo : /
