### ISSUE TITLE
Apoio - Prefeitura de Manaus | Cassina

### ISSUE THREAD

**Issue by jailsonpj** [pythonbrasil/pybr2022-org#236]
### Descrição
Entrar em contato o Casarão de Inovação Cassina da prefeitura de Manaus para realização dos tutorias e sprint no local.

**Comment by jailsonpj** [comment]
Eu entrei em contato com a administração do Casarão de inovação Cassina (coworking da prefeitura de Manaus). Para conseguir o local para realizarmos os tutoriais e sprints no local.

**Comment by jailsonpj** [comment]
Observações do local:
- O local dispões de um espaço grande com bancadas e cadeiras para 54 pessoas
- 1 auditório para 30 pessoas
- 1 espaço para cooffe break
- Caixa de som, microfone, datashow e tela branca

**Comment by jailsonpj** [comment]
![photo1656430613 (9)](https://user-images.githubusercontent.com/13952136/176221678-8e765adf-3997-416f-aac7-c000fb2fd604.jpeg)
![photo1656430613 (8)](https://user-images.githubusercontent.com/13952136/176221686-01ea9e56-150b-4d15-940c-4fd77fd05349.jpeg)
![photo1656430613 (7)](https://user-images.githubusercontent.com/13952136/176221689-d99c434f-2662-4ea0-93c0-86ae42d4d141.jpeg)
![photo1656430613 (6)](https://user-images.githubusercontent.com/13952136/176221695-40915890-2ec2-4973-b9e1-578891b3f905.jpeg)
![photo1656430613 (5)](https://user-images.githubusercontent.com/13952136/176221698-cd13306e-94fc-4875-89d2-edd70958ad9d.jpeg)
![photo1656430613 (3)](https://user-images.githubusercontent.com/13952136/176221714-3fdbb352-ffc9-4a35-830d-fa0296e4616c.jpeg)

![photo1656430613 (4)](https://user-images.githubusercontent.com
![photo1656430613](https://user-images.githubusercontent.com/13952136/176221905-ce7a814f-4bd4-4e5e-8fcd-97778363b5ae.jpeg)
/13952136/176221706-acd18759-1ca4-4bca-9219-d2e28d28d8cb.jpeg)
![photo1656430613 (2)](https://user-images.githubusercontent.com/13952136/176221893-772d1bb9-4d3c-44da-94bd-b4843c6d6b51.jpeg)

![photo1656430613 (1)](https://user-images.githubusercontent.com/13952136/176221880-022eb0a6-9e9c-4829-a805-9790e3de06f1.jpeg)

**Comment by jailsonpj** [comment]
Observações 2: 
- O local é novo
-  Fica localizado no centro histórico de Manaus

Apoio Prefeitura:
- O órgão administrador da prefeitura se dispôs em divulgar nas redes o evento da Python Brasil
- Eles não querem nenhuma contra partida , somente que o evento seja realizado no local.

**Comment by renan-assis-santos** [comment]
Po, achei mto bom @jailsonpj .
Só uma dúvida o que seria isso de "não querem nenhuma contra partida"? N querem nada em troca? Dinheiro, prioridade nas sprints/tutoriais? kkk

**Comment by jailsonpj** [comment]
Não. Eles só querem a oportunidade de apoiar o evento.

**Comment by jailsonpj** [comment]
O que ficou decidido foi que faremos os tutorias e sprints no espaço do LUDUS e OCEAN Manaus que fica localizado na UEA.
