### ISSUE TITLE
Estilo para a camisa do evento

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#238]
### Campanha
Solicitação de arte para ser utilizada na camisa do evento. 

Nela é necessário adicionar a logo, além de itens que remetam à região e ao evento. Acredito que seria legal ser uma camisa de cor clara para não absorver muito calor.

 
**Data para entrega**: 01/08/2022

**Comment by jailsonpj** [comment]
Oi gente, pensei que se fossemos fazer as camisas estilo Abadá poderiam ficar nesses estilo:

https://fortal.com.br/wp-content/uploads/2022/07/WhatsApp-Image-2022-07-19-at-16.43.11-2-573x1024.jpeg

Daí poderiamos usar as ondinhas que temos na nossa identidade visual nas camisas e testar sem manga ou com manga.
