### ISSUE TITLE
Patrocínio Vinta

### ISSUE THREAD

**Issue by wasp-lahis** [pythonbrasil/pybr2022-org#243]
### Descrição
Acompanhamento das tarefas relacionadas ao possível patrocínio da [Vinta](https://www.vinta.com.br/careers/developer/).

A planilha de prospecção das empresas pode ser visualizada em #82 

### Requisitos para a atividade ser concluída
- Contrato assinado
- Patrocínio recebido em caixa
- Pendências pós evento concluídas

Ticket: [8275](https://pythonbrasil.freshdesk.com/a/tickets/8275) Vinta & Python Brasil 2022

**Comment by wasp-lahis** [comment]
Oie @pythonbrasil/apyb, passando p avisar que solicitamos a NF da Vinta (Cobre - 5k) o/

**Comment by wasp-lahis** [comment]
## Enviado em 14/07:

```
Olá, ---!

Em anexo segue a NF para o pagamento do patrocínio da Python Brasil (pacote Cobre).

Ficamos no aguardo tb dos assets, solicitados no email anterior, para fornecermos as contrapartidas 
e divulgarmos a parceria entre Vinta e Python Brasil <3

Qualquer dúvidas, não hesitem em nos contatar.
Atenciosamente,
Python Brasil 2022
```

**Comment by wasp-lahis** [comment]
## Recebido em 21/07

```
Lahis, boa tarde!

Obrigada pelas informações.

Preenchi o formulário e segue comprovante de pagamento.

Algo ainda está pendente? Quais os próximos passos?
```

```
Lahis,

Desconsidera esse comprovante por favor, amanhã enviaremos o correto.

Abs,
```

**Comment by wasp-lahis** [comment]
Oie @pythonbrasil/time-comunicacao @menezesgabriel , a Vinta (Cobre) preencheu todos os dados do nosso formulário de assets (logo, texto e redes sociais).

Link: https://drive.google.com/file/d/1mT1CnpkkuslvhZKxwlrAWJDNqMdylCiF/view?usp=sharing

Quando tiverem um tempo, poderiam fazer um post divulgando o Patro? Lembrando que precisaremos validar com eles.

**Comment by wasp-lahis** [comment]
## Enviado em 21/07:

```
Olá ---!

Obrigada! Ficaremos no aguardo do comprovante.

Sobre os próximos passos, iremos colocar a logo da Vinta em nosso site e divulgar nas redes sociais. 
Antes de realizar essas divulgações, iremos validar com vocês ^^.

E uma boa notícia é que a venda dos ingressos da Python Brasil 2022 está aberta! 
Para as empresas patrocinadores venderemos os ingressos à preço de 1º lote até a data do evento. Segue o link de inscrição:  [link](https://www.eventbrite.com/e/python-brasil-2022-registration-356802725557).

Abs,
```

**Comment by wasp-lahis** [comment]
## Recebido em 22/07:
```
Boa tarde, Lahis!

Segue em anexo o comprovante de pagamento correto. Confirma o recebimento, por favor? :)

Abs,
```

Oie @pythonbrasil/apyb , recebemos o din din da Vinta? (Cobre - 5k)

**Comment by rougeth** [comment]
Caiu sim @wasp-lahis - https://github.com/apyb/tarefas/issues/112#issuecomment-1192882678

**Comment by wasp-lahis** [comment]
## Enviado em 25/07:

```
Olá ---, Bom dia!

Confirmamos o recebimento do pagamento! Gostaríamos de agradecer a Vinta e time por ajudarem a construir mais uma edição da Python Brasil! Vai ser massa ^^

Em breve retornaremos para vocês validarem a logo em nosso site e arte para as redes sociais.

Att,
```

**Comment by menezesgabriel** [comment]
Oi @wasp-lahis  o link informado é somente da legenda e das redes sociais, onde eu poderia pegar a logo?

link informado: https://drive.google.com/file/d/1mT1CnpkkuslvhZKxwlrAWJDNqMdylCiF/view?usp=sharing

**Comment by wasp-lahis** [comment]
Oie @menezesgabriel vc encontra os outros assets aqui: https://drive.google.com/drive/folders/1shbEIcyllSjhrUID1bC9YrG-OEK-6f1N?usp=sharing

**Comment by menezesgabriel** [comment]
Arte da vinta compartilhada no discord, no aguardo da aprovação

**Comment by wasp-lahis** [comment]
## Enviado em 27/07:
````
Olá pessoal, Bom dia!

Segue em anexo a arte de divulgação da parceria entre Vinta e Python Brasil. O texto do post será:
````
> Estamos contentes em anunciar a @vintasoftware como patrocinadora Cobre da Python Brasil 2022 💛
> `-----
> Somos uma consultoria com 9 anos de mercado e uma forte conexão com a comunidade Python desde sempre. Open-source e work-life balance estão na base de como atuamos com nossos clientes internacionais.
>
````
Poderiam validar se está tudo ok com a arte e texto, por favor?
Att,
````

**Comment by wasp-lahis** [comment]
Status do patro: https://docs.google.com/spreadsheets/d/1tnj6Um90g6FueWCAqZip4QvbLc9XXQdSRHXltFK2F34/edit?usp=sharing
