### ISSUE TITLE
Patrocínio Grupo SBF 

### ISSUE THREAD

**Issue by wasp-lahis** [pythonbrasil/pybr2022-org#246]
### Descrição
Acompanhamento das tarefas relacionadas ao possível patrocínio da [Grupo SBF](https://ri.gruposbf.com.br/).

A planilha de prospecção das empresas pode ser visualizada em #82 

### Requisitos para a atividade ser concluída
- Contrato assinado
- Patrocínio recebido em caixa
- Pendências pós evento concluídas

Ticket: [8429](https://pythonbrasil.freshdesk.com/a/tickets/8429) Python Brasil 2022

**Comment by wasp-lahis** [comment]
Oie @julianyraiol  @pythonbrasil/apyb e @pythonbrasil/time-patrocinio , modifiquei a minuta que a SBF preparou. 

[Link da Minuta para a cota Bronze](https://docs.google.com/document/d/139ZJ9NBlRIWdiSPBAJDROVWPWwbBORrt/edit?usp=sharing&ouid=104240651414053856255&rtpof=true&sd=true)

**Os principais pontos que add foram:**
> - Dados da apyb
> - Anexo de contrapartidas
> - Anexo CdC
> - Claúsula em que eles abdicam do Job Fair presencial
> - Retirada da claúsula 4.3, que não previa multa no caso de não pagamento -> contradiz a 5.3
> - Formato de pagamento combinado por email (À vista 60 dias)

Vou enviar amanhã entre 12-13h (Manaus). Fiquem a vontade para revisar. No caso de inclusão, coloquem em formato de comentários plss.

**Comment by wasp-lahis** [comment]
Obrigada gente! Vou enviar por agora p SBF.

Vou fazer essas adaptações para a minuta da da Saks e mais tarde p/ o template da minuta de Patro tb

**Comment by wasp-lahis** [comment]
## Enviado em 26/07:

```
Olá -----, Boa tarde!

Tudo bem?

Segue a minuta revisada pelo nosso time. Os principais pontos alterados/incluídos foram:

- Dados da Associação Python Brasil
- Valor da cota de patrocínio e formato de pagamento combinado por e-mail (À vista 60 dias)
- Inclusão de três anexos à minuta:
   - Anexo I: Contrapartidas que a Python Brasil oferece para o pacote Bronze 
   - Anexo II: Código de Conduta da Python Brasil
   - Anexo III:  Termo de Doação, Ciência e Consentimento Pessoas Jurídicas
​
Ficamos no aguardo do retorno de vocês e qualquer dúvida, estamos à disposição!
Att,
```

**Comment by wasp-lahis** [comment]
## Recebido em 19/08:

```
Olá, Lahis!

Precisamos de retorno sobre os dados bancários.
Não conseguirei fazer os pagamento necessários.

Ontem enviei email solicitando, mas até o momento sem retorno.

Para esta solicitação precisamos anexar os documentos:
Comprovante Bancário (Cabeçalho de extrato que contenha Razão Social, CNPJ e dados do Banco, Agência e conta ou cópia de cheque)

Você consegue me responder até quando?

Abs,
```

## Enviado em 19/08:
```
Olá, ----!

Estamos providenciando o comprovante bancário. Em breve retornaremos. Para os outros patrocínios, os seguintes dados foram suficientes:

Segue os dados para pagamento:
RAZÃO SOCIAL: ASSOCIAÇÃO PYTHON BRASIL
CNPJ: 09.344.485/0001-05
1 - BANCO DO BRASIL
Cc: 78126-6
Agência: 0089-2

A Nfe de patrocínio já serviria talvez de comprovante para vocês?

Att,

```

**Comment by wasp-lahis** [comment]
Oie @pythonbrasil/apyb , boa noite! Conseguem dar uma olhada nisso p essa semana que está vindo pls?

> Para esta solicitação precisamos anexar os documentos:
> Comprovante Bancário (Cabeçalho de extrato que contenha Razão Social, CNPJ e dados do Banco, Agência e conta ou cópia de cheque)
> 
> Você consegue me responder até quando?

Realmente não sei pq isso trava a assinatura da minuta de contrato, mas eles estão sendo insistentes TT

**Comment by muriloviana** [comment]
@wasp-lahis verificarei isso, te dou um retorno até amanhã final do dia.

**Comment by muriloviana** [comment]
@wasp-lahis não sei se ao certo se isso seria suficiente, mas, fica aqui a tentativa.

<img width="1050" alt="Screen Shot 2022-08-21 at 19 23 54" src="https://user-images.githubusercontent.com/6524275/185813323-aacf6de3-280e-4d80-81f9-82dd7ac59712.png">

**Comment by wasp-lahis** [comment]
> @wasp-lahis não sei se ao certo se isso seria suficiente, mas, fica aqui a tentativa.
> 
> <img alt="Screen Shot 2022-08-21 at 19 23 54" width="1050" src="https://user-images.githubusercontent.com/6524275/185813323-aacf6de3-280e-4d80-81f9-82dd7ac59712.png">

Vou mandar p eles. Vlw!

**Comment by wasp-lahis** [comment]
OIe @pythonbrasil/apyb @muriloviana Solicitei a Nfe da SBF (Bronze). Eles pediram isso aqui:

> Você pode gerar a nota fiscal para seguirmos como pagamento?
> o número do Pedido 4500311604, deve constar na nota.

**Comment by wasp-lahis** [comment]
Mandaram essas infos tb: https://pythonbrasil.freshdesk.com/a/tickets/8753?lang=pt-BR
