### ISSUE TITLE
Criação de post para divulgação de datas do evento

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#250]
Datas que precisamos divulgar: reunião do dia 29 de junho https://github.com/pythonbrasil/pybr2022-org/issues/232 

20/08/22 até 30/08/22 - Avaliação das palestras submetidas (processo feito pela comunidade)
31/08/22  até 09/10/22 - Avaliação final por parte da organização 
10/08/22 - Envio dos convites para as palestrantes selecionadas
17/08/22 - Divulgação das palestras nas redes sociais
15/09/22 - Divulgação da grade
17/10/22 - Python Brasil 2022

**Comment by julianyraiol** [comment]
seriam essas informações né @anadulce @renan-assis-santos?

**Comment by renan-assis-santos** [comment]
Só uma correção, coloquei a data final de review por parte dos palestrantes pra dia 31/07 23:59:59, isso pq eu atrasei dois dias pra soltar pra todo mundo e tbm pq mto provavelmente podemos ir adiantando o nosso lado da avaliação antes deles acabarem

**Comment by menezesgabriel** [comment]
Criei uma arte e compartilhei no Discord, no aguardo da aprovação.

**Comment by menezesgabriel** [comment]
Postagem publicada dia 26/07/22
