### ISSUE TITLE
Criação de post para divulgar modelo de avaliação de palestras

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#251]
Compartilhar no post alguns itens do modelo de [avaliação](https://rgth.co/pt-br/blog/modelo-de-avaliacao-das-atividades-da-python-brasil/
)

**Comment by renan-assis-santos** [comment]
Aqui poderia ser um post só avisando tipo
"Pessoas que submeteram palestras, começamos o período de avaliação de atividades, verifiquem seus emails"

**Comment by renan-assis-santos** [comment]
Só pra referencia, o email de instruções para a avaliação das atividades segue aqui embaixo

Revisão de atividades na Python Brasil 2022
—
Olá, {name}! Tudo bem?

A Python Brasil é feita pela comunidade para a comunidade, visando difundir a linguagem, promover a troca de experiências e manter a comunidade crescendo igualmente em público e impacto social.

Seguindo a premissa de envolver a comunidade, você deve ter recebido um email sendo convidado a participar da equipe organizadora “Revisores” do evento. Assim, convidamos você a avaliar as submissões que tivemos e colaborar com a determinação dos conteúdos que serão abordados no evento.

Para que as avaliações não sejam enviesadas, as propostas estarão anonimizadas.

A avaliação deverá seguir o Código de Conduta (https://python.org.br/cdc/). Se você ferir o código de conduta durante esta avaliação, em suas respostas nas questões dissertativas, suas submissões serão penalizadas com desclassificação do evento. 
Caso você considere que a proposta de submissão que está avaliando fere o código de conduta, entre em contato com a organização pelo e-mail [eventos@python.org.br](mailto:eventos@python.org.br).

Considere que o último dia para fazer a revisão das atividades é dia 31/07/2022 23:59:59 (Horário de Manaus)

Contamos com a sua colaboração para selecionar as melhores atividades e fazer uma Python Brasil incrível!
Organização da {event_name}

**Comment by menezesgabriel** [comment]
Criei uma arte e compartilhei no Discord, no aguardo da aprovação.
