### ISSUE TITLE
Contratar o serviço de segurança, bombeiros e ambulância

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#252]
Na reunião do dia 20.07, foi decidido que iremos contratar um serviço de segurança, bombeiros e ambulância que estarão disponíveis durante os 4 dias de evento no Centro de Convenções. 

#245

**Comment by julianyraiol** [comment]
Orçamento realizado com a empresa R.R Emergências Médicas #237 

[ORÇAMENTO - EVENTO DIAS 20, 21, 22 E 23 DE OUTUBRO.pdf](https://github.com/pythonbrasil/pybr2022-org/files/9161864/ORCAMENTO.-.EVENTO.DIAS.20.21.22.E.23.DE.OUTUBRO.pdf)

**Comment by julianyraiol** [comment]
Contrato enviado pela empresa. É preciso fazer a nossa revisão.

[CONTRATO EVENTO DE TECNOLOGIA - DIAS 20, 21, 22 E 23 DE OUTUBRO DE 2022.pdf](https://github.com/pythonbrasil/pybr2022-org/files/9161872/CONTRATO.EVENTO.DE.TECNOLOGIA.-.DIAS.20.21.22.E.23.DE.OUTUBRO.DE.2022.pdf)

**Comment by renan-assis-santos** [comment]
Pra mim ficou claro e acho suficiente o tamanho da equipe que informaram. N sei dizer de preços pq n tenho parâmetros, mas achei ok até.
Até que horas temos o aluguel do vasco vasquez em cada dia?

**Comment by rougeth** [comment]
Dúvidas:
- Qual será a alocação nos dias do evento? Quantos bombeiros e seguranças estão no evento?
- Não dá pra pagar 100% por um serviço antes dele acontecer. Sugere o pagamento dos 50% no dia 26 de outubro (três dias úteis após o fim do evento)
