### ISSUE TITLE
Adicionar Termo Apyb em minuta de Patrocínio Nacional

### ISSUE THREAD

**Issue by wasp-lahis** [pythonbrasil/pybr2022-org#253]
Adicionar Termo de Doação, Ciência e Consentimento Pessoas Jurídicas na minuta de Patrocínio

### Requisitos para a atividade ser considerada como concluída

- Minuta atualizada.

**Comment by wasp-lahis** [comment]
Oie @pythonbrasil/apyb , mudei a minuta Nacional para incluir o termo: [link](https://docs.google.com/document/d/1otwAGDZihbY-xPKrTjc9NlYaSFzLpo0V/edit?usp=sharing&ouid=104240651414053856255&rtpof=true&sd=true) . Dps deem uma olhada pls.

Vocês teriam a versão em inglês tb? Daí já poderíamos colocar na minuta internacional.

**Comment by rougeth** [comment]
Modelo revisado @wasp-lahis. Não temos uma versão em inglês do termo :/
