### ISSUE TITLE
Preencher Formulário da PSF

### ISSUE THREAD

**Issue by wasp-lahis** [pythonbrasil/pybr2022-org#256]
O objetivo desta task é preencher de forma colaborativa e mais prática o forms da PSF, no qual solicitaremos apoio financeiro para nosso evento.

### Requisitos para a atividade ser considerada como concluída

- Formulário preenchido e enviado

**Comment by wasp-lahis** [comment]
[Link do Formulário PSF](https://docs.google.com/document/d/1W3E2Ad1YzIPYop2kmOwTKDvoBj-wEfN3Relse2xmW3g/edit?usp=sharing)

**Comment by wasp-lahis** [comment]
[OK] 7/8 etapas do forms

> [in progress] 3) Proposal

**Comment by wasp-lahis** [comment]
**O únicos item que falta é a planilha de orçamentos.**

Nosso orçamento está incompleto. Eu e a @julianyraiol  solicitamos um mais atualizado da IAI PROMO. Pior dos casos, podemos mandar o que temos mesmo!

Sobre o relatorio de 2019, @anadulce e @muriloviana, poderiam dar uma força pls? Não precisamos dele p submeter, mas a PSF já nos cobrou por email recentemente. Acredito que precisaremos em futuro bem próximo

**Comment by wasp-lahis** [comment]
## Enviado em 19/08:

> Hi ---!
> 
> In the previous financial aid submission we did, we still hadn't finished filling it out. We submitted the form by mistake.
> 
> We have just submitted a form with more complete and detailed information.
> 
> Could you confirm receipt please?
> 
> For more submission details, you can access:  https://docs.google.com/document/d/1ISpJ8HdTt_6J7NrU6NYcGdxgnVRMmuiD/edit?usp=sharing&ouid=104240651414053856255&rtpof=true&sd=true
> 
> Let us know if you have any questions!
> ​
> Best and Thank you,

**Comment by wasp-lahis** [comment]
## Recebido em 18/08:
```
Hello,
We have received your grant request. Please note that it takes up to 6 weeks to review.
For further information about our grant program, check out:
– https://www.python.org/psf/grants/
– https://www.python.org/psf/grants/faq/
```

**Comment by wasp-lahis** [comment]
## Recebido em 22/08:

> Hi Lahis,
> 
> Yes, we have received your new grant submission, thank you. From my previous email,
> 
> 1. Have you contacted our Trademark Committee ([psf-trademarks@python.org](mailto:psf-trademarks@python.org)) for permission to use your logos and word marks?
> 4. I don't see an event report for Python Brasil 2019. Could you or someone else with Python Brazil [submit a follow-up grant report](https://docs.google.com/forms/d/e/1FAIpQLSdtTVQLoCeCiPL_H3FWlhqbul79SxfnsqLGPrwCmL7Fvkd35g/viewform)?

cc @julianyraiol

ps: vou entrar em contato com o email do item 1. O que eu respondo para o item 2  @anadulce ?

**Comment by wasp-lahis** [comment]
## Enviado para psf- trademarks  em 22/08:

> Hi folks!
> 
> I'm part of Python Brasil 2022 organization team. We made a grant submission for PSF in August 19, 2022. They tell us that we need to enter in contact with you to give permission to you to use our logos and word marks. Can you tell us more about this? How it works?
> 
> Best and Thank you!

## Enviado p/ PSF em 22/08:

> Hi, ----!
> 
> 1. Have you contacted our Trademark Committee ([psf-trademarks@python.org](mailto:psf-trademarks@python.org)) for permission to use your logos and word marks?
> R: Yes, we contacted psf-trademarks today .
> 
> 4. I don't see an event report for Python Brasil 2019. Could you or someone else with Python Brazil [submit a follow-up grant report](https://docs.google.com/forms/d/e/1FAIpQLSdtTVQLoCeCiPL_H3FWlhqbul79SxfnsqLGPrwCmL7Fvkd35g/viewform)?
> R: We are finalizing the Python Brasil 2019 report and soon will send it here.
> Best,

**Comment by wasp-lahis** [comment]
## Recebido em 23/08 - psf- trademarks:

> Hi there!
> 
> Yes, the Grants WG is correct: If you're using the Python two-snakes or the word PyCon which are both trademarks of the PSF, you'll need to send us details on them for permissions to use.
> Can you send us the sample of the proposed logo for the conference (a draft is fine if it's not finalized) and more details on Python Brasil 2022 (like URL) so we can go through them?

## Enviado em 23/08 - psf- trademarks:

> Hi ---!
> 
> Thank you for the informations! Our logo is attached and here is the Python Brasil 2022 website: https://2022.pythonbrasil.org.br/
> 
> Best,

**Comment by wasp-lahis** [comment]
## Recebido em 23/08 - psf-trademarks:

````
Hi,

Your proposed logo does not contain elements of the trademarked 2-snakes Python logo so it is fine.
Everything looks OK!

We hope you have a successful conference.
````

**Comment by lahiss** [comment]
Oie @pythonbrasil/apyb, tá faltando só o Relatório da Python Brasil 2019 para dar prosseguimento a nossa solicitação. Poderiam dar uma olhada pfvr?

**Comment by rougeth** [comment]
@lahiss o relatório é necessário para enviar o formulário? Se não for, acho que devíamos enviar logo, enquanto o relatório não fica pronto.

**Comment by lahiss** [comment]
> @lahiss o relatório é necessário para enviar o formulário? Se não for, acho que devíamos enviar logo, enquanto o relatório não fica pronto.

Oie @rougeth, já enviamos sim (19/08).  E recebemos como resposta isso:

> Yes, we have received your new grant submission, thank you. From my previous email,
> 
>     1. Have you contacted our Trademark Committee ([psf-trademarks@python.org](mailto:psf-trademarks@python.org)) for permission to use your logos and word marks?
>     2. I don't see an event report for Python Brasil 2019. Could you or someone else with Python Brazil [submit a follow-up grant report](https://docs.google.com/forms/d/e/1FAIpQLSdtTVQLoCeCiPL_H3FWlhqbul79SxfnsqLGPrwCmL7Fvkd35g/viewform)?

**O item 1 já está ok, falta o 2.**

**Comment by wasp-lahis** [comment]
## Enviado em 30/08:

> 
> Hi ---!
> 
> Here are the Trademark Committee response:
> ​
>  > Your proposed logo does not contain elements of the trademarked 2-snakes Python logo so it is fine.
>  > Everything looks OK!
>  > We hope you have a successful conference.
> 
> In addition to the 2019 report, are there any other issues? Could you give us a status of our request, please? 
> 
> Best and Thank you!
>

**Comment by wasp-lahis** [comment]
## Recebido em 30/08:

```
Hi Lahis,

Thank you for following up. I believe the event report from 2019 is the last thing we are missing.

Lauar
```

**Comment by wasp-lahis** [comment]
## Enviado em 04/09:

````
Hi, --!

The event report from 2019 was sent to you last week. Did you received? Do you need another information of us?

Let me know you have some question.

Best and Thank you!
````

## Recebido em 07/09:

```Hi Juliany,

Yes, we did receive your report, thank you. We are reviewing your request now and will contact you again soon.

Thanks,
```

**Comment by wasp-lahis** [comment]
## Recebido em 22/09:

Hello ----,
 
I am pleased to inform you of the PSF's Board decision to support your event. Please see the resolution approved on September 21, 2022:
 
RESOLVED, that the Python Software Foundation Board grant $27,000 USD to the Python Brasil 2022 conference happening on October 17, 2022.

Reporting:
After the event, the board & grants workgroup require a follow-up report by completing the grant accountability form here: http://bit.ly/2kgf4up. If there will be pictures, please share them and we can possibly discuss doing a blog post after the event. By providing pictures of the event, you are giving the PSF permission to use them in PSF marketing and reporting. If you have any further questions on this, please do not hesitate to ask.

PSF logo and description:  
Here you can find our logo and official description for your event website and/or conference printed material: https://wiki.python.org/psf/PSF%20Press%20Kit

Events Page:
Please contact [events@python.org](mailto:events@python.org) to have your Python conference added to https://www.python.org/events/

Grant Instructions
Please send ---- an invoice for your grant. For information about what to include in your invoice and a sample invoice template, [see our Invoices page](https://www.python.org/psf/vendorpolicies/#invoices). Invoices will only be accepted from the grant submitter or a person designated by the grant submitter.

The PSF offers several payment methods for US domestic and international payments. Please review our [Payment Options page](https://www.python.org/psf/paymentoptions/), which includes specific details the PSF needs to process payments.

Contact --- with any questions. Please note that all grant offers expire six (6) months from the date of this email.
 
Thank you,
