### ISSUE TITLE
Parceria com Rede de Hotéis - Manaus Hotéis

### ISSUE THREAD

**Issue by wasp-lahis** [pythonbrasil/pybr2022-org#257]
### Descrição
Acompanhamento das tarefas relacionadas ao possível apoio da rede de hotéis [Manaus Hotéis](https://www.mhmillennium.tur.br/).

A planilha de prospecção das empresas pode ser visualizada em #82 

### Requisitos para a atividade ser concluída
- Minuta elaborada
- Contrato assinado
- Contrapartidas de apoio recebidas
- Pendências pós evento concluídas

**Comment by wasp-lahis** [comment]
[Link da proposta ](https://drive.google.com/file/d/1xA0G3SCuV2lGKTMewAuv9v-TtHDMnVBx/view?usp=sharing)enviado por eles, após reunião com a Thaty.

**Comment by wasp-lahis** [comment]
@pythonbrasil/apyb @julianyraiol @pythonbrasil/time-patrocinio Quando tiverem um tempo, poderiam revisar, por favor? Não tenho experiência com isso.. acho q ficou meio zoado > <

> [Link da Minuta](https://docs.google.com/document/d/1-QQoXKRQfLsfvRolWqg4I7M11tJsBT_V/edit?usp=sharing&ouid=104240651414053856255&rtpof=true&sd=true) que preparei para fecharmos Apoio com eles.

**Comment by wasp-lahis** [comment]
> @pythonbrasil/apyb @julianyraiol @pythonbrasil/time-patrocinio Quando tiverem um tempo, poderiam revisar, por favor? Não tenho experiência com isso.. acho q ficou meio zoado > <
> 
> > [Link da Minuta](https://docs.google.com/document/d/1-QQoXKRQfLsfvRolWqg4I7M11tJsBT_V/edit?usp=sharing&ouid=104240651414053856255&rtpof=true&sd=true) que preparei para fecharmos Apoio com eles.

@thaty-maru, quando tiver um tempo, vê se faz sentido com a conversa que você teve com eles, por favor?

**Comment by wasp-lahis** [comment]
Oie gente, consigo mandar hj mais tarde (uma 22 ou 23h) a minuta. Se acharem que tem alguma coisa p ajustar, só avisar o/

**Comment by wasp-lahis** [comment]
## Enviado em 04/08:

```
Olá ---, Bom dia!

Tudo bem?

Conseguiram avaliar o contrato? A partir do ok de vocês, mandaremos para assinatura online, via docusign. 
​
Qualquer dúvida, não hesitem em nos contatar!
Att,
```

## Recebido em 04/08:

```
Prezada Lahis, boa tarde!
 
Está sendo analisado, mas já adianto que teremos que mudar algumas cláusulas neste contrato.
 
Mas assim que o nosso administrativo definir lhe retorno.
 
Atenciosamente,
```

## Enviado em 04:08:

```
Olá ----!

Claro, sem problemas! Ficamos no aguardo. 
​
Se já tiverem um contrato modelo da Manaus Hotéis, podemos avaliar e seguir com ele!

Abs,
```

**Comment by wasp-lahis** [comment]
Oie @julianyraiol  @pythonbrasil/apyb @pythonbrasil/time-patrocinio , pessoal da Manaus Hoteis mandou a minuta revisada:

[Link da Minuta Revisada pela Manaus Hoteis](https://docs.google.com/document/d/1N9zZpFnvPWVEB4xd4eKQ1eXzSzxZoA8G/edit?usp=sharing&ouid=104240651414053856255&rtpof=true&sd=true)

**Pontos de atenção:**
> Eu tinha colocado multa de 5k para o caso deles não comprirem o acordo, mas eles retiraram isso.

**Pela demora que isso está levando e pela próximidade do evento, pensei de assinarmos assim mesmo. O que acham? Gostaria de responde-los no máximo até quarta-feira TT**

**Comment by tiidadavena** [comment]
@wasp-lahis add algumas observações bem pontuais. Sobre a multa, como entendo que é um contrato de parceria, acho interessante que a outra contrapartida na cláusula no. 6 seria a postagem da logo da empresa. Creio que com esta divulgação a empresa aceite a cláusula de multa. Outro ponto seria a disponibilização de vouchers ou cupons específicos para o evento com o intuito de registrar a contribuição da PYBR nas reservas do Hotel.

**Comment by wasp-lahis** [comment]
> @wasp-lahis add algumas observações bem pontuais. Sobre a multa, como entendo que é um contrato de parceria, acho interessante que a outra contrapartida na cláusula no. 6 seria a postagem da logo da empresa. Creio que com esta divulgação a empresa aceite a cláusula de multa. Outro ponto seria a disponibilização de vouchers ou cupons específicos para o evento com o intuito de registrar a contribuição da PYBR nas reservas do Hotel.

Tínhamos colocado a contrapartida da logo e os links de voucher no ANEXO I mesmo. Sobre as siglas, vou perguntar por email (pela demora deles em revisar a minuta), aí colocamos explicado no site. Os outros ajustes já fiz, obrigada!

**Comment by wasp-lahis** [comment]
## Enviado em 16/08:

```
Olá ----, Boa noite!

Tudo certo com a minuta de contrato! Segue em anexo a versão final em pdf.

A próxima etapa é enviarmos via Docusign para assinatura online. Para isso, precisaremos dos dados de nome e email solicitados no email anterior ^^.

Após assinatura do contrato, podemos fornecer as contrapartidas de nossa parceria ^^. Se já puderem nos passar a logo de vocês e a descrição da Manaus Hoteis que ficará em nosso site seria massa! Aqui está um exemplo de como a parceria de hotel ficou em nosso site no evento de 2019: https://2019.pythonbrasil.org.br/.

Qualquer dúvida, estamos à disposição!

Att,
```

**Comment by wasp-lahis** [comment]
## Recebido em 19/08:
```
Prezada Lahis, bom dia!
 
Informo que o contrato já foi assinado, segue em anexo Logo da Rede, conforme solicitado.
 
Segue o significado das siglas:
 
SGL – apartamento individual
DBL – apartamento duplo
TPL – apartamento triplo
ROOM TAX – seria taxas dos quartos, mas nós não cobramos nenhum tipo de taxa.
 
Para ter acesso as tarifas promocionais exclusivas da Python, pedimos que seja informado no site o nosso e-mail de reservas.
 
Hotel Adrianópolis – ***
Hotel Millennium –  ***
Hotel Saint Paul –  ***
Hotel Express Vieiralves – ****
 
O registro da contribuição será contabilizada no sistema de confirmação de reservas.
 
 
Atenciosamente,
```
