### ISSUE TITLE
Arte para credenciais do evento

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#259]
### Peça/publicidade solicitada
Arte para credenciais do evento. É preciso ter a logo do evento e a logo de patrocinadores.

Algumas ideias estão aqui nessa [pasta](https://drive.google.com/drive/u/0/folders/1iUWCEN9Cm4aVxmELJwZUaylR3V5BI3tI).

**Comment by julianyraiol** [comment]
@wasp-lahis você pode adicionar o link das logos de patrocinadores?

**Comment by wasp-lahis** [comment]
Consigo! 

** @taivalois aqui vocês podem encontrar todas as logos das empresas patrocinadoras:** 
> https://drive.google.com/drive/folders/1shbEIcyllSjhrUID1bC9YrG-OEK-6f1N?usp=sharing

**Lembrando que, para as credenciais dos participantes e organização, devem entrar a logo da TW (patrocinador ouro) e Google (patrocinador prata) somente o/**

Até agora, temos somente esses dois patrocinadores em cada uma dessas categorias. Se quiserem tb, já deixar uma arte extra com sobra de espaço, caso consigamos mais patro, seria legal tb o/

**Comment by jailsonpj** [comment]
Esse exemplo é muito bom:
![image](https://user-images.githubusercontent.com/13952136/182640730-17cc2638-5f59-4d9d-b18d-62670c151948.png)

Esse foi um exemplo que estava naquele esboço do inicio do desenvolvimento da identidade visual do evento.
