### ISSUE TITLE
[Reunião] Geral: 13 de novembro de 2021

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#26]
# Reunião Geral

- Data: 13 de novembro de 2021

- Participantes:

**Comment by lskbr** [comment]
Assuntos pra pauta:
- Plano de patrocínio
- Papeis e responsabilidades
- Horários das reuniões
- Discord
- Sistema de cadastro
- Situação da reserva centro de convenções.
- Email enviado pra uea e ifam

**Comment by JacksonOsvaldo** [comment]
@lskbr e @julianyraiol reunião é aberta à quem deseja participar da organização? Se sim, por onde será/acontecerá?
