### ISSUE TITLE
Pagamento da empresa de produção 

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#262]
Assinamos um [contrato](https://drive.google.com/drive/u/0/folders/1d9rM8hrFmpWKqCVx7iXEpSP9C6BQKeGF) com a empresa IAI Promo para apoio na organização estrutural do Centro de Convenções. 

Sendo o pagamento parcelado em 2 vezes, 50% do valor deverá ser pago até o dia 01 de setembro de 2022 e o restante até o dia 20 de outubro de 2022.

Solicito o pagamento da primeira parcela, o valor de 50%. Assim que realizamos elas emitirão a nota fiscal como comprovante. 

Obrigada!

cc: @pythonbrasil/apyb

**Comment by muriloviana** [comment]
@julianyraiol no caso o processo é o contrário rs. A gente precisa da NFe deles para realizar o pagamento. Pode até ser uma nota para a primeira parcela e outra para a segunda, ou até mesmo uma Nota Fiscal de Venda Futura.

Com a NF em mãos, basta solicitar o pagamento junto a APyB. Mais detalhes:
- https://docs.google.com/document/d/1j0UwPbZrN1E8W3zdclzyIxaFPgztjLAATSdsPAizFX0/edit#
- https://www.ultradox.com/app/apyb-solicitacao-pagamento

**Comment by julianyraiol** [comment]
Oi @muriloviana, valeu pelo comentário! Segue a NF. A data está para essa semana pois gostaria de adiantar o pagamento.

Obrigada! 

https://drive.google.com/file/d/1LCPM127eYLmREmC8W85qQsA6ZbwqQjWw/view?usp=drivesdk

**Comment by muriloviana** [comment]
@julianyraiol tu consegue submeter essa solicitação lá pelo ultradox? Segue o link: [Formulário de solicitação de pagamento junto a APyB](https://www.ultradox.com/app/apyb-solicitacao-pagamento)

Assim, vai direto pro Drive da Associação além de deixar os conselhos a par das movimentações 😉

**Comment by julianyraiol** [comment]
oi @muriloviana, submeti! obrigada :smile:
