### ISSUE TITLE
Renovar assinatura do Hootsuite

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-org#268]
### Descrição
Renovar assinatura da plataforma de gestão de midias sociais, Hootsuite.

### Requisitos para a atividade ser considerada como concluída

- Escolher entre pĺano mensal (ago-out) e anual 
- Efetivar assinatura

**Comment by cecivieira** [comment]
@wasp-lahis @julianyraiol o plano anual do Hootsuite é $588 e o mensal é $99. Acredito que não vale a pena pagar $300 por 3 meses apenas. Além disso, a organização começou a usar o plano em abril, ou seja, o tempo total de uso será de 6 meses (abr-out) sendo que os primeiros meses foi sem ônus. 


Seria interessante pagar o plano anual para que a próxima organização também se beneficie da ferramenta de gestão das redes sociais. Caso o valor do plano anual não acomode no orçamento, talvez a APyB possa considerar apoiar @anadulce @rougeth @muriloviana @tiidadavena 


![image](https://user-images.githubusercontent.com/30605862/185968992-6ee9adf1-da8f-479e-8c51-306bf5d78968.png)

**Comment by cecivieira** [comment]
Como só temos 2 redes conectadas na plataforma, fiz o downgrade para que a conta pudesse ser usada nas publicações. Mas, as funcionalidades estão limitadas.

Posso fazer a assinatura depois que for escolhida a modalidade.

@menezesgabriel

**Comment by menezesgabriel** [comment]
O facebook possui a ferramenta "Meta Business suite" onde consigo agendar posts para o facebook e instagram da PYBR, já o app de desktop do twitter me permite agenda tweets (somente 1 tweet, não sendo possível threads).

A unica ferramente que não consigo agendar é o Linkedin (ainda estou sem acesso, estamos sem postar nada por lá)

**Comment by wasp-lahis** [comment]
> @wasp-lahis @julianyraiol o plano anual do Hootsuite é $588 e o mensal é $99/mês. Acredito que não vale a pena pagar $300 por 3 meses apenas. Além disso, a organização começou a usar o plano em abril, ou seja, o tempo total de uso será de 6 meses (abr-out) sendo que os primeiros meses foi sem ônus.
> 
> Seria interessante pagar o plano anual para que a próxima organização também se beneficie da ferramenta de gestão das redes sociais. Caso o valor do plano anual não acomode no orçamento, talvez a APyB possa considerar apoiar @anadulce @rougeth @muriloviana @tiidadavena
> 
> ![image](https://user-images.githubusercontent.com/30605862/185968992-6ee9adf1-da8f-479e-8c51-306bf5d78968.png)

Faz sentido assinarmos a mensal mesmo. Sobre a organização de 2023, acredito que eles começariam a usar p valer em março talvez? No caso de assinatura anual, teriam meses não utilizados tb.


No Hootsuite, estavamos usando 4 plataformas (inta, facebook, linkedin e twitter). Seria massa se desse p/ centralizar tudo pelo Hootsuite mesmo pois facilitaria a nossa vida

**Comment by cecivieira** [comment]
O Hootsuite foi atualizado com o plano mensal. Como solicitado, mensalmente será renovado até outubro

**Comment by rougeth** [comment]
Quem está pagando pelo hootsuite?

**Comment by cecivieira** [comment]
@rougeth eu tô pagando.
Ontem fiz a assinatura mensal. Caso precise alterar para o anual, próximo dia 23 o faço.

**Comment by muriloviana** [comment]
@cecivieira já faz a [solicitação de reembolso](https://www.ultradox.com/app/apyb-solicitacao-reembolso) junto a APyB, por favor.
