### ISSUE TITLE
Comprar passagem para keynotes

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-org#277]
### Descrição
Comprar passagens para keynotes de índice 2, 3, 5 e 9 [desta tabela](https://docs.google.com/spreadsheets/d/1Dth4_m4Ti6B62aPjtTKz71VxFwMG8QB38rqCgDP3WCg/edit#gid=1300915528).

### Requisitos para a atividade ser considerada como concluída

- Enviar passagens para keynotes.

**Comment by cecivieira** [comment]
Compradas as passagens das keynotes 2, 3 e 5.

Aguardando dados da keynote 9

**Comment by julianyraiol** [comment]
@cecivieira podemos fechar essa?

**Comment by cecivieira** [comment]
Sim

Passagens compradas e inseridas nesta pasta: https://drive.google.com/drive/u/1/folders/1Tz9nGv9uL7A4hEnupf2D8G0g4B-d10_2
