### ISSUE TITLE
Reservar hospedagem para keynotes

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-org#278]
### Descrição
Reservar hospedagem para keynotes 2, 3, 5, 8 e 9 [desta tabela](https://docs.google.com/spreadsheets/d/1Dth4_m4Ti6B62aPjtTKz71VxFwMG8QB38rqCgDP3WCg/edit#gid=1300915528) entre os dias 16 e 24 de outubro.

### Requisitos para a atividade ser considerada como concluída

- Enviar reserva de hotel para keynotes.

**Comment by cecivieira** [comment]
Solicitado orçamento para Hotel Millenium

**Comment by cecivieira** [comment]
Devido a não disponibilidade do Hotel Millenium, foi solicitada reserva no hotel Adrianópolis.

Aguardando confirmação da reserva.

**Comment by cecivieira** [comment]
Valor da reserva por keynote: R$2.512

**Comment by muriloviana** [comment]
@cecivieira assim que o pagamento for realizado, o comprovante é enviado automaticamente para o email da pessoa solicitante 👍
