### ISSUE TITLE
Definir roteiro para a abertura do evento

### ISSUE THREAD

**Issue by wasp-lahis** [pythonbrasil/pybr2022-org#279]
### Descrição
Definir roteiro para a abertura do evento

### Requisitos para a atividade ser considerada como concluída

Definição de topicos e respectivos tempos de apresentação dos mesmos

**Comment by wasp-lahis** [comment]
Sugestão - 35min:

2min - Agradecimentos aos participantes pela presença
5min - Apresentar Python Brasil
5min - Falar do código de conduta
5min - Apresentar integrantes da Org (?)
5min - Apresentar estrutura dos eventos (salões, horario coffee break)
5min - Apresentar palestras relâmpago
5min - Adradecimentos a todos os canguinhas

**Comment by wasp-lahis** [comment]
Sugestão - Duração 26min

> 1min - Agradecimentos aos participantes pela presença
> 5min - Apresentar Python Brasil
> 9min - Falar do código de conduta
> 5min - Apresentar estrutura dos eventos (salões, horario coffee break)
> 5min - Apresentar palestras relâmpago
> 5min - Adradecimentos a todos os canguinhas

**Comment by julianyraiol** [comment]
- O que falar na abertura do evento?
    - Boas vindas a Python Brasil 2023 e a Manaus
    - Agradecimento patrocinadores
    - Agradecimento a todas pessoas voluntárias
    - Agradecimento a todas as pessoas palestrantes e keynotes
    - Agradecimento a apyb
    - Apresentação do evento de manaus
        - Falar que ficamos 2 anos sem pybr
        - Falar sobre Manaus
        - Importância do evento na região norte
    - Código de Conduta
        - Time de resposta
    - Palestra Relampago
    - Video patrocinador ouro
    
  #275

**Comment by cecivieira** [comment]
- O que falar na abertura do evento?
    - Boas vindas a Python Brasil 2023 e a Manaus
    - Agradecimento patrocinadores
    - Agradecimento a todas pessoas voluntárias
    - Agradecimento a todas as pessoas palestrantes e keynotes
    - Agradecimento a apyb
    - Apresentação do evento de manaus
        - Falar que ficamos 2 anos sem pybr
        - Falar sobre Manaus
        - Importância do evento na região norte
        - Programa de Auxílio Financeiro
    - Código de Conduta
        - Time de resposta
    - Palestra Relampago
    - Video patrocinador ouro

**Comment by thaty-maru** [comment]
- O que falar na abertura do evento?
    - Boas vindas a Python Brasil 2023 e a Manaus
    - Agradecimento patrocinadores
    - Agradecimento a todas pessoas voluntárias
    - Agradecimento a todas as pessoas palestrantes e keynotes
    - Agradecimento a apyb
    - Incentivar o network no Linkedin
    - Apresentação do evento de manaus
        - Falar que ficamos 2 anos sem pybr
        - Falar sobre Manaus (pedir para participantes ajustarem o relógio para 1h menos)
        - Importância do evento na região norte
        - Programa de Auxílio Financeiro (sugestão de inclusão)
    - Código de Conduta
        - Time de resposta
    - Palestra Relampago
    - Video patrocinador ouro
