### ISSUE TITLE
Mandar email vendendo ingressos no valor de 1º lote para empresas

### ISSUE THREAD

**Issue by wasp-lahis** [pythonbrasil/pybr2022-org#282]
### Descrição
Mandar email vendendo ingressos no valor de 1º lote para empresas

### Requisitos para a atividade ser considerada como concluída

Eldorado
TCE
TRT
ITRIAD
UME
UFAM
LUDUS
LINX
CESAR
PRODAM
COMMUNY
MELIUZ
CODESE
SEBRAE AM
INST. FIT
INST. CREATHUS
INST. CONECTHUS
ZEUSS
MANAOSTECH
SIDI

**Comment by wasp-lahis** [comment]
[OK] Eldorado
[OK] TCE
[OK] TRT
[OK] ITRIAD
[OK] UME
[OK] UFAM
[OK] LUDUS
[OK] LINX

**Comment by julianyraiol** [comment]
[OK] CESAR
[OK] PRODAM
[OK] COMMUNY

**Comment by wasp-lahis** [comment]
[GLOBO]
[FPF]
