### ISSUE TITLE
Arte para divulgação do local dos tutoriais 

### ISSUE THREAD

**Issue by jailsonpj** [pythonbrasil/pybr2022-org#294]
### Campanha
Divulgar o local onde será realizado os tutoriais
  
### Detalhamento
Imagem : Informações de onde será realizado os tutoriais, data e logo do local

Pode também ser um carrossel de imagens , sendo a primeira contendo informações do local onde será realizado o tutorial, data e logo do Ocean. E as outras imagens ser do espaço do Ocean

**Obs**: O OCEAN é onde será realizado os tutoriais . Na postagem do OCEAN como apoio, erramos em anunciar como Smasung OCEAN . Eles utilizam em divulgações somente o OCEAN (o samsung não existe) .

Link para fotos do OCEAN: https://drive.google.com/drive/u/1/folders/1eZ70HgWTJzZ24QbDg5v2ouNmCSN-_2l3
Link para logo e descrição do que é o OCEAN caso precise: https://drive.google.com/drive/u/1/folders/1zp-ZG1VCrKaYMuMw_FHgTLZPp33iQwka 

### Locais para divulgação
- [ ] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;

**Comment by jailsonpj** [comment]
@alynnefs Criei a Issue para divulgação do local dos Tutoriais .

**Comment by wasp-lahis** [comment]
Exemplo de como ficou em nosso site: https://2022.pythonbrasil.org.br/

**Comment by wasp-lahis** [comment]
A Escola Superior de Tecnologia - EST/UEA tbm cederá laboratórios p/ Tutoriais e sprints, mas como ainda não fechamos o contrato, acho que não eh uma boa divulgar eles nesse post de agora..

**Comment by alynnefs** [comment]
![tutoriais_maior](https://user-images.githubusercontent.com/17454743/192406213-470ace15-ef8c-42ff-98f8-5e05cf4d5bc8.png)
amanhã penso no texto e nas outras imagens pro carrossel

**Comment by alynnefs** [comment]
sem a EST/UEA, por causa do comentário da lahis

<img width="810" alt="copia 2(3)" src="https://user-images.githubusercontent.com/17454743/192646868-81a41ceb-8875-4305-839e-39e6ed9a5d9a.png">

**Comment by julianyraiol** [comment]
A gente precisa divulgar que os tutoriais serão realizados na UEA/EST também. Acho que não seria tão bom divulgar apenas o OCEAN até porque ele não comporta todas as atividades e não ficaria legal separado.

cc: @jailsonpj @wasp-lahis @alynnefs
