### ISSUE TITLE
Acompanhar venda de ingressos

### ISSUE THREAD

**Issue by wasp-lahis** [pythonbrasil/pybr2022-org#315]
### Descrição
Acompanhar venda de ingressos.

### Requisitos para a atividade ser considerada como concluída

- Até completarmos a venda de 600 ingressos

**Comment by wasp-lahis** [comment]
## 04/10:

> 372 - INSCRITOS NO EVENTBRITE 04/10 (NOITE)
>         - 15/16 ORG (Ju, Thaty, Jailson, Lahis, Gabriel, Renan, Murilo, Marco, Alynne, Ceci, Tainah, Klayton, Ana Dulce, Felipe, Ricardo)
>         - 2/8 (Letícia, Elloá, Lidi)
>         - 3/65 (Bemol)
>         - 2/5 (Google)
>         - 3/3 (Globo)
>         - 5 (Jusbrasil)
>         - 5/5 (Labcodes)
>         - 5/5 (Vinta)
>         - 0/0 Luizalabs
>         - 0/0 Stream
> 
> 5  - INGRESSOS DE KEYNOTES NÃO RETIRADOS
> 1 - INGRESSOS DA ORG NÃO RETIRADOS (Mariana)
> 
> 62 - BEMOL (foram enviados para retirada)
> 23 - ELDORADO (confirmação até 05/10)
>         - Pior caso: 45 pessoas (considerando meia 110,00)
> 4  - INGRESSOS DA SAKS (não foi comprado ainda - email enviado)
> 5  - INGRESSOS DO INDT (não foi comprado ainda - email enviado)
> 3  - INGRESSOS DA TWILIO (não foi retirado)
> 3  - INGRESSOS DO GOOGLE (não foi retirado)
> 10  - INGRESSOS DA TW (não foi retirado)
> 6  - INGRESSOS DA BOTCITY (não foi retirado)
> 3  - INGRESSOS DA SBF (não foi retirado)
> 11 - Palestrantes que não retiraram ingresso
> 
> 
> TOTAL ESTIMADO: 508 / 500

**Comment by wasp-lahis** [comment]
## 08/10 (manhã):

- 441 - INSCRITOS NO EVENTBRITE, incluindo:
    - 15/16 ORG (Ju, Thaty, Jailson, Lahis, Gabriel, Renan, Murilo, Marco, Alynne, Ceci, Tainah, Klayton, Ana Dulce, Felipe, Ricardo)
    - 4/8 (Letícia, Elloá, Lidi, Mariatta)
    - 3/3 Globo
    - 5/5 Jusbrasil (extra)
    - 5/5 Labcodes
    - 5/5 Vinta
    - 8/8 INDT (Selma)
    - 6/6 Botcity
    - 0/0 Luizalabs
    - 0/0 Stream
    - 0/3 Jusbrasil (uso livre)
    - 2/5 Google
    - 33/65 Bemol
    - 7/33 ELDORADO
    - 0/5 INDT (estande)
    - 0/4 SAKS    

- Ingressos que ainda Não foram retirados:
    - 01  - ORG NÃO RETIRADOS (Mariana)
    - 04  - KEYNOTES NÃO RETIRADOS
    - 03  - JUSBRASIL 
    - 26  - ELDORADO (foram enviados para retirada)
    - 32  - BEMOL (foram enviados para retirada)
    - 04  - SAKS (não foi comprado ainda - email enviado)
    - 05  - INDT (não foi comprado ainda - email enviado)
    - 03  - TWILIO (não foi retirado)
    - 03  - GOOGLE (não foi retirado)
    - 10  - TW (não foi retirado)
    - 03  - INGRESSOS SBF (não foi retirado)
    - 03  - INGRESSOS JUSBRASIL (USOLIVRE)
    - 09  - Palestrantes que não retiraram ingresso


- Ingressos em negociação:

    - 10 Eldorado
    - 4 Prodam
    - 2 Sidia
    - 20 FPF

TOTAL ESTIMADO: não tive mais tempo de calcular, mas eh só somar / 600

**Comment by wasp-lahis** [comment]
## 09/10:

- 441 - INSCRITOS NO EVENTBRITE, incluindo:
    - 15/16 ORG (Ju, Thaty, Jailson, Lahis, Gabriel, Renan, Murilo, Marco, Alynne, Ceci, Tainah, Klayton, Ana Dulce, Felipe, Ricardo)
    - 4/8 (Letícia, Elloá, Lidi, Mariatta)
    - 3/3 Globo
    - 5/5 Jusbrasil (extra)
    - 5/5 Labcodes
    - 5/5 Vinta
    - 8/8 INDT (Selma)
    - 6/6 Botcity
    - 0/0 Luizalabs
    - 0/0 Stream
    - 2/2 OKB
    - 0/3 Jusbrasil (uso livre)
    - 2/5 Google
    - 33/65 Bemol
    - 7/33 ELDORADO
    - 0/5 INDT (estande)
    - 0/4 SAKS    

- 106 - Ingressos que ainda Não foram retirados:
    - 01  - ORG NÃO RETIRADOS (Mariana)
    - 04  - KEYNOTES NÃO RETIRADOS
    - 03  - JUSBRASIL 
    - 26  - ELDORADO 
    - 32  - BEMOL 
    - 04  - SAKS (não foi comprado ainda - email enviado)
    - 05  - INDT (não foi comprado ainda - email enviado)
    - 03  - TWILIO 
    - 03  - GOOGLE 
    - 10  - TW 
    - 03  - INGRESSOS SBF 
    - 03  - INGRESSOS JUSBRASIL (USOLIVRE)
    - 09  - Palestrantes que não retiraram ingresso

**TOTAL ESTIMADO: 547 / 600**


- 8/50 Ingressos em negociação :
    - 10 Eldorado
    - 4 Prodam
    - 2 Sidia
    - 20 FPF
    - [OK] 8 INDT (Incluso na contagem acima)

**Comment by muriloviana** [comment]
@wasp-lahis temos mais 4 ingressos para Prodam (https://pythonbrasil.freshdesk.com/a/tickets/9177) e 5 para Salks (https://pythonbrasil.freshdesk.com/a/tickets/9197)

**Comment by wasp-lahis** [comment]
## 10/10 (noite):

- 475 - INSCRITOS NO EVENTBRITE, incluindo:
    - 15/16 ORG (Ju, Thaty, Jailson, Lahis, Gabriel, Renan, Murilo, Marco, Alynne, Ceci, Tainah, Klayton, Ana Dulce, Felipe, Ricardo)
    - 5/8 (Letícia, Elloá, Lidi, Mariatta, Eduardo)
    - 3/3 Globo
    - 5/5 Jusbrasil (extra)
    - 5/5 Labcodes
    - 5/5 Vinta
    - 8/8 INDT (Selma)
    - 6/6 Botcity
    - 2/2 OKB
    - 0/3 Jusbrasil (uso livre)
    - 2/5 Google
    - 44/65 Bemol
    - 27/33 ELDORADO
    - 0/5 INDT rotativo (estande)
    - 1/3 Twilio
    - 0/5 SAKS rotativo (estande)
    - 2/6 - Participante NFe
    - 2/6 - Palestrantes
    - 3/3 - NFe Josenildo

- 84 - Ingressos que ainda Não foram retirados:
    - 01  - ORG (Mariana)
    - 03  - KEYNOTES (Eulanda, Valcleia e Guilherme)
    - 06  - ELDORADO 
    - 21  - BEMOL 
    - 05  - SAKS (aguardando pagamento)
    - 05  - INDT (aguardando pagamento)
    - 02  - TWILIO 
    - 03  - GOOGLE 
    - 10  - TW 
    - 03  - INGRESSOS SBF 
    - 03  - INGRESSOS JUSBRASIL (USOLIVRE)
    - 04  - Palestrantes que não retiraram ingresso
    - 04  - Participante NFe
    - 04 - Prodam (aguardando pagamento)
    - 09 - Ingresso Geral inteira
    - 01 - Ingresso Geral meia

**TOTAL ESTIMADO: 559 / 600**

> - 12/48 - Ingressos em negociação dos 50 alocados para as empresas:
>     - 10 Eldorado (Lahis)
>     - 06 Sidia (Murilo)
>     - 20 FPF (Lahis)
>    -  [aguardando pagamento] 4 Prodam (contabilizado nos reservados)
>     - [OK] 8 INDT ((contabilizado nos retirados))

**Comment by wasp-lahis** [comment]
> @wasp-lahis temos mais 4 ingressos para Prodam (https://pythonbrasil.freshdesk.com/a/tickets/9177) e 5 para Salks (https://pythonbrasil.freshdesk.com/a/tickets/9197). Todos aguardando pagamento das empresas.

Oie @muriloviana, são 8 ingressos da Prodam então ao todo? sobre o SIDIA, fiquei na dúvida se são 4 ou 6 ingressos

**Comment by muriloviana** [comment]
> > @wasp-lahis temos mais 4 ingressos para Prodam (https://pythonbrasil.freshdesk.com/a/tickets/9177) e 5 para Salks (https://pythonbrasil.freshdesk.com/a/tickets/9197). Todos aguardando pagamento das empresas.
> 
> Oie @muriloviana, sobre o SIDIA, fiquei na dúvida se são 4 ou 6 ingressos

Perdão, não tinha visto que os quatro ingressos da Prodam já estavam contabilizados. São apenas quatro mesmo.
Quanto a SIDIA, tá uma novelinha rs. Mas se atendo aos fatos, eles desejam 6 ingressos.

**Comment by wasp-lahis** [comment]
## 11/10 (noite):

- **510 - INSCRITOS NO EVENTBRITE**, incluindo:
    - 15/16 ORG (Ju, Thaty, Jailson, Lahis, Gabriel, Renan, Murilo, Marco, Alynne, Ceci, Tainah, Klayton, Ana Dulce, Felipe, Ricardo)
    - 6/8 (Letícia, Elloá, Lidi, Mariatta, Eduardo, Valcleia)
    - 3/3 Globo
    - 5/5 Jusbrasil (extra)
    - 5/5 Labcodes
    - 5/5 Vinta
    - 9/9 INDT (Selma)
    - 6/6 Botcity
    - 2/2 OKB
    - 0/3 Jusbrasil (uso livre)
    - 2/5 Google
    - 08/10 TW
    - 51/65 Bemol
    - 27/33 ELDORADO
    - 0/5 INDT rotativo (estande)
    - 1/3 Twilio
    - 0/5 SAKS rotativo (estande)
    - 5/6 - Participante NFe
    - 4/5 - Palestrantes
    - 3/3 - NFe Josenildo
    - 3/3 - SBF
    - 4/4 - Prodam
    - 1/1 - Stream

- 50 - Ingressos que ainda Não foram retirados:
    - 01  - ORG (Mariana)
    - 02  - KEYNOTES (Eulanda e Guilherme)
    - 06  - ELDORADO 
    - 14  - BEMOL  
    - 05  - SAKS (aguardando pagamento)
    - 05  - INDT (aguardando pagamento)
    - 02  - TWILIO 
    - 03  - GOOGLE 
    - 02  - TW 
    - 03  - JUSBRASIL 
    - 01  - Participante NFe
    - 03  - Sidia
    - 01  - Palestrantes que não retiraram ingresso
    - 03  - Ingresso Geral inteira 
    - 00  - Ingresso Geral meia


**TOTAL ESTIMADO: 560 / 600**

> - Ingressos em negociação:   
>     - 20 FPF (Lahis)

**Comment by wasp-lahis** [comment]
## 14/10 (manhã):

- **525 - INSCRITOS NO EVENTBRITE**, incluindo:
    - 15/16 ORG (Ju, Thaty, Jailson, Lahis, Gabriel, Renan, Murilo, Marco, Alynne, Ceci, Tainah, Klayton, Ana Dulce, Felipe, Ricardo)
    - 6/8 (Letícia, Elloá, Lidi, Mariatta, Eduardo, Valcleia)
    - 3/3 Globo
    - 5/5 Jusbrasil (extra)
    - 5/5 Labcodes
    - 5/5 Vinta
    - 9/9 INDT (Selma)
    - 6/6 Botcity
    - 2/2 OKB
    - 0/3 Jusbrasil (uso livre)
    - 2/5 Google
    - 08/10 TW
    - 59/65 Bemol
    - 27/33 ELDORADO
    - 0/5 INDT rotativo (estande)
    - 1/3 Twilio
    - 0/5 SAKS rotativo (estande)
    - 5/6 - Participante NFe
    - 4/5 - Palestrantes
    - 3/3 - NFe Josenildo
    - 3/3 - SBF
    - 4/4 - Prodam
    - 1/1 - Stream

- 74 - Ingressos que ainda Não foram retirados:
    - 01  - ORG (Mariana)
    - 02  - KEYNOTES (Eulanda e Guilherme)
    - 06  - ELDORADO 
    - 06  - BEMOL  
    - 05  - SAKS (aguardando pagamento)
    - 05  - INDT (aguardando pagamento)
    - 02  - TWILIO 
    - 03  - GOOGLE 
    - 02  - TW 
    - 03  - JUSBRASIL
    - 01  - Participante NFe
    - 03  - Sidia
    - 01  - Palestrantes que não retiraram ingresso
    - 20  - FPF (negociação)
    - 09  - Ingresso Geral inteira 
    - 05  - Ingresso Geral meia 

**TOTAL ESTIMADO: 599 / 600**

**Comment by wasp-lahis** [comment]
## 15/10 (noite):

- **554 - INSCRITOS NO EVENTBRITE**, incluindo:
    - 15/16 - ORG 
    - 06/08 - Keynotes
    - 03/03 - Globo
    - 05/05 - Jusbrasil (extra)
    - 05/05 - Labcodes
    - 05/05 - Vinta
    - 09/09 - INDT (Selma)
    - 06/06 - Botcity
    - 02/02 - OKB
    - 03/03 - Jusbrasil (uso livre)
    - 03/03 - NFe Josenildo
    - 03/03 - SBF
    - 04/04 - Prodam
    - 01/01 - Stream
    - 02/05 - Google
    - 08/10 - TW
    - 62/65 - Bemol
    - 32/33 - ELDORADO
    - 08/20 - FPF
    - 01/03 - Twilio
    - 00/05 INDT rotativo (estande)
    - 00/05 SAKS rotativo (estande)
    - 05/06 - Participante NFe
    - 04/05 - Palestrantes

- 47 - Ingressos que ainda Não foram retirados:
    - 01  - ORG (Mariana)
    - 02  - KEYNOTES (Eulanda e Guilherme)
    - 01  - ELDORADO 
    - 03  - BEMOL  
    - 05  - SAKS (aguardando pagamento)
    - 05  - INDT (aguardando pagamento)
    - 12  - FPF  (aguardando pagamento)
    - 02  - TWILIO 
    - 03  - GOOGLE 
    - 02  - TW 
    - 01  - Participante NFe
    - 03  - Sidia 
    - 01  - Palestrantes que não retiraram ingresso
    - 04 - Ingresso Geral (lote 2) - 158/162
    - 02 - Ingresso Meia-Entrada (lote 2) 101/103 


**TOTAL ESTIMADO: 601 / 600**

**Comment by wasp-lahis** [comment]
## 17/10 (noite):

- **569 - INSCRITOS NO EVENTBRITE**, incluindo:
    - 03/03 - Globo
    - 05/05 - Jusbrasil (extra)
    - 05/05 - Labcodes
    - 05/05 - Vinta
    - 09/09 - INDT (Selma)
    - 06/06 - Botcity
    - 02/02 - OKB
    - 03/03 - Jusbrasil (uso livre)
    - 03/03 - NFe Josenildo
    - 03/03 - SBF
    - 04/04 - Prodam
    - 01/01 - Stream
    - 06/06 - Ingresso Geral (lote 2) - 160/160
    - 06/06 - Ingresso Meia-Entrada (lote 2) 103/103
    - 06/08 - Keynotes
    - 62/65 - Bemol
    - 01/03 - Twilio
    - 02/05 - Google
    - 08/10 - TW
    - 05/05 - Palestrantes
    - 15/16 - ORG 
    - 32/33 - ELDORADO
    - 16/20 - FPF
    - 00/05 SAKS rotativo (estande)
    - 00/05 INDT rotativo (estande)
    - 05/06 - Participante NFe
    
- 30 - Ingressos que ainda Não foram retirados:
    - 01  - ORG (Mariana)
    - 02  - KEYNOTES (Eulanda e Guilherme)
    - 01  - ELDORADO 
    - 02  - BEMOL  
    - 05  - SAKS (aguardando pagamento)
    - 05  - INDT (aguardando pagamento)
    - 04  - FPF  (aguardando pagamento)
    - 02  - TWILIO 
    - 03  - GOOGLE 
    - 02  - TW 
    - 01  - Participante NFe
    - 02  - Sidia 


**TOTAL ESTIMADO: 599 / 600**
