### ISSUE TITLE
Revisar e Corrigir datas no formulário de inscrição do Eventbrite (LGPD)

### ISSUE THREAD

**Issue by luzfcb** [pythonbrasil/pybr2022-org#317]
### Descrição

Algumas partes dos textos incluídos no formulário de inscrição no Eventbrite fazem referencia a edição e anos anteriores e não de 2022 e isso precisa ser corrigido para os dados de 2022

![image](https://user-images.githubusercontent.com/807599/195642392-f14a914b-c83a-4a87-80da-12752d9d0629.png)

**Comment by luzfcb** [comment]
Ping @rougeth @felipecolen, penso que isso deve ser resolvido rapidamente desde que tem implicações legais em relação a LGPD, afinal, o formulário de inscrição é um tipo de contrato.

**Comment by rougeth** [comment]
Vou corrigir amanhã e aviso aqui quando atualizar.

**Comment by rougeth** [comment]
Corrigido @luzfcb! Value pelo aviso.
