### ISSUE TITLE
Extrair e subir dados para repositório de dados

### ISSUE THREAD

**Issue by gabubellon** [pythonbrasil/pybr2022-org#328]
* YouTube	Total de visualizações no canal por dia (considera todos vídeos no canal)	
* YouTube	Total de visualizações nos vídeos por dia (apenas vídeos da pybr2022)	
* Discord	Total de participantes por dia	
* Discord	Participantes por plataforma	
* Discord	Participantes por país	
* Discord	Participantes que interagiram no servidor	
* Discord	Participantes ativas (visitaram pelo menos 3 canais de texto)	
* Discord	Participantes que mutaram servidor	
* Discord	Pessoas novas no Discord	
* Discord	Atividade por texto	
* Discord	Atividade por voz	
* Discord	Canais de texto mais populares	
* Discord	Canais de voz mais populares		
* Inscrições	Questionário das incrições realizadas via EventBrite	
* Ministrantes de atividades	Dados sócio econômicos das ministrantes de palestras e tutoriais

**Comment by gabubellon** [comment]
https://github.com/pythonbrasil/dados/pull/11

**Comment by cecivieira** [comment]
- [ ] YouTube	Total de visualizações no canal por dia (considera todos vídeos no canal)	
- [ ] YouTube	Total de visualizações nos vídeos por dia (apenas vídeos da pybr2022)	
- [x] Discord	Total de participantes por dia	
- [x] Discord	Participantes por plataforma	
- [x] Discord	Participantes por país	
- [x] Discord	Participantes que interagiram no servidor	
- [x] Discord	Participantes ativas (visitaram pelo menos 3 canais de texto)	
- [x] Discord	Participantes que mutaram servidor	
- [x] Discord     Participantes que saíram do servidor
- [x] Discord	Pessoas novas no Discord	
- [x] Discord	Atividade por texto	
- [x] Discord	Atividade por voz	
- [x] Discord	Canais de texto mais populares	
- [x] Discord	Canais de voz mais populares		
- [x] Inscrições	Questionário das incrições realizadas via EventBrite	
- [ ] Ministrantes de atividades	Dados sócio econômicos das ministrantes de palestras e tutoriais

**Comment by cecivieira** [comment]
@renan-assis-santos tu poderia colocar o link aqui dos dados do Pretalx? Vou dá uma olhada neles para abrir o perfil socio cultural das ministrantes

**Comment by cecivieira** [comment]
- [x] YouTube	Total de visualizações no canal por dia (considera todos vídeos no canal)	
- [x] YouTube	Total de visualizações nos vídeos por dia (apenas vídeos da pybr2022)	
- [x] Discord	Total de participantes por dia	
- [x] Discord	Participantes por plataforma	
- [x] Discord	Participantes por país	
- [x] Discord	Participantes que interagiram no servidor	
- [x] Discord	Participantes ativas (visitaram pelo menos 3 canais de texto)	
- [x] Discord	Participantes que mutaram servidor	
- [x] Discord     Participantes que saíram do servidor
- [x] Discord	Pessoas novas no Discord	
- [x] Discord	Atividade por texto	
- [x] Discord	Atividade por voz	
- [x] Discord	Canais de texto mais populares	
- [x] Discord	Canais de voz mais populares		
- [x] Inscrições	Questionário das incrições realizadas via EventBrite	
- [x] Ministrantes de atividades	Dados sócio econômicos das ministrantes de palestras e tutoriais
