### ISSUE TITLE
Desativar servidor do Discord dos participantes

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-org#332]
### Descrição
Desativar modo escrita do Discord e links de convite disponível (ex. o disponível nos vídeos do Youtube (https://discord.gg/NfE7VDGbJn))

### Requisitos para a atividade ser considerada como concluída

- Fechar Discord para novas pessoas
- Converter servidor apenas para modo leitura

**Comment by rougeth** [comment]
Discord em modo leitura e anuncio enviado.
