### ISSUE TITLE
Coleta de dados sobre covid-19

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-org#334]
### Descrição
Publicar pesquisa solicitando às participantes dados sobre infecção por covid-19 entre os dias 20 e 31 de outubro.

### Requisitos para a atividade ser considerada como concluída

- Criação de formulário
- Criação de arte para post
- Postagem

**Comment by cecivieira** [comment]
Formulário: https://docs.google.com/forms/d/e/1FAIpQLSc0r9TY1iZuRjlZszKkpXsQ_7yAE6ypUyXe66_7q6ch2FpZhA/viewform

**Comment by cecivieira** [comment]
[Sugestão de legenda] 
Queremos saber o total de participantes que testaram positivo para COVID-19 entre os dias 20 e 31 de outubro. Se você esteve presencialmente no evento, por favor, responde a essa pesquisa de 1 pergunta, ainda que tenha testado negativo.

Esses dados nos ajudarão no planejamento dos próximos evenots presenciais.

![image](https://user-images.githubusercontent.com/30605862/199301647-14a5f393-d243-4424-b742-9d5352588262.png)

**Comment by tiidadavena** [comment]
Texto excelente, Ceci! 

Só acho que a parte inicial, que é o objetivo, deveria vir antes do parágrafo maior e deixar explícito que a coleta vai seguir a LGPD

**Comment by cecivieira** [comment]
[Legenda ajustada conforme sugestões de @tiidadavena e @wasp-lahis ]
Durante a Python Brasil 2022, na região sede do evento houve aumento de casos de COVID-19 desencadiando o anúncio da fase amarela

Queremos saber o total de participantes que testaram positivo para COVID-19 entre os dias 20 e 31 de outubro. Se você esteve presencialmente no evento, por favor, responde a essa pesquisa anônima com apenas 1 pergunta, ainda que tenha testado negativo ou não realizado o teste.

Esses dados nos ajudarão no planejamento dos próximos evenots presenciais.

**Comment by cecivieira** [comment]
Post realizado
