### ISSUE TITLE
[Reunião] Geral: 20 de dezembro de 2021

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#34]
# Reunião Geral

- Data: a definir
- Participantes:
  - Giulio Carvalho  (@giuliocc)
  - Juliany Raiol (@julianyraiol)
  - Jailson Januário (@jailsonpj)
  - Paulo Sérgio (@PSFreitas) 
  - Marcos Wenneton

## Acompanhamento das tarefas

- [ ] Verificar [tarefas bloqueadas](https://github.com/pythonbrasil/pybr2022-org/projects/1?card_filter_query=label%3Abloqueado):
  - Está claro o que precisa ser feito para desbloquear a tarefa?
  - Há parte da tarefa que pode prosseguir de alguma forma?
- [ ] Verificar [tarefas em andamento](https://github.com/pythonbrasil/pybr2022-org/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-asc+-label%3ABloqueado+-label%3AP%C3%B3s-evento+project%3Apythonbrasil%2Fpybr2021-org%2F1) e ordenando pela últimas que foram atualizadas.
  - A tarefa está associada a uma pessoa responsável?
  - Há algo bloqueando o avanço da tarefa que possa ser discutido?
- [ ] Verificar [tarefas abertas](https://github.com/pythonbrasil/pybr2021-org/issues?q=is%3Aopen+is%3Aissue+-project%3Apythonbrasil%2Fpybr2021-org%2F1+) não associadas ao projeto no Github.

## Ata

- Apresentar plano de patrocínio
- Priorização de atividades
- Definir período de alerta por conta da variante Omicron

- Definir data da próxima reunião
    
### Ações para serem realizadas

- Organização do dia do evento
    - 15 e 16: organização da infraestrutura do evento
    - 17 a 23: o evento em si
    - 24: remoção da infraestrutura
    
- Jailson vai ficar responsável por se o contato com o Centro de Convenções. Ele irá verificar como podemos fazer para remover a infraestrutura, visto que o centro está reservado apenas até o dia 23. 
- Juliany vai falar com a Alice para confirmar data do PyLadiesConf afim de não haver conflito com o evento
- Criação de 3 planos de patrocínio: internacional, nacional e regional.
    - O internacional: versão em inglês para chamar empresas de fora;
    - O nacional: empresas do Brasil;
    - O regional: empresas do Polo Digital;
    - Data para finalizar plano de patrocinio: 15.01.22;
    - Início de Fevereiro para iniciar o contato com as empresas;
    - Marcos Wenneton irá contribuir na parte financeira;
- Definir plano de ação para alerta sobre a variante Ômicron (marcar uma reunião para isso?);
    - Data de alerta: até 31.01.2022
- Listar contatos de empresas para solicitar patrocínio;
- Verificar a compra da licença de software para call4papers
    - Sugestão: https://pretalx.com/p/pricing
    - Fazer um benchmark dos existentes
- Paulo Sérgio irá apresentar uma proposta de logo
- Definir cargos dentro da organização
    - Designer
    - Financeiro
    - Comunicação
    - Tecnologia
- Adotar o canal do discord para reuniões e grupos de trabalho.

**Comment by JacksonOsvaldo** [comment]
@julianyraiol, a reunião é aberta à quem deseja participar da organização? Se sim, por onde será/acontecerá?
