### ISSUE TITLE
Finalizar tópicos do plano de patrocínio

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#35]
O @giuliocc e eu criamos a base do [plano de patrocínio](https://docs.google.com/presentation/d/1QWQeC4z19Ku0r58elHt1sBnVL71SvabMg7RJwS1IR6M/edit#slide=id.p1) mas precisamos de ajuda para finalizarmos esse documento. Estamos nos baseando nos [eventos anteriores](https://drive.google.com/drive/u/0/folders/1f9rUmmfSwFoAO_XJeMGP81fTCxmlmIrz).

Os tópicos que estão pendentes são:

- O evento
- A comunidade
- A cidade
- Como será esta edição?
- Número de participantes
- Porque patrocinar
- Quem patrocinou
- Qual o plano de ação para a covid 19?

Começamos a trabalhar nessa [issue](https://github.com/pythonbrasil/pybr2022-org/issues/1)

**Comment by julianyraiol** [comment]
[patrocinio_python_brasil.pdf](https://github.com/pythonbrasil/pybr2022-org/files/7937779/patrocinio_python_brasil.pdf)

versão 0.0.1 do plano.

disponível em: 

https://www.canva.com/design/DAE2US3tpM0/le0tf0xjwqzKGCNVtdABSQ/edit
https://docs.google.com/presentation/d/1QWQeC4z19Ku0r58elHt1sBnVL71SvabMg7RJwS1IR6M/edit#slide=id.gcffaff9658_0_41

**Comment by julianyraiol** [comment]
o @jailsonpj vai adicionar os tópicos 

- A cidade
- A Python Brasil será em Manaus!

**Comment by julianyraiol** [comment]
versão 0.0.2 do plano

[patrocinio_python_brasil (1).pdf](https://github.com/pythonbrasil/pybr2022-org/files/7945881/patrocinio_python_brasil.1.pdf)

**Comment by julianyraiol** [comment]
- Apresentação do plano de patrocínio (@julianyraiol, @giuliocc, @allanacardoso, @Kadidjah)
    - Comprovante de vacinação
    - Máscaras e alcóol em gel no kit do participante
    - Adicionar o recrutamento para primeiro tópico (reforçar essa contrapartida)
    - Verificar a versão online no plano de patrocínio
    - Não enviar o email dos participantes para empresas (abrir espaço para que a organização do evento envie emails vindos das empresas?)  
    - Considerar slots de horários para o job fair (melhor divulgação das empresas)
    - Estandes para platina e diamante
    - Plantina e Diamante são muito parecidos
    - Pouco alcance nas redes sociais (divulgação de marca x recrutamento)
    
Comentários que surgiram após a [reunião](https://github.com/pythonbrasil/pybr2022-org/issues/43) do dia 26.01

**Comment by julianyraiol** [comment]
Link para o canva: https://www.canva.com/design/DAE2US3tpM0/le0tf0xjwqzKGCNVtdABSQ/edit

**Comment by cecivieira** [comment]
Ajustes a serem feitos:

1 - Desmembrar os dados referentes ao evento online e presencial, presente no slide 14.
2 - Nas cotas de patrocínio, explicitar o que significam "bolsas". Talvez só trocar o termo ou colocar um * no pé da página
3 - Revisar plano de patrocínio da [PyBr21](https://github.com/pythonbrasil/pybr2021-site/blob/main/public/plano-patrocinio-pybr2021.pdf) e verificar se há algum benefício do evento online que pode ser incluído no Plano de Patrocínio atual

**Comment by cecivieira** [comment]
@giuliocc compartilha aqui a tabela base para essas visualizações do flourish, por favor.

**Comment by cecivieira** [comment]
Tabela fonte com dados de cotas de patrocinadora:

https://docs.google.com/spreadsheets/d/1eQyoEUX16MBLoV9Kxgj2zNzpfHeuTv_-QIGprQjSPYg/edit#gid=466765179

**Comment by giuliocc** [comment]
Para quem não pôde participar da discussão mais a fundo no plano de patrocínio ontem após a reunião geral, quais foram as decisões tomadas? Acho que vale adicionar na ata também

**Comment by cecivieira** [comment]
@giuliocc as decisões a grsso modo foram:

- Redução da quantidade de tipo de cota para 4 (diamante, platina, ouro, prata), 
- O Apoio será descrito fora da planilha de cotas.
- Revisão dos benefícios de todas as cotas para haver maior diferenciação entre elas.

Os dados atualizados estão no documento do comentário anterior. Tu poderia atualizar a visualização no Flourish?

**Comment by giuliocc** [comment]
Beleza, valeu! Entendi melhor. A segunda página da planilha tava me confundindo.

Atualizei a visualização e em breve vejo com mais calma as mudanças.

**Comment by rougeth** [comment]
Trazendo alguns tópicos vindos da issue #75:
- Vídeo publicitário antes de depois de keynote: Normalmente tem 1m30s de duração
  -  Meu comentário foi: *Acho que é muito, considerando que será o mesmo vídeo todos os dias. Tivemos reclamações em 2019 por conta dos vídeos.*
  - Penso que 30 segundos está de bom tamanho (sugestão do Giulio 👍)
- Valor mínimo para apoios:
  - Meu comentário foi: *Geralmente os apoios são definidos caso a caso, já que não envolvem, necessariamente, valores em dinheiro. Não sei conseguiremos criar uma regra específica.*
  - Acho que a parte de apoios não precisa ir para o plano de patrocínio.

**Comment by rougeth** [comment]
Dados da Python Brasil 2021: https://github.com/pythonbrasil/dados/tree/main/dados/python-brasil-2021

#### Views no YouTube:
| Date | Views |
|-|-|
| 2021-10-11 | 16707 |
| 2021-10-12 | 7819 |
| 2021-10-13 | 6389 |
| 2021-10-14 | 5120 |
| 2021-10-15 | 4389 |

#### Dados do Discord
- +49k mensagens de texto
- 816 horas conversas
- 153 participantes fora do Brasil

**Comment by giuliocc** [comment]
[Plano de patrocínio](https://www.canva.com/design/DAE2US3tpM0/le0tf0xjwqzKGCNVtdABSQ/edit) atualizado.

Mapeei alguns pontos ainda precisam ser fechados, mas podem ter mais:

1. Quantidade de slots para Job Fair
    1. Online
    2. Presencial
2. Número de cards em redes sociais
3. Número e duração de vídeos em redes sociais
4. Quantidade de vagas e números de posts de divulgação de vagas para a cota Platina

**Comment by giuliocc** [comment]
Seguindo a sugestão do @rougeth alterei a maneira que a tabela comparativa é apresentada (inclusive eliminando a necessidade de slides anteriores à tabela). Também coloquei alguns números nos pontos que precisamos fechar que mencionei acima, vejam se estão de acordo.

Alterei um pouco o conteúdo de alguns slides e adicionei mais um slide  "como será essa edição" para adicionar que faremos o evento híbrido.

O [plano de patrocínio "finalizado" está no drive](https://drive.google.com/file/d/1a_gUc7de05n04TS_2-m-1HcIlYu-V2PE/view?usp=sharing).

**Comment by wasp-lahis** [comment]
Muito Obrigada @giuliocc !

Aqui vão algumas sugestões:

### Slide 4, A Cidade: 
- Substituir "(...)metropolitana e por ser a capital turística da Amazônia, devido a sua localização no meio da floresta, mas com todos os serviços e o conforto de uma grande cidade." por  **"(...)metropolitana e por ser a capital turística do Amazonas, devido a sua localização no meio da floresta, mas com todos os serviços e o conforto de uma grande cidade."**

Outros estados do Norte, estão no ecossistema da Amazônia tb, como o Pará por exemplo. Além dos outros países da America Latina.. Acho q essa parte me incomodou haha. Enfim, dxo essa sugestão :)

### Slide 6, Cuidados:
- Seria bacana mostrar uma foto do local. Acho q se fosse possível patrocinadora, gostaria de ver essa info o/

**Comment by giuliocc** [comment]
Atualizei com suas observações @wasp-lahis . Muito bom!

Quanto ao slide dos "cuidados", achei que faria sentido até mudar o nome pra "local do evento e cuidados" e alterei.

**Comment by cecivieira** [comment]
@giuliocc @wasp-lahis já foi fechado o contrato para o local do evento?

Na capa, não seria interessante ter pessoas da comunidade Python de Manaus? Se não tiver foto delas em PyBr, poderia ser em eventos regionais ou locais. De forma geral eu senti muita falta de pessoas com fenótipos característicos da região Norte. Nem foto de Ju (big kahuna) tem.

**Comment by cecivieira** [comment]
Posso colaborar nessa curadoria de fotos. Coloca o link da pasta aqui.

**Comment by giuliocc** [comment]
@cecivieira o contrato não foi fechado mas tínhamos a reserva do local e planejamos o evento acontecendo nele. Acha que seria problemático? Caso precisemos mudar de local penso que muito provavelmente vamos precisar alterar o plano de qualquer forma (número de pessoas, estandes, espaço para crianças, etc.) e seria justificado.

Mas se achar que é melhor tirar o local do plano posso alterar o slide de "local do evento e cuidados" tranquilo.

Ah, as fotos a @julianyraiol foi pegando do Flickr da Python Brasil se não me engano e foi colocando direto no Canva. Não tem pasta no drive. Pode dar acesso ao canva pra @cecivieira , @julianyraiol ?

**Comment by cecivieira** [comment]
@pythonbrasil/apyb poderia me dar acesso as (imagino) várias pastas com fotos que tem de eventos?

@julianyraiol será que rola pedir nos grupy/Pug e pydata de Manaus fotos de eventos presenciais?

**Comment by rougeth** [comment]
@cecivieira https://flickr.com/photos/pythonbrasil/albums

**Comment by cecivieira** [comment]
@giuliocc se existe reserva, acho que deve ser mantido. No entanto, se não houver nada, ou seja, só uma conversa inicial e o desejo por parte da organização, acho que deve ser retirado.

Acho que a perspectiva de público pode ser mantida, pois é o planejamento do evento  que a organização está trabalhando para viabilização.

Maaasss ... Isso é um pitaco a organização que deve decidir @julianyraiol

**Comment by wasp-lahis** [comment]
Complementando os slides de plano de patrocínio e pensando no contato com empresas daq da região, atualizei o slide **'A Cidade'** para quando formos contatar empresas aq de Manaus. Se puderem, dar feedbacks: 

O [plano de patrocínio **regional** em PDF está no drive](https://drive.google.com/file/d/1za_D4aoD-KJDhSUKdknLpJ9HqT9R2mu8/view?usp=sharing).

**Comment by guigasque** [comment]
Muito bom.

Só achei os números que estão no gráfico do slide 13 um pouco pequeno

**Comment by giuliocc** [comment]
Atualizei os planos (nacional e regional) com sua sugestão @guigasque :+1: 

@wasp-lahis obrigado por já ter desenrolado! Eu achei que ficou legal o texto. Vi que tu mudou um pouco o primeiro parágrafo do slide de

> Manaus é conhecida pela Zona Franca da Manaus que explica a grande concentração de indústrias e centros de pesquisa em sua zona metropolitana

para

> Manaus é conhecida pela Zona Franca da Manaus que explica a grande concentração de Indústrias Multinacionais e Centros de Pesquisa em sua zona metropolitana

Para deixar consistente nos dois planos, só queria que a gente escolhesse um. Você acha que o segundo está melhor?

**Comment by giuliocc** [comment]
@julianyraiol @cecivieira @anadulce @rougeth vocês validaram a tabela comparativa dos planos? Se não, peço que validem as seções de "Comunicação" e "Recrutamento" pois têm os números que ficaram pendentes. 

Falando especialmente sobre sessões de Job Fair, estimei que, no máximo, 15 (uma para cada patrocinadora) sessões presenciais de 50 min ao longo de 5 dias de palestras fosse ideal para permitir uma boa organização do espaço. No online, pensei que as sessões poderiam ser um pouco maiores, 90 min, e em termos uma por dia de palestras, mas adicionei uma a mais para a cota Platina para diferenciar um pouco mais suas contrapartidas. O que acham?

**Comment by wasp-lahis** [comment]
Oie @giuliocc, acredito que o segundo pois evidencia que há bastante Indústrias multinacionais (no sentido de grande porte mesmo) na Zona Franca de Manaus. Ex: Honda, Procter & Gamble, Samsung, Whirpool, entre mts outras o/

**Comment by giuliocc** [comment]
Estava pensando agora que talvez seria interessante pensarmos o Job Fair presencial se extendendo para os dias de tutoriais e sprints. Assim teríamos mais atividades interessantes no evento nesses dias também. Nesse caso, na organização atual, poderíamos ter duas sessões presenciais para Platina e Ouro ao invés de apenas uma, chegando a no máximo 20 sessões de Job Fair presencial ao longo do evento. O que acham?

**Comment by rougeth** [comment]
>[...] rougeth vocês validaram a tabela comparativa dos planos? Se não, peço que validem as seções de "Comunicação" e "Recrutamento" pois têm os números que ficaram pendentes.

@giuliocc ficou ótimo!! Uma dúvida que surgiu, "cards para twitter e afins" (comunicação) vs "post de divulgação de vagas" (recrutamento), qual a diferença? Empresa poderá usar o card no Twitter pra divulgar vaga?

**Comment by julianyraiol** [comment]
> Ah, as fotos a @julianyraiol foi pegando do Flickr da Python Brasil se não me engano e foi colocando direto no Canva. Não tem pasta no Drive. Pode dar acesso ao canva - [ ] pra @cecivieira?

oi @giuliocc dei acesso à @cecivieira ao canva

**Comment by julianyraiol** [comment]
> @julianyraiol @jailsonpj @wasp-lahis @guigasque será que rola pedir nos grupy/Pug e pydata de Manaus fotos de eventos presenciais ?

Temos algumas fotos aqui, posso criar uma pasta no drive com fotos de eventos locais

**Comment by cecivieira** [comment]
@julianyraiol Massa!!
Coloca o link da pasta por aqui, quando tu a criar.

**Comment by giuliocc** [comment]
> > [...] rougeth vocês validaram a tabela comparativa dos planos? Se não, peço que validem as seções de "Comunicação" e "Recrutamento" pois têm os números que ficaram pendentes.
> 
> @giuliocc ficou ótimo!! Uma dúvida que surgiu, "cards para twitter e afins" (comunicação) vs "post de divulgação de vagas" (recrutamento), qual a diferença? Empresa poderá usar o card no Twitter pra divulgar vaga?

No meu entendimento, esses posts seriam mais institucionais e até poderiam trazer um link pra página de vagas da empresa. Enquanto os posts de divulgação de vagas iriam realmente divulgar "uma vaga em cada post" que ficaria à escolha da patrocinadora. Não sei se é bem o que estavam imaginando, mas é uma boa discussão @rougeth .

**Comment by giuliocc** [comment]
Total de Job Fair presenciais: 20 (2/platina, 2/ouro, 1/prata)
Total de Job Fair online: 6 (2/platina, 1/ouro) 

Para cada dia de palestra:

Horário | Atividade
---|---
10:00 - 10:50 | Job Fair Presencial
11:00 - 11:50 | Job Fair Presencial
12:00 - 13:30 | Job Fair Online
14:00 - 14:50 | Job Fair Presencial
15:00 - 15:50 | Job Fair Presencial

Para um dia de tutoriais:

Horário | Atividade
---|---
12:00 - 13:30 | Job Fair Online (platina)

**Comment by julianyraiol** [comment]
Link para a pasta com algumas fotos q eu tinha, amanhã posso adicionar outras 😄 @pythonbrasil/time-patrocinio @cecivieira @jailsonpj 

https://drive.google.com/drive/folders/1x76oiF636SI1DR6T-eYT6CLa8YaM55V3

**Comment by cecivieira** [comment]
@julianyraiol usei as fotos da pasta para substituir uma parte das imagens do plano de patrocínio.

**Comment by giuliocc** [comment]
Valeu @julianyraiol ! Se ainda tiver mais pra adicionar, manda mais ;)

**Comment by giuliocc** [comment]
Ficou muito bom :) Obrigado pelas contribuições! Só ajustei algumas imagens que estavam se repetindo.

Links:
 * [Nacional](https://drive.google.com/file/d/1a_gUc7de05n04TS_2-m-1HcIlYu-V2PE/view?usp=sharing)
 * [Regional](https://drive.google.com/file/d/1za_D4aoD-KJDhSUKdknLpJ9HqT9R2mu8/view?usp=sharing)

Podemos fechar a issue @julianyraiol ?

**Comment by julianyraiol** [comment]
eu amei  :heart_eyes:, só vou trocar uma imagem no slide 1 (pedindo uma foto da rafa com a qualidade melhor kk)

**Comment by julianyraiol** [comment]
oi @giuliocc modifiquei a imagem, se puder dar uma olhada depois :pray:

**Comment by giuliocc** [comment]
Dei uns últimos retoques com a @julianyraiol e atualizei os documentos no drive.

Muito obrigado a todo mundo que colaborou <3

Simbora catar patrocínio agora!

Fechando a issue.

**Comment by julianyraiol** [comment]
Parabéns, galera!!! Ficou muito lindoooo :heart:
