### ISSUE TITLE
Discutir opções da pybr presencial + online

### ISSUE THREAD

**Issue by rougeth** [pythonbrasil/pybr2022-org#38]
## Descrição
Com o objetivo de aproveitar o alcance e impacto que a Python Brasil em formado online teve nos últimos dois anos, precisamos discutir se um modelo de evento online complementar se encaixa com os nossos planos.

## Requisitos para a atividade ser considerada como concluída
- Decidir se organizaremos algum evento ou atividade online e, caso sim, o que faremos.

## Referências
- Dados dos eventos 2020 e 2021: https://github.com/pythonbrasil/dados

## Ideias

Vou adicionar as ideias que discutimos durante a reunião #36, mas não deixem de complementar com outras ideias ou opinarem sobre essas.

⚠️ Clique na seta ► para ver os detalhes de cada ideia.

<details>
<summary><b>Ideia 1: “Python Brasilzinha” no primeiro semestre </b></summary>

Fazer uma Python Brasil online, além do evento presencial, na primeira metade do ano, nos moldes das edições de 2020 e 2021, porém, menor (por exemplo, sem tutoriais, apenas uma trilha, apenas no período noturno, etc). Pode ser divulgado como um convite para o evento presencial.

#### Pontos positivos
- Pode ser organizado por um time focado apenas no evento online - mantendo alinhamento com o evento presencial.
- Pode fazer parte do plano de patrocínio - maior alcance > maior retorno financeiro.
- Muitas coisas podem ser reusadas das últimas duas edições do evento.

#### Pontos negativos
- Precisa ser organizado o quanto antes 
- Um dos incentivos dos eventos regionais no primeiro semestre do ano, é gerar engajamento para a Python Brasil, que tradicionalmente acontece no final do ano. Fazer uma “mini pybr” pode competir com eventos regionais que podem acontecer no mesmo período.
- Se organizado pelo mesmo time do evento presencial:
	- mesmo que o evento online seja menor, trabalho aumenta consideravelmente.
	- perda de foco do evento principal
- Se organizado por um time diferente, demandará um esforço maior em comunicação com o time do evento presencial para manter as coisas alinhadas (por exemplo, palestrantes).
- Uma ideia que surgiu na reunião é que o evento online tenha palestras que acontecerão no evento presencial, mas por conta do tempo, acho que difícil de conseguirmos definir a tempo.

</details>

<details>
<summary><b>Ideia 2: Retrospectiva Python Brasil </b></summary>

Evento de reprise da Python Brasil 2022 presencial, algum tempo (meses?) depois do evento principal, em que as palestras gravadas serão publicadas online. Modelo das duas últimas edições online, porém, ao invés de palestras ao vivo, as palestras gravadas no presencial seriam transmitidas.

#### Pontos positivos
- Quem participasse, teria acesso a todas as palestras do evento presencial (em algum momento isso aconteceria mesmo sem evento - com os vídeos prontos publicados no YouTube).
- Oportunidade para quem não pode ir no evento presencial de participar do evento, tendo acesso as palestras e aos palestrantes (poderíamos organizar dos palestrantes ficarem acessíveis durante transmissão de suas palestras).

#### Pontos negativos
- Todas as palestras precisam ser gravadas e estarem editadas para que o evento aconteça.
- Para não saturar a comunidade, a reprise precisaria acontecer um certo tempo depois do evento presencial, talvez apenas em Q2 2023.
- Falta de engajamento do time de organização, uma vez que o desgaste de organizar o evento presencial tenha passado.
- Pouco atrativo?

</details>

<details>
<summary><b>Ideia 3: Python Brasil 2022 ao vivo</b></summary>

Transmitir as palestras ao vivo.

#### Pontos positivos
- Talvez a opção mais fácil para a organização.

#### Pontos negativos
- Custo alto - link de internet suficiente para transmitir 4 ou 5 trilhas, simultaneamente, em alta qualidade.
- Risco alto - se a internet cair, perdemos as transmissões
- Difícil moderação por parte do time de resposta do código de conduta.
- Difícil engajamento do participantes online - participação ativa ao invés de apenas consumir as palestras.
- Difícil justificar a ida ao evento presencial, pagando viagem, hotel, inscrição, se as palestras serão transmitidas ao vivo.

</details>

<details>
<summary><b>Ideia 4: Nenhuma das anteriores</b></summary>
Precisamos considerar não fazer nada online, principalmente por conta do trabalho em cima da organização.
</details>

Caso o caminho escolhido seja fazer um evento online, seja durante o evento presencial ou não, entendo que o plano de patrocínio deve ser atualizado para incluir também o que for feito nesse evento online. Dessa forma, o alcance e impacto do evento online deverá refletir nos valores no plano (Referência #1).

**Comment by muriloviana** [comment]
Super apoio a ideia, o evento online tem um alcance muito valioso para nossa comunidade. Porém, algumas dúvidas surgiram:

1. Esse evento aconteceria na mesma data que a Python Brasil presencial?
2. Os planos de patrocínio englobariam ambos os eventos ou cada evento teria seu próprio plano de patrocínio?
3. Caso venha de fato a acontecer o evento online, isto, gerir um evento virtual além do presencial, se tornaria uma "obrigação" para as futuras organizações?

Talvez vocês inclusive já tenham conversado sobre estes pontos, mas como não achei a ata da última reunião, decidi trazer pra cá 😅

**Comment by rougeth** [comment]
1. Depende. Duas das opção que discutimos na reunião aconteceriam em outras datas (opção 1 e 2 na descrição). Na opção 3, seria a transmissão ao vivo do evento, então seria na mesma data.
2. Sim, atualizei a descrição.
3. Ótima pergunta. Na minha opinião, um evento Python Brasil online deveria acontecer todo ano, mas não sei em que modelo, se organizado pelo time do evento presencial ou não (isso inclusive é algo em aberto nas ideias que listei). Dito isso, acho que essa discussão foge um pouco do foco dessa issue/repo, é mais abrangente.

Obrigado pelas perguntas @muriloviana! Me avisa se algo não ficou claro.

**Comment by anadulce** [comment]
1 - Considerando um dos três cenários onde exista uma versão online, inclusive a concomitante com a presencial, é previsto que seja apenas uma divulgação de conteúdo, ou mais próximo dos moldes que tem ocorrido nos últimos dois anos? Inclusive prevendo a comunicação entre participantes?

2 - Caso vocês optem por realizar um evento menor no primeiro semestre, mais ou menos quando seria? Acho que vale pensar que também ocorrerá a Python Nordeste nesse mesmo período e que é interessante que não sejam eventos concorrentes/próximos. Eu também tomaria o cuidado de realizar uma atividade limitada, que não onerasse muitas pessoas da organização, principalmente das que estiverem disponíveis em Manaus, pois existem muitos pequenos detalhes a serem acertados quanto mais próximo do evento, e essas pessoas estarão bastante ocupadas.

3 - Vocês tem a intenção de fazer essa retrospectiva do evento com datas previamente divulgadas? Como realmente um evento? Se sim, acho um pouco mais arriscado porque já tivemos problemas suficiente com fornecedores para não confiar em datas de entrega de materiais editados para divulgação. Não escolheria essa opção por essa insegurança (organizar a PyBR 2019 me deixou traumatizada sobre vídeos haha).

4 - Já realizaram alguma pesquisa para saber o que será necessário para cogitar transmitir o evento ao vivo? (infra/trabalho da org)

E por fim, se vocês considerarem que está fora das suas possibilidades levaram ambas as iniciativas e resolverem priorizar o evento presencial, tem todo meu apoio. Sim, concordo que é interessante aproveitar o espaço conquistado nesses dois anos de eventos online, e que ele democratizou o acesso à Python Brasil, mas vocês estão começando agora e ainda precisam entender as demandas e responsabilidades do evento, então caso não se sintam seguros, não se sintam pressionados a aceitarem <3
Nada impede que outros eventos de Python sejam organizados online por outras pessoas, os times das orgs anteriores tem trabalhado para documentar e facilitar esse processo, e a comunidade pertence a todas as pessoas, e queremos que elas se sintam donas o suficiente para que organizem outros eventos em novos formatos.

**Comment by rougeth** [comment]
> é previsto que seja apenas uma divulgação de conteúdo, ou mais próximo dos moldes que tem ocorrido nos últimos dois anos? Inclusive prevendo a comunicação entre participantes?

Depende. Se, por exemplo, será apenas lives ou se terá um servidor no Discord, depende da implementação. Ambos os casos se encaixam na três ideias.

> [...] interessante que não sejam eventos concorrentes/próximos

Um dos pontos negativos das ideias 1 e 2 são as datas conflitantes.

> [...] realizar uma atividade limitada 

Essa é a ideia.

> Vocês tem a intenção de fazer essa retrospectiva do evento com datas previamente divulgadas?

Boa pergunta. Além do custo, essa é um outro risco para o evento. Mas considerando que a ideia é usar o evento online no plano de patrocínio, acho que deveria ter datas sim.

> Já realizaram alguma pesquisa para saber o que será necessário para cogitar transmitir o evento ao vivo?

Não chegamos a analisar nenhuma das ideias a fundo.

**Comment by cecivieira** [comment]
Olá,
Considerando que estamos em um momento de **pandemia** e é muito incerta a situação sanitária no segundo semestre de 2022, tenho uns pitacos sobre esse tema: 

- Redimensionamento de público do evento para 400/500 participantes presenciais:
    - Foco no público local;
    - Estabelecimento de percentual para participantes de outros estados;
    - Renegociação com o Governo do Estado para mudança de local para universidade estudual/teatro/etc.

- Evento originalmente pensado para formato híbrido:
    - Transmissão de palestras e keynote em tempo real no Youtube (trabalho 100% tercerizado);
    - Job fair em ambiente virtual;
    - Job fair ambiente presencial;
    - Palestras presenciais;
    - Tutoriais presenciais;
    - Sprints presenciais;
    - Interação apenas pelo Youtube (trabalho da organização);
    - Dividir tempo das perguntas para as oriundas de comentários do youtube e das feitas presencialmente;
    - Estimular a pessoas comentarem sobre o evento com # específica no Twitter;
    - Compartilhamento dos tweets no perfil da pythonbrasil para que eles virem espaços de conversa entre participantes online e presencial do evento; (opcional)

Como Rougeth mostrou nos dados de inscrições, a Python Brasil online foi em torno de 4x maior do que a presencial. Quando pensamos em alcance dos vídeos isso vai para mais de 10x (esses dados ainda precisam ser abertos). Com isso, as cotas de patrocínios puderam ser muito mais altas, o que poderá viabilizar o evento nesse formato.

-----------------

**Respondendo sobre as ideias de pré-evento:**
Tendo em vista que a Python Brasil é um evento grande, que a organização é feita através de trabalho voluntário e nas horas vagas das pessoas, além disso que a quantidade de pessoas na organização é baixa. Talvez seja interessante repensar a realiazação de pré-eventos no sentido de não fazê-los e concentrar energia na realização da conferência principal, em outubro.

**Comment by julianyraiol** [comment]
Baseado nessa discussão e na última [reunião](https://github.com/pythonbrasil/pybr2022-org/issues/43), o evento até o momento será presencial com a transmissão de palestras e keynotes online. Será mantido o mesmo local, o Vasco Vasques, seguindo as instruções de alocação que a administração sugerir, bem como nas medidas adotadas pela secretaria de saúde.

**Comment by cecivieira** [comment]
- Evento gratuito

- Evento originalmente pensado para formato híbrido:
    - Transmissão de palestras e keynote em tempo real no Youtube (trabalho 100% tercerizado);
    - Job fair em ambiente virtual (Google meet, skype, zoom,etc.);
    - Job fair ambiente presencial;
    - Palestras presenciais;
    - Tutoriais presenciais;
    - Sprints presenciais;
    - Interação apenas pelo Youtube (trabalho da organização);
    - Dividir tempo das perguntas para as oriundas de comentários do youtube e das feitas presencialmente;
    - Estimular a pessoas comentarem sobre o evento com # específica no Twitter;
    - Compartilhamento dos tweets no perfil da pythonbrasil para que eles virem espaços de conversa entre participantes online e presencial do evento; (opcional)
