### ISSUE TITLE
Agendar visita ao local do evento

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#41]
Na nossa [última reunião ](https://github.com/pythonbrasil/pybr2022-org/issues/37)o @jailsonpj ficou como responsável por enviar um e-mail agendando uma reunião com a AmazonasTur para conversarmos sobre o local do evento e agendarmos uma visita.

Essa visita é para que possamos identificar quais espaços estão disponíveis. Dessa forma podemos dividir quantas salas teremos. 

- Quantas pessoas cabem em uma sala?
- A cozinha está liberada para nosso uso?
- Qual a capacidade do estacionamento?

**Comment by jailsonpj** [comment]
O contato com a Amazonas Tur foi feito hoje 17/01/2022 às 11hrs. 
Aguardando retorno.

**Comment by julianyraiol** [comment]
O Centro de Convenções está sendo utilizado para testagem da [COVID-19](https://www.manaus.am.gov.br/noticia/prefeitura-reforca-que-centro-de-testagem-do-vasco-vasques-inicia-atendimento-na-quarta-19-1/). Sem data prevista para a liberação do espaço.


[issue-6](https://github.com/pythonbrasil/pybr2022-org/issues/6)

**Comment by jailsonpj** [comment]
Foi agendada uma reunião com o Presidente da Amazonas Tur, no dia 01/02/2022.

**Comment by jailsonpj** [comment]
A visita será agendada logo após ser enviado o documento de informações sobre o evento para a secretária de turismo do estado do amazonas

**Comment by julianyraiol** [comment]
[Status](https://github.com/pythonbrasil/pybr2022-org/issues/59) da reunião realizada no dia 03 de fevereiro de 2022
