### ISSUE TITLE
Decidir ferramenta de submissão de palestras e tutoriais

### ISSUE THREAD

**Issue by rougeth** [pythonbrasil/pybr2022-org#48]

**Comment by giuliocc** [comment]
(em andamento)

Levantamento de ferramentas disponíveis:
 - [papercall](https://www.papercall.io/)
 - [pretalx](https://pretalx.com/p/about/)

**Comment by cecivieira** [comment]
@renan-assis-santos dá uma olhada na issue #50 pra tu ter ideia do que a ferramenta precisará cobrir

**Comment by cecivieira** [comment]
A experiência como usuária do Pretalx tá bem boa. Acredito que é possível fazer formulários diferentes:
- coleta de dados sociocultural das participantes
- submissão de palestras
- solicitação de auxílio viagem

**Comment by cecivieira** [comment]
Talvez alterar essa issue para "Ferramenta para Inscrição de participantes e palestras" para a gente ter um sistema único

**Comment by renan-assis-santos** [comment]
Eu to testando agora msm com o pappercall, vou compilar o que achei bom e nem tanto dele e mando aqui

**Comment by cecivieira** [comment]
@renan-assis-santos se tu puder, observa se é possível esse sistema suportar 3 formulários diferentes:

    coleta de dados sociocultural das participantes
    submissão de palestras
    solicitação de auxílio viagem

**Comment by renan-assis-santos** [comment]
Informações do PaperCall

- Sessão para descrição do evento
- Sessão para descrição do código de conduta
- Submissões anonimizadas
- Campo para descrição do que precisaríamos dos participantes via texto
- Possibilidade de adicionar tags personalizadas pro palestrante escolher (iniciante, nao tecnico, etc)
- Campo se oferecemos assistencia de viagem (nao é possivel a pessoa escolher se precisa ou nao selecionando, isso seria uma informacao adicional que ela teria que colocar na descrição da sua proposta)
- Forma de escolha das palestras ou dando notas de 1 a 5 ou sim, nao, talvez
- Plano pago de $499 possui submissoes ilimitadas, 5 questoes boleanas customizadas para os participantes

**Comment by renan-assis-santos** [comment]
> A experiência como usuária do Pretalx tá bem boa. Acredito que é possível fazer formulários diferentes:
> 
> * coleta de dados sociocultural das participantes
> * submissão de palestras
> * solicitação de auxílio viagem

Testei o pretalx e achei bem mais alinhado com nossos propósitos mesmo

**Comment by giuliocc** [comment]
Mais uma ferramenta que podemos olhar: https://sessionize.com/

**Comment by renan-assis-santos** [comment]
# Comparação entre ferramentas de submissão

## [PapperCall](https://www.papercall.io/)

Pontos a serem considerados:
* Interface simples e não personalizável, poucos recursos disponiveis.
* Apenas 5 questoes booleanas na criação dos formularios
* Sessão para descrição do código de conduta
* Adição de tags por conta da organização
* Campo se oferecemos assistencia de viagem (nao é possivel a pessoa escolher se precisa ou nao selecionando, isso seria uma informacao adicional que ela teria que colocar na descrição da sua proposta ou gastaríamos uma das 5 questoes booleanas)
* Forma de avaliação das palestras ou dando notas de 1 a 5 ou sim, nao, talvez. Sem avaliações mais complexas.
* Se quisessemos dados socioculturais dos participantes teriamos que usar as questoes booleanas

Preço: $499
Formas de pagamento: não informada

Avaliação final pessoal: é uma ferramenta que não possui alguns requisitos mínimos de personalização que precisaríamos como informações pessoais adicionais dos participantes. A forma de avaliação é bastante simplista sendo a primeira opção notas de 1 a 5 e a segunda apenas sim/não/talvez.

## [Sessionize](https://sessionize.com/)

Pontos a serem considerados:
* Interface muito organizada e intuitiva
* Possibilidade de adicionar logo do evento e design proprio
* Possibilidade de adicionar co-speakers nas submissões
* Agent mode (Permite submissões no nome de outra pessoa, util para secretarios, agentes e gerentes de marketing)
* Formulário de submissão com separação entre campos da submissao e campos da pessoa palestrante
* Criação de questões personalizadas nos formulários de submissão do tipo escolha única, múltipla escolha ou questão de escrita (restrita aos tipos: texto curto, texto longo, upload de arquivo, URL, número inteiro, checkbox, porcentagem ou email)
* Possibilidade de edição das subissoẽs (Sim, mas apenas 1h dps da submissão; sim, mas apenas no periodo do call for speakers aberto; sim pra qualquer hora)
* Feature para exportação de dados automatica por um periodo: a cada 3 dias, a cada semana, a cada 2 semanas ou a cada mes. Ocorre até 1 mes dps do evento.
* Gráfico de cada pergunta que fizermos pros palestrantes
![](https://i.imgur.com/pMzVuDG.png)
* 3 tipos de avaliação de palestras sendo possivel fazer mais de uma sessão de avaliação como uma simples tipo sim/nao/talvez e outra mais complexa.
![](https://i.imgur.com/s2LDFEG.png)
* No formato de "stars rating" é possível avaliar critérios personalizaveis pela organização com pesos especificos
![](https://i.imgur.com/9bfgjG8.png)
* Possibilidade de filtrar as avaliações pra só palestrantes com X característica, só Y linguagem etc
* Avaliações de palestras pode mostrar as caracteristicas e questoes importantes que responderam (genero, auxilio viagem, etc)
* Avaliações anonimizadas
* Fácil criação da agenda das palestras submetidas e possibilidade de disponibilizar publicamente
* Possibilidade de exportar dados dos palestrantes e das submissões
* Ferramenta de envio de emails para todos os palestrantes que tiveram propostas aceitas ou para todos os que nao tiveram propostas aceitas. Também existe a possibilidade de enviar emails com feedbacks individuais pela ferramenta

Preço: 499 USD
Formas de pagamento: Cartão de crédito, paypal, transferência bancária e GooglePay

Avaliação final pessoal: É uma ferramenta muito completa e fácil de manusear, além de ser muito personalizável. Por todos os pontos listados acima vejo que não faltaria nada que precisaríamos na organização e não vejo nenhum ponto negativo.


## [Pretalx](https://pretalx.com/)

* Ferramenta open-source utilizada na PyCon, assim é bem conhecida
* Possibilidade de adicionar co-speakers nas submissões
* Interface de criação do evento confusa de início, mas compreensível depois de um tempo
* Configurações do evento em várias paginas diferentes sendo dificil localizar onde é preciso alterar
* Possibilidade de tradução de outras linguas para todos os campos, exemplo titulo, descrição do evento, formulario de submissão de palestras em portugues e espanhol
![](https://i.imgur.com/svhwOMf.png)
* Possibilidade de feedback anonimo pela plataforma por parte dos participantes do evento
* Possibilidade de colocar logo e desing do nosso evento
* Avaliação de palestras muito personalizada sendo possivel adicionar diversos criterios com pesos diferentes
* Possibilidade de exigir um texto de revisão dos revisores das palestras
* Mostrar programação do evento na pagina inicial da ferramenta ou até adicionar no nosso site próprio
* No formulário de submissao possibilidade de adicionar quais disponibilidades de horarios e dias os palestrantes possuem
* Configuração de tamanho minimo e maximo nos titulos, resumo e biografia da submissao
* Possibilidade de adicionar perguntas quaisquer no formulario de submissao sem limite e totalmente personalizaveis
* Envio de lembretes para perguntas nao respondidas
* Adição de perguntas que podem ser requeridas apos um certo prazo tipo após o evento os palestrantes darem um feedback sobre o que acharam
* Estatísticas de propostas
* Exportação de dados dos palestrantes e das propostas
* Revisão de propostas no modelo todos avaliam uma a uma nos criterios especificados
* Ferramenta de envio de emails para avisar sobre propostas recebidas, aceitas, rejeitadas e aviso de cronograma novo


Preço: Variável conforme o número de participantes que teremos e o preço do ingresso. Fazendo algumas estimativas seria 449 EUR
Formas de pagamento: Não informado.

Avaliação final pessoal: É uma ferramenta bem completa, mas de difícil utilização e confusa na sua organização, isso geraria um trabalho da organização para configurar o evento na ferramenta. É altamente personalizável e um bom ponto a ser levantado é para os participantes adicionarem em quais dias e horarios conseguiriam. O preço e a interface da ferramenta seriam os únicos pontos a serem pensados com cautela.

---
## Avaliação final (pessoal) das ferramentas:
A ferramenta PapperCall falta muitos recursos que precisaríamos então já descartaria, ficando entre a Sessionize e a Pretalx. Entre as duas existem poucas diferenças de funcionalidades, mas a principal que percebi criando o evento de teste em ambas, submetendo palestras e avaliando-as é a configuração confusa da Pretalx ao contrário da Sessionize que é muito intuitiva. A Pretalx possui algumas coisas que a Sessionize não tem como tradução em linguas diferentes, ferramenta dos palestrantes colocarem a disponibilidade de horário e envio de lembrete de perguntas não respondidas, mas para mim isso não supera a facilidade de utilização da Sessionize.

**Comment by julianyraiol** [comment]
Ficou definido o uso da Pretalx, decidido na [reunião](https://github.com/pythonbrasil/pybr2022-org/issues/105) 09.03.
