### ISSUE TITLE
Definir trilha em espanhol

### ISSUE THREAD

**Issue by rougeth** [pythonbrasil/pybr2022-org#52]

**Comment by cecivieira** [comment]
Ideia:

Levando em conta o atual fenômeno migratório que decorre dos países vizinhos e estabelece comunidades, principalmente, nos estados fronteiriços aonde essas pessoas estão reconstruindo sua vida profissional em condições muito inferiores ao do seu país de origem - na maior parte dos casos, desenvolvendo atividades que não são sua profissão -, sugiro:

- Destinar um percentual das vagas para imigrantes que ainda não estão exercedo sua profissão no nosso mercado de trabalho;
- Realizar parceria com ONGs e instituições que acolhem e prestão serviços para imigrantes, no sentido de divulgação das vagas.
