### ISSUE TITLE
Definição de grupos de trabalho 

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#55]
## Grupos de trabalho
| Grupo | Descrição | Pessoas Responsáveis |
|---|---|---|
| Comunicação/Marketing | Desenvolver textos para postagem em redes sociais e canais de divulgação previamente mapeados, entrar em contato com entidades para realizar divulgação do evento. | @time-comunicacao |
| Design | Criação da nova identidade visual do evento, que deverá ser aplicada para materiais gráficos e digitais que do evento.| @pythonbrasil/time-design  | 
| Patrocínio | Responsável pelo contato entre empresas e obtenção de recursos para o patrocínio do evento.| @pythonbrasil/time-patrocinio |
| Infraestrutura Remota | Responsável por viabilizar a transmissão das palestras e keynotes, lidando com a infraestrutura e contratos para o respectivo serviço. |  -- |
| Site | Responsável pelo desenvolvimento da landing page do site. | @pythonbrasil/time-site  |
| Organização de trilhas | Coordenação das submissões, seleções e distribuições de atividades e ministrantes. | @pythonbrasil/time-trilhas |

**Comment by renan-assis-santos** [comment]
Posso entrar no grupo da programação do evento também, nele seriam as responsabilidades de organizar as palestras, horários, trilhas etc?

**Comment by julianyraiol** [comment]
1. oi @renan-assis-santos, obrigada! vou adicionar você nesse grupo o/

2. é que na última reunião nós voltamos a levantar esse tópico.
