### ISSUE TITLE
Criar apresentação para reunião com o presidente da Amazonas Tur

### ISSUE THREAD

**Issue by jailsonpj** [pythonbrasil/pybr2022-org#56]

**Comment by julianyraiol** [comment]
[patrocinio_python_brasil (3).pdf](https://github.com/pythonbrasil/pybr2022-org/files/8008744/patrocinio_python_brasil.3.pdf)

Apresentação utilizada na reunião.

Status do que foi discutido na [issue](https://github.com/pythonbrasil/pybr2022-org/issues/59)
