### ISSUE TITLE
Criar politica de rastreamento e apoio em relação a COVID durante o evento.

### ISSUE THREAD

**Issue by luzfcb** [pythonbrasil/pybr2022-org#6]
Tendo em vista o cenário atual, é necessário que a organização do evento crie ações para incentivo à vacinação e considere a apresentação do cartão de vacina durante o evento. 

Além disso, liste no site os pontos mais próximos ao local do evento onde esteja ocorrendo a vacinação.

**Comment by julianyraiol** [comment]
Definimos a data de alerta para o dia 31.01.22. A cada [reunião](https://github.com/pythonbrasil/pybr2022-org/issues/37) estamos conversando sobre a situação da pandemia no Brasil. Até o momento iremos manter o evento presencial.

**Comment by julianyraiol** [comment]
O Centro de Convenções está sendo utilizado para testagem da [COVID-19](https://www.manaus.am.gov.br/noticia/prefeitura-reforca-que-centro-de-testagem-do-vasco-vasques-inicia-atendimento-na-quarta-19-1/). Sem data prevista para a liberação do espaço.

**Comment by cecivieira** [comment]
A página da pycon us sobre as medidas de contenção pra covid é tá bem interessante. Vou deixar aqui como inspiração:

https://us.pycon.org/2022/attend/health-safety-guidelines/

**Comment by giuliocc** [comment]
[Última versão do guia da OMS para planejamento de eventos de grande porte](https://www.who.int/publications/i/item/10665-332235) (04/11/21) e [outro sobre medidas de prevenção à COVID em ambientes de trabalho](https://www.who.int/publications/i/item/WHO-2019-nCoV-workplace-actions-policy-brief-2021-1) (19/05/21).

**Comment by julianyraiol** [comment]
[Último decreto municipal](https://g1.globo.com/am/amazonas/noticia/2022/02/16/amazonas-amplia-para-50percent-a-capacidade-do-publico-em-eventos-apos-reducao-de-casos-de-covid.ghtml)
