### ISSUE TITLE
Preço de ingresso

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-org#60]
### Descrição
Estabelecer preço para ingresso do evento presencial.

### Requisitos para a atividade ser considerada como concluída
- Cotar custos de itens a ser cobertos pelo ingresso
- Estabelecer preço do ingresso

**Comment by julianyraiol** [comment]
- [ ] Definir quantidade de lotes e seus respectivos valores

**Comment by julianyraiol** [comment]
Realizar orçamentos para estimar ingressos

**Comment by julianyraiol** [comment]
oi @giuliocc ainda não tem uma pessoa responsável para realizar esse orçamento

**Comment by cecivieira** [comment]
@wasp-lahis será que a dúvida sobre o preço do ingresso não rola de ser assíncrona?

**Comment by cecivieira** [comment]
Foi definido na #178 , o custo do ingresso deve ser coberto pelos seguintes gastos individuais:

- Camisa
- 50% do aluguel do local
- Corda e crachá
- Ecobag
- Caneca
