### ISSUE TITLE
Decidir sobre existencia de campanha de arrecadação financeira

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-org#61]
Na edição Pybr21 foi realizada uma exitosa campanha de arrecadação financeira em benefício de uma ONG que trabalha no combate a fome.

Pensando na ideia original que faz com que o congresso seja um evento itinerante, "impactar positivamente a região", e na tendência da comunidade Python em desenvolver projetos de código aberto com impacto social, poderíamos nesta edição da PyBR promover uma campanha que beneficie uma instituição que trabalhe com temas importantes para o estado sede. Algumas sugestões:

- Comunidades indígenas
- Meio ambiente

A arrecadação seria através de doação voluntária no ato da inscrição do evento online e presencial, além de incentivos de doação direta para a instituição durante as apresentações das palestras e keynotes.

**Comment by Kadidjah** [comment]
Super interessante @cecivieira !
De acordo.
