### ISSUE TITLE
Criação de plano de trabalho

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#62]
Criação de um plano de trabalho para ser enviado à AmazonasTur afim de obter a liberação oficial do Centro de Convenções Vasco Vasques. 

#56 
#59 

**Tópicos Iniciais**

**Python Brasil**
O evento
A Comunidade
Eventos anteriores	
Python Brasil em Manaus / Remoto
Participantes
Ingressos (adicionar lotes)
Diversidade e Inclusão
Código de Conduta

**Programação do Evento**

**Organizadores**

**Grupos de trabalho**

**Infraestrutura do Evento**
Fornecedores
Serviços

**Medidas de segurança**

**Patrocínio**
Por que patrocinar?
Quem já patrocinou?
Cotas de patrocínio

**Cronograma geral**

[Arquivo](https://docs.google.com/document/d/1B4hKUM2-IGbQfdntY3a8uBp4KA14dybe-7YhS42xB7c/edit#)

**Comment by cecivieira** [comment]
Alguém poderia colocar o link do plano de patrocínio aqui, por favor?

**Comment by cecivieira** [comment]
Ajustes a serem feitos:

1 - Desmembrar os dados referentes ao evento online e presencial, presente no slide 14.
2 - Nas cotas de patrocínio, explicitar o que significam "bolsas". Talvez só trocar o termo ou colocar um * no pé da página
3 - Revisar plano de patrocínio da [PyBr21](https://github.com/pythonbrasil/pybr2021-site/blob/main/public/plano-patrocinio-pybr2021.pdf) e verificar se há algum benefício do evento online que pode ser incluído no Plano de Patrocínio atual

**Comment by jailsonpj** [comment]
Regulamento do Centro de Convenções Vasco Vasques: http://www.amazonastur.am.gov.br/wp-content/uploads/2020/03/Regulamento-de-Uso-Regimento-Interno-CCA-1.pdf

![image](https://user-images.githubusercontent.com/13952136/153651577-af5e1751-a5d2-4aa5-ad75-e0c9f1d140dd.png)

Informações que precisam ter no documento.

**Comment by cecivieira** [comment]
@jailsonpj qual é a capacidade do lacal considerando pessoas sentadas?
Idealmenteprecisamos saber a capacidade por sala.

**Comment by cecivieira** [comment]
@pythonbrasil/apyb Vocês poderiam disponibilizar o CADASTUR? Sabe se a APyB tem esse tipo de documento ou um correspondente?

**Comment by jailsonpj** [comment]
> @jailsonpj qual é a capacidade de lacal considerando pessoas sentadas? Idealmenteprecisamos saber a capacidade por sala.

Eu estou esperando a resposta da secretaria. Enviei um email para eles perguntando sobre a capacidade máxima do local, capacidade para pessoas sentadas e informação da quantidade de pessoas que a Secretaria de Saúde do Estado do Amazonas alocou no período de vacinação.

**Comment by rougeth** [comment]
> @pythonbrasil/apyb Vocês poderiam disponibilizar o CADASTUR? Sabe se a APyB tem esse tipo de documento ou um correspondente?

Estou na dúvida se esse cadastro se aplica a APyB, já que não atuamos no setor de turismo:

> Cadastur é o sistema de cadastro de pessoas físicas e jurídicas que atuam no setor de turismo.

https://cadastur.turismo.gov.br/hotsite/#!/public/duvidas-frequentes/inicio

**Comment by cecivieira** [comment]
@pythonbrasil/apyb Qual é a categoria (é assim que chama?) do CNPJ da APyB? Ela tá registrada como o que?

**Comment by rougeth** [comment]
- Atividade Principal: 94.99-5-00 - Atividades associativas não especificadas anteriormente
- Atividade Secundária: 94.93-6-00 - Atividades de organizações associativas ligadas à cultura e à arte

**Comment by cecivieira** [comment]
@jailsonpj , por favor, questiona sobre a obrigatoriedade do registro do CADASTUR. Informa que a empresa organizadora do evento é uma associação sem fins lucrativos e que tá cadastrada como "Atividades de organizações associativas ligadas à cultura e à arte", além disso pergunta se o Estatuto Social da associação seria suficiente

**Comment by jailsonpj** [comment]
@cecivieira blzinha, vou perguntar.

**Comment by cecivieira** [comment]
@giuliocc tu poderia considerar isso na tua proposta de ocupação dos espaços e atualizar a capacidade do evento?
Como eu imagino esse cálculo:

- Dividir 3.500 pelos metros quadrados disponíveis na área dos pavilhões e salas;
- Multiplicar o resultado (qnt de pessoas por metro2) pelo total de m2 considerando a soma das salas 2, 3, 4 e 5 (as que estão previstas para uso);
- Dividir por 2 (pensando nas conversas anterior sobre ocupar apenas 50% da lotação)

**Comment by giuliocc** [comment]
Somando todas as áreas abaixo e dividindo por 3500, o valor que eles estão passando pra gente é de **1,16 pessoas sentadas / m²**.

![image](https://user-images.githubusercontent.com/26327506/154094404-5c42c54b-abcc-4aa7-8b8c-47b6444635f9.png)

Isso daria **~1953 pessoas sentadas nos salões B-E** considerando a área toda dos salões. Ou seja, ocupando 50% da lotação, **976 pessoas sentadas**.

Porém, levando em conta espaço para palco e passagem de pessoas, eu **diminuiria o espaço dos salões para 300 m² cada**.

Assim, teríamos **~1392** pessoas sentadas nos salões B-E**, ou seja, **696 pessoas sentadas** com ocupação de 50%.

**Comment by muriloviana** [comment]
@cecivieira @jailsonpj segundo o regulamento de uso do CCV, no artigo primeiro, parágrafo 7 e 8 falam sobre associações sem fins lucrativos e quais documentos são necessários enviar para a Amazonastur.

![Screen Shot 2022-02-16 at 19 35 54](https://user-images.githubusercontent.com/6524275/154370053-b42af881-efd0-4161-84a8-ccc796f0ad0a.png)

![Screen Shot 2022-02-16 at 19 36 21](https://user-images.githubusercontent.com/6524275/154370089-ee49b6b1-708a-4479-a3a8-1dc77ae154b8.png)

Logo, se a Amazonastur confirmar que basta essa documentação, citada no parágrafo 8, para pleitearmos o espaço, basta a APyB nos passar esses documentos, o que não deve ser muito complicado (assim espero 😅).

**Comment by cecivieira** [comment]
@jailsonpj alguma nova informação da Secretaria de Turismo sobre a documentação necessária?

**Comment by julianyraiol** [comment]
seria interessante termos um status esse semana pois na próxima é feriado de carnaval @jailsonpj

**Comment by julianyraiol** [comment]
Acredito que esta atividade está como **Bloqueada** enquanto não tivermos uma resposta sobre o cadastro na CASTUR :cry:

**Comment by cecivieira** [comment]
@julianyraiol nós podemos considerar o trecho que Murilo postou há alguns dias. A resposta que está vamos esperando seria apenas uma confirmação. Mas acredito que podemos finalizar o plano com a documentação considerando os requisitos do trecho do Regulamento postado por Jailson e Murilo

**Comment by muriloviana** [comment]
@cecivieira concordo com você! Vou começar a recolher a documentação citada no regulamento do CVV pra não perdermos muito tempo.

@jailsonpj se quiser me passar o contato do pessoal do CVV posso ver isso diretamente com eles, ou quem mais tiver esse contato para me passar rs.

**Comment by julianyraiol** [comment]
oi @muriloviana, peguei a informação com @jailsonpj e adicionei aqui na [lista](https://docs.google.com/document/d/1qwMW3wcDxJlfpYfOR7S_LQfaAZIbCaVG/edit#heading=h.au5foj924yj2) de contatos

**Comment by julianyraiol** [comment]
o documento foi enviado para a amazonastur, em cópia foi adicionado o e-mail da @anadulce @muriloviana e @jailsonpj
