### ISSUE TITLE
[Reunião] Designer: 07 de fevereiro de 2022

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#63]
_[Remover antes de abrir o ticket] Este template deve ser editado com os itens a serem discutidos durante a reunião. Toda colaboração é bem vinda. Durante a reunião devem ser registradas as participantes e as decisões tomadas, caso hajam informações sensíveis, deve ser criado um arquivo no [Google Drive da organização da Python Brasil 2022](https://drive.google.com/drive/folders/18zvyKpV42k_n_8Sr4a7yo5KxyU_SFgen?usp=sharing) e o link inserido nessa issue. Após o encerramento, o grupo responsável pela reunião deve revisar as informações e fechar a issue em não mais do que uma semana._

# Reunião Designer: 07 de fevereiro de 2022

- Data: 07 de fevereiro de 2022
- Participantes:
  - Tainah Valois
  - Paulo Sergio
  - Juliany Raiol
  - Jailson Pereira
  - Klayton Fadul
  - Nayara Souza e Thaís Lopez (acompanharam pela gravação)

## Ata

_Primeira reunião semanal do time de Design. A reunião teve como objetivo alinhar o que foi pesquisado na semana passada para levantamento de elementos visuais de inspiração para criação da identidade visual do evento. Na reunião debatemos sobre:_

- Apresentar as referências visuais que tínhamos pesquisado.
- Debater com todos as ideias que poderiam ser aplicadas na nova identidade visual.
- Filtragem das referências visuais (para criarmos uma linha visual de inspiração).
- Registro do que deve ser pesquisado mais a fundo (atividade dessa semana).
- Confirmação da próxima reunião semanal.

### Ações para serem realizadas

- Pesquisar mais sobre paletas de cores, aplicação de identidade visual em elementos gráficos e digitais, identidade visual de eventos tech, identidade visual de elementos que envolvam o tema do evento (Todos os designers)
- Reunião semanal confirmada para a próxima segunda-feira dia 14 de Fevereiro às 18h30 via Discord - Chanel Design.

**Comment by taivalois** [comment]
@julianyraiol Editei a ata no seu comentário acima

**Comment by julianyraiol** [comment]
obrigada Tai @taivalois  <3
