### ISSUE TITLE
Criar templates para issues

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-org#65]
- Duplicar template de issues da Pybr2021(https://github.com/pythonbrasil/pybr2021-org/tree/main/.github/ISSUE_TEMPLATE) sobre criação de tarefas e peças publicitárias
- Solicitar revisão da equipe de design

**Comment by julianyraiol** [comment]
[Template para a Criação de tarefas](https://github.com/pythonbrasil/pybr2022-org/commit/778cd2906a1a3fd0c92ded6532e7966bb9b340fe)
