### ISSUE TITLE
Prever custos para o evento

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-org#66]
Criar planilha com os custos previstos para o evento.

Essa issue está concluida quando:
- Existir tabela com todos os custos listados
- Existir orçamento base para todos os custos

**Comment by cecivieira** [comment]
@julianyraiol @jailsonpj @giuliocc @giovanadelucca Imagino que essa tabela já exista. Poderiam colocar o link nessa issue?

**Comment by cecivieira** [comment]
Cotar custo para gerenciamento de redes sociais

**Comment by julianyraiol** [comment]
[Link da pasta no drive que contém a planilha de custos do evento
](https://drive.google.com/drive/u/0/folders/1ffTT7PAWz5SiMjLYZyxov8xtcECJ1R50)

**Comment by cecivieira** [comment]
Cotar custo de fotógrafas para o evento

**Comment by cecivieira** [comment]
@wasp-lahis tem essa issue

**Comment by cecivieira** [comment]
Contratação de ambulância conforme exigência do Centro de Convenções Vasco Vasquez:

'''
Na eventualidade do número de participantes atingir +/- 1.000 pessoas, será
necessário a permanência de uma ambulância ou mais ambulâncias e equipe na área externa
do CCAVV, durante a realização do evento;
'''

**Comment by cecivieira** [comment]
Planilha financeiro:

https://docs.google.com/spreadsheets/d/1g2qmJSoTrxiugwxSqHbMqEb9N0m2igjf9_xOO-0akAY/edit#gid=106041710

**Comment by cecivieira** [comment]
Contratação de:
- técnico de eletricidade (plantão)
- serviço de limpeza
- segurança para pessoas
- internet
- áudio visual para evento presencial
- serviço de stream para evento híbrido
- catering
- stands para patrocinadoras
