### ISSUE TITLE
Criação de logo para o evento

### ISSUE THREAD

**Issue by PSFreitas** [pythonbrasil/pybr2022-org#67]
### Descrição

Esta tarefa consiste em criar uma logo que irá nos guiar na tarefa da criação de uma identidade visual para o evento.

**Comment by julianyraiol** [comment]
Oi @taivalois e @PSFreitas, por favor, adicionar a data para entrega. :upside_down_face: 

#74

**Comment by PSFreitas** [comment]
@julianyraiol Assim que nos reunirmos nesta terça-feira (15/02) acredito que teremos uma data.

**Comment by PSFreitas** [comment]
Após reunião feita hoje concordamos na data de 04 de Março para a entrega da logo.

**Comment by PSFreitas** [comment]
Tivemos alguns imprevistos e por causa disso prorrogamos a data de entrega em mais uma semana

**Comment by julianyraiol** [comment]
Nova versão já foi desenvolvida. Parabéns, pessoas :heart_eyes:
