### ISSUE TITLE
Criar cronograma geral do evento

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#68]
### Descrição

Listar as atividades e suas respectivas datas de entrega para que o evento aconteça e adicionar ao plano de trabalho.

### Requisitos para a atividade ser considerada como concluída

Planilha com as atividades e sua respectiva data de entrega.

**Comment by julianyraiol** [comment]
Link da planilha com o cronograma
https://docs.google.com/spreadsheets/d/1B4H7Di94yto45nTOYmhoKtplWZiPKC1T-25bY8gLHN8/edit#gid=0

**Comment by rougeth** [comment]
Podemos colocar isso em um calendário? Acho que ficará mais fácil ver o que está se aproximando sem precisar ir sempre na planilha. Nós temos um calendário da org, né?

**Comment by julianyraiol** [comment]
Temos sim um calendário da org, pensei em adicionar em uma planilha para anexar ao plano de trabalho @rougeth 

Mas vou adicionar ao calendário também :+1:
