### ISSUE TITLE
Criar onboarding para novos membros da organização

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#69]
### Descrição
Estruturar um onboarding onde novos membros possam compreender o status do evento e contribuir de maneira assíncrona. 

### Requisitos para a atividade ser considerada como concluída

- Estrutura do programa de onboarding
- Slides

**Comment by julianyraiol** [comment]
Adicionar ao documento informações como:

- Decisões tomadas pela organização até o momento (dias do evento, local, remoto)
- Apresentar grupos de trabalho
- Canais de comunicação
- Horário de reuniões

**Comment by julianyraiol** [comment]
Link para a apresentação https://docs.google.com/presentation/d/1x6h7aFsxRuY2x60aWAu123TIYTZgj7e2kzTbVaLUdGw/edit#slide=id.p

**Comment by julianyraiol** [comment]
Adicionar a quantidade de pessoas por grupo de trabalho

**Comment by rougeth** [comment]
@julianyraiol o que acha de colocar essas informações no README.md? Pode ser que a apresentação tenha mais informação, mas essas que você listou me parecem úteis pra ficar já no próprio README.md.

**Comment by julianyraiol** [comment]
oi @rougeth, acho uma boa ideia. vou adicionar essas informações no [readme](https://github.com/pythonbrasil/pybr2022-org/blob/main/README.md) do repositório

**Comment by cecivieira** [comment]
Frequência: a cada 2 semanas
Decidido em #76

**Comment by wasp-lahis** [comment]
Dei uma atualizada nos Slides @julianyraiol @giuliocc . Aproveitei alguns slides do Plano de Patrocínio. Tá faltando as infos de:

**- Programação e Trilhas**
**- Grupo de trabalho Contato com os Fornecedores**

Sobre o primeiro item, já temos essas infos de programação e trilhas definidas? faz sentido ter essas infos no Onboarding?

ah, e claro, fiquem à contade p mudar template, formatação e conteúdo.

**Comment by wasp-lahis** [comment]
Criei um tópico chamado **Canais de Comunicação**. A ideia é apresentarmos para os novos integrantes como temos trabalhado (e.g., Discord, Github, pasta do Drive)

**Comment by julianyraiol** [comment]
Oi @wasp-lahis, muito obrigada! Achei que ficou muito massa as informações que você adicionou. Vou complementar com o restante.

**Comment by julianyraiol** [comment]
Algumas informações adicionadas no [README](https://github.com/pythonbrasil/pybr2022-org/blob/main/README.md).

**Comment by wasp-lahis** [comment]
Oie gente, atualizei a  apresentação de Onboarding, utilizando o template e novas fotos da apresentação do Plano de Patrocínio. Se puderem, deem sugestões o/

Os slides podem ser encontrados nas pasta [Onboarding](https://drive.google.com/drive/folders/1dUAIcTa1p_rhW-2t4autlLPwImaB8Iit?usp=sharing,).
