### ISSUE TITLE
Criar treinamento para a equipe de Código de Conduta

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#7]
- montar equipe para a organização do código de conduta e fazer rodadas de treinamento

**Comment by rougeth** [comment]
Vou deixar algumas referências da pybr2021:
- [Código de Conduta](https://python.org.br/cdc/)
- [Protocolo do participante para denunciar incidentes que infringem o Código de Conduta](https://github.com/pythonbrasil/pybr2021-org/blob/main/protocolos/protocolo-denuncia-incidente.md)
- [Protocolo da equipe para resposta aos incidentes que infringem o Código de Conduta](https://github.com/pythonbrasil/pybr2021-org/blob/main/protocolos/resposta-incidente-cdc.md)

**Comment by cecivieira** [comment]
@julianyraiol já tem alguém de Manaus pensada para a liderança da equipe do CDC?

**Comment by julianyraiol** [comment]
oi @cecivieira, ainda não tem nenhum nome definido, vou adicionar na ata da próxima reunião
