### ISSUE TITLE
Patrocínio da Sólides Tecnologia

### ISSUE THREAD

**Issue by rougeth** [pythonbrasil/pybr2022-org#72]
### Descrição

Acompanhamento das tarefas relacionadas ao possível patrocínio da Sólides Tecnologia.

### Requisitos para a atividade ser considerada como concluída

- Contrato assinado
- Patrocínio recebido em caixa
- Pendências pós evento concluídas

Ticket #8014 - Patrocínio

**Comment by rougeth** [comment]
Contato direto no email de eventos da Python Brasil. Precisamos responder que:

- o plano ainda não está pronto mas que deve estar pronto nas próximas semanas
- e que entraremos em contato quando concluído

**Comment by giuliocc** [comment]
Email recebido em 10/02/22:

```
Boa tarde! Tudo bem?

Meu nome é *****, eu trabalho na Sólides Tecnologia, na equipe de eventos.

Este é o [site](https://solides.com.br/) da nossa empresa para você nos conhecer melhor!

Nós estamos analisando possíveis parcerias e patrocínios com eventos de tecnologia e gostaríamos de conhecer mais sobre o Python Brasil 2022, você poderia me enviar o seu mídia kit por favor?

Atenciosamente,
```

**Comment by giuliocc** [comment]
Resposta enviada em 15/02/22:

```
Olá, *****!

Sou o Giulio e faço parte da organização da Python Brasil 2022.

Ficamos muito animados com o interesse da Sólides no evento!
​
Estamos finalizando nosso plano de patrocínio no momento. Podemos marcar uma videochamada para apresentarmos o plano e tirarmos dúvidas quando o mesmo estiver finalizado. O que acha?

Atenciosamente,
​
Giulio Carvalho.
```
