### ISSUE TITLE
Criar planejamento das campanhas publicitárias

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#74]
### Descrição
Criar o cronograma de entregas da equipe de design para que seja adicionado ao cronograma geral da organização.

### Requisitos para a atividade ser considerada como concluída

Planilha com as atividades e sua respectiva data de entrega.

**Comment by rougeth** [comment]
Nós já temos o que precisará ser feito? Se sim, acho que vale colocar aqui na issue.

**Comment by julianyraiol** [comment]
À princípio vejo a criação dessas atividades:

- [ ] Logo oficial do evento
- [ ] Banner do evento para capa de redes sociais (twitter e facebook)
- [ ] Imagem para perfil das redes sociais (twitter, facebook, instagram)
- [ ] Card do evento para story (instagram)
- [ ] Card para divulgação de palestrantes
- [ ] Card para divulgação de keynotes
- [ ] Card para submissão de palestras
- [ ] Identidade visual do site
- [ ] Design do kit do evento (camisa, crachá, adesivos, bolsa)

Cada atividade será criada como uma issue de [arte/publicidade](https://github.com/pythonbrasil/pybr2022-org/issues/new?assignees=cmdiasbr%2C+martinsvanessa%2C+paulohenriquedsgn%2C+deboraazevedo&labels=Arte%2C+Comunica%C3%A7%C3%A3o&template=design.md&title=%3CTema+da+publicidade%3E). A ideia dessa issue é entender quais as atividades mais urgentes e priorizá-las. Como uma estimativa de data podemos adicionar ao cronograma de [plano de trabalho](https://github.com/pythonbrasil/pybr2022-org/issues/68) e acompanhar o andamento das tarefas.

**Comment by julianyraiol** [comment]
@jailsonpj você identifica outras atividades para a equipe de design que estejam associadas à parte de comunicação?

**Comment by cecivieira** [comment]
Talvez pensar em campanhas publicitárias facilite definir as postagens necessárias, consequentemente, as entregas da equipe de design.

Esse foi o planejamento do ano passado:
https://docs.google.com/spreadsheets/d/1ISo4dqdqoB1A2CRHCQSpZ06EWRnkutZWfCWCx7xHwz0/edit?usp=sharing

Sugestões de campanhas adicionais:
- Vacinação COVID e Febre Amarela (10 dias antes de viajar (fonte de informação: [Ministério da Saúde - Artigo](https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/f/febre-amarela-1) + [Ministério da Saúde - Artigo 2](https://www.saude.go.gov.br/noticias/2095-vacina-contra-febre-amarela-deve-ser-aplicada-10-dias-antes-da-viagem) + [Lista de municípios conforme áreas de recomendação para vacinação contra febre amarela](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjAorfxlIz2AhWxLLkGHR0eAzsQFnoECAQQAQ&url=https%3A%2F%2Fsbim.org.br%2Fimages%2Ffiles%2Fms-listamunicipios-fa.pdf&usg=AOvVaw1vIO5-4D1Q7L6olkdRyYJz)))
- Políticas para um evento seguro contra COVID #6

**Comment by cecivieira** [comment]
@menezesgabriel

**Comment by cecivieira** [comment]
Planejamento atual:
https://docs.google.com/spreadsheets/d/1ocmuswrPUkmoQV_4wXKQvhFiCtlbVxDl4hm0IDEw1ME/edit#gid=0

**Comment by cecivieira** [comment]
Talvez pensar em campanhas publicitárias facilite definir as postagens necessárias, consequentemente, as entregas da equipe de design.

Como comentado na https://github.com/pythonbrasil/pybr2022-org/issues/74 :

O time de Comunicação junto @julianyraiol https://github.com/orgs/pythonbrasil/teams/time-design pode decidir o que o evento quer comunicar nas suas redes sociais, ou seja, com quem a gente quer falar? Sobre o que? O que a gente não quer falar? Vai ter libras em toda a programação? Se sim, como vamos comunicar isso? (Dica: colocar [esse icone](https://i0.wp.com/gamacidadao.com.br/wp-content/uploads/2020/03/icon-libras.png?ssl=1) em todas as imagens sobre atividades)

Esse foi o planejamento do ano passado:
https://docs.google.com/spreadsheets/d/1ISo4dqdqoB1A2CRHCQSpZ06EWRnkutZWfCWCx7xHwz0/edit?usp=sharing

Algumas das campanhas foram: Lançamento do evento, Chamada para atividades, Código de conduta, Contagem regressiva para evento, Divulgação das atividades (sprint; palestras; tutoriais e keynotes). Todas estão listadas na coluna A.

Além das campanhas da planilha, sugiro a inclusão das seguintes campanhas adicionais:

    Vacinação COVID e Febre Amarela (10 dias antes de viajar (fonte de informação: [Ministério da Saúde - Artigo](https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/f/febre-amarela-1) + [Ministério da Saúde - Artigo 2](https://www.saude.go.gov.br/noticias/2095-vacina-contra-febre-amarela-deve-ser-aplicada-10-dias-antes-da-viagem) + [Lista de municípios conforme áreas de recomendação para vacinação contra febre amarela](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjAorfxlIz2AhWxLLkGHR0eAzsQFnoECAQQAQ&url=https%3A%2F%2Fsbim.org.br%2Fimages%2Ffiles%2Fms-listamunicipios-fa.pdf&usg=AOvVaw1vIO5-4D1Q7L6olkdRyYJz)))
    Políticas para um evento seguro contra COVID 

    https://github.com/pythonbrasil/pybr2022-org/issues/6

Tô disponível para uma reunião sobre o fluxo e ferramentas de comunicação externa.

**Comment by menezesgabriel** [comment]
https://docs.google.com/spreadsheets/d/1PF6Ys5yGG50Rf3u2hWq0iiIc6-UtbJ2TH4laL8hgqTA/edit#gid=0

**Comment by menezesgabriel** [comment]
https://docs.google.com/spreadsheets/d/1udIOySuO2AHUNoIJXknj0dEL45Q1q6-9/edit#gid=1770463003

**Comment by julianyraiol** [comment]
oi @menezesgabriel vou criar uma issue pra gente mapear as campanhas das próximas semanas, ok?

Criar planejamento das campanhas publicitárias (semana 22-28.05), o q acha?
