### ISSUE TITLE
[Reunião] Kick off da equipe de patrocínio: 13 de fevereiro de 2022

### ISSUE THREAD

**Issue by giuliocc** [pythonbrasil/pybr2022-org#75]
# Reunião de kick off da equipe de patrocínio

- Data: 13/02/22 
- Participantes:
  - Juliana Barros Lima (@tiidadavena)
  - Flávia Viana (@Flaviasv)
  - Giulio Carvalho (@giuliocc)
  - Luiz Bentes (@luizbenttes)
  - Lahis Almeida (@wasp-lahis)
  - Guilherme Gasque (@guigasque)

## Ata
_O objetivo da reunião era apresentar e discturi o atual plano de patrocínio para a equipe de patrocínio e pegar as dicas principais de como encarar os próximos passos com quem tem mais experiência nessa área._

Sobre o plano:
   - Fazer o plano em espanhol também deve ser bem importante 

Vídeo publicitário antes de depois de keynote:
   - Empresas normalmente não tem esse vídeo pronto, fazem especialmente pro evento
   - Normalmente tem 1m30s de duração

Apoios:
   - Apoios ficam fora das cotas de patrocínio
   - Na última Python Brasil conseguiram apoio com a Alura de forma personalizada
   - Fluxo: no primeiro email, mostrar a tabela comparativa. se nos próximos emails não rolar um patrocínio previsto, negociar apoio
   - Precisamos ver valor mínimo para apoios

Prioridade de patrocínios para empresas locais:
   - Luiz menciona que no GDG, as empresas locais foram priorizadas e deu muito certo
   - Poderíamos repetir essa dinâmica, Juliana curtiu a ideia
   - É importante não pressupormos valores de patrocínios ao contatar empresas, surpresas acontecem
   - [Planilha de acompanhamentos dos patrocínios - 2021](https://docs.google.com/spreadsheets/d/1pz619Ma2K9mv6N2vdn1CdzzmHZ7yePuHN85CxKFZ0H0/edit?usp=sharing
)
   - [Fluxo de contato com patrocinadores - Google Docs](https://docs.google.com/document/d/1PQkOxPOQ2VPTx5QuspB--zurIDChC7JvLKiUoQVswUs/edit?usp=sharing)

Cotas de patrocínio:
   - Aumentar número de cotas da diamante para 3
   - Diminuir a distância de contrapartidas entre a diamante e a platina
   - Relatar que as o contrato será fechado na cota desejada com ordem de prioridade, se as cotas disponíveis encerrarem no decorrer do fechamento do contrato, uma renegociação seria necessária

Contato com empresas:
   - Entrar em contato com as empresas, sem mandar o plano de patrocínio primeiramente
   - Caso a empresa não retorne o primeiro contato em algum período definido (1 semana por exemplo), enviar plano de patrocínio
   - Se disponibilizar para uma conversa para apresentar o plano de patrocínio e tirar dúvidas 
   - Ler e reler os contratos, pode pedir tempo para analisar
   - Se precisar de apoio legal, a apyb está disponível para auxiliar
   - O tempo do processo de pagamento varia, podendo chegar até a quase 45 dias
   - Apresentar código de conduta
   - Pesquisar sobre histórico das empresas
   - Não deixar muito tempo se passar entre os contatos com as empresas, priorizar quem está andando mais rápido com o processo
   - Perto do final, as patrocinadoras que entrarem em contato, redirecionar para organização da próxima pybr
   - Mencionar que não priorizamos ninguém, mas estimulamos a presença de pessoas de grupos minoritários
   - Organizar chamadas de meia hora, se apresentar e apresentar o plano inicilamente
   - Sempre que possível, ter pelo menos duas pessoas para passar segurança de existe uma organização por trás e também uma pessoa cobrir a outra caso tenha dúvida

Job fair:
   - Equipe do patrocínio deve ficar à frente disso

Tickets:
   - Mapear os tickets do freshdesk dentro do mesmo contato de empresa, mesmo que venha de pessoas diferentes
   - Não confiar em buscas por nome

### Ações para serem realizadas

- [ ] Assim que o plano de patrocínio for fechado (previsão 18/02), vamos estabelecer o contato com as empresas que já tem interesse (equipe de patrocínio)
- [x] #82

**Comment by rougeth** [comment]
Na última reunião, eu, @julianyraiol, @anadulce e @cecivieira conversamos sobre esses tópicos, mas já tava tarde e acabamos não anotando (marcando elas para verem as notas também). Eu tenho algumas perguntas:

> Normalmente tem 1m30s de duração

Acho que é muito, considerando que será o mesmo vídeo todos os dias.

> Precisamos ver valor mínimo para apoios

Geralmente os apoios são definidos caso a caso, já que não envolvem, necessariamente, valores em dinheiro. Não sei conseguiremos criar uma regra específica.

> Luiz menciona que no GDG, as empresas locais foram priorizadas e deu muito certo

Chegamos a comentar sobre uma ideia parecida: dar um desconto nas quotas para pequenas empresas. Torna o plano mais acessível, mas não beneficia grandes empresas, já que essas não precisam (exemplo: Samsung tem presença forte em Manaus, mas nem por isso precisaria ser priorizada/beneficiada).

> Aumentar número de cotas da diamante para 3

Como vocês chegaram nesse número? Acho que a quota perde valor não sendo exclusiva.

> Diminuir a distância de contrapartidas entre a diamante e a platina

Nós aumentamos a diferença entre as duas quotas porque não parecia justificável pagar 40k a mais pelos benefícios da diamante. O que vocês acham que pode diminuir? (Levando em consideração [essa planilha](https://docs.google.com/spreadsheets/d/1eQyoEUX16MBLoV9Kxgj2zNzpfHeuTv_-QIGprQjSPYg/edit#gid=466765179)).

> Ações para serem realizadas

Vamos criar issues para os dois itens na lista?

**Comment by cecivieira** [comment]
Boa noiteee!!!

Complementando o que Rougeth:

> Relatar que as o contrato será fechado na cota desejada com ordem de prioridade, se as cotas disponíveis encerrarem no decorrer do fechamento do contrato, uma renegociação seria necessária

Talvez seja mais interessante que a priorização seja por ordem de primeiro contato realizado pela empresa com a organização do evento.

> Entrar em contato com as empresas, sem mandar o plano de patrocínio primeiramente
> Caso a empresa não retorne o primeiro contato em algum período definido (1 semana por exemplo), enviar plano de patrocínio

Talvez uma abordagem direta e prática dê agilidade ao processo de patrocínio. Empresas costumam ter limite de investimento anual para esse setor, então boa parte da tomada de decisão é saber quanto de grana precisarei colocar no evento e se a contra partida faz sentido para o valor investido. 

-----
Sugestões para a organização:

- Não vender dados, ou seja, no contrato precisa estar explicitado que não haverá nenhum tipo de repasse de dados pessoais de participantes do evento.
- Realizar todo o contato via e-mail institucional.
- Abrir issue de patrocínio a partir do primeiro contato por parte da empresa + registrar todo o relacionamento com links (contratos, ticket freshdesk etc)

**Comment by rougeth** [comment]
Reabri a issue só para não deixarmos de ver os pontos levantados aqui.

**Comment by giuliocc** [comment]
Respondendo @rougeth e @cecivieira . 

Se alguém mais que estava na reunião desejar apresentar mais perspectivas sobre o que foi conversado fiquem à vontade. Na verdade, seria até melhor hehehe

### Rougeth:

> > Normalmente tem 1m30s de duração
> 
> Acho que é muito, considerando que será o mesmo vídeo todos os dias. Tivemos reclamações em 2019 por conta dos vídeos.

Entendo. Foi um comentário rápido, nada definitivo. Sugere alguma duração? 30s?

Em paralelo, penso em levarmos essa discussão para a issue #35 . O que acha? 

> > Precisamos ver valor mínimo para apoios
> 
> Geralmente os apoios são definidos caso a caso, já que não envolvem, necessariamente, valores em dinheiro. Não sei conseguiremos criar uma regra específica.

Real, real. Estariam confortáveis em já deixar isso definido na issue #35?

> > Luiz menciona que no GDG, as empresas locais foram priorizadas e deu muito certo
> 
> Chegamos a comentar sobre uma ideia parecida: dar um desconto nas quotas para pequenas empresas. Torna o plano mais acessível, mas não beneficia grandes empresas, já que essas não precisam (exemplo: Samsung tem presença forte em Manaus, mas nem por isso precisaria ser priorizada/beneficiada).

No momento foi cogitado entrar em contato com as empresas locais primeiro, mas isso poderia acabar atrasando possíveis contatos bem sucedidos. Pode ser uma boa. O que acham @pythonbrasil/time-patrocinio e @tiidadavena? 

> > Aumentar número de cotas da diamante para 3
> 
> Por curiosidades, como vocês chegaram nesse número? Minha impressão é de que a quota perde valor não sendo exclusiva.
>
> > Diminuir a distância de contrapartidas entre a diamante e a platina
> 
> Nós aumentamos a diferença entre as duas quotas porque não parecia justificável pagar 40k a mais pelos benefícios da diamante. O que vocês acham que pode diminuir? (Levando em consideração [essa planilha](https://docs.google.com/spreadsheets/d/1eQyoEUX16MBLoV9Kxgj2zNzpfHeuTv_-QIGprQjSPYg/edit#gid=466765179)).
> 

A @tiidadavena explicou o raciocínio para essas duas questões e salvo engano era por razão de mais de uma empresa ter interesse em dar o maior patrocínio em experiências passadas e permitirmos isso. Ao mesmo tempo, diminuir as distâncias entre as cotas tornaria mais fácil de uma empresa migrar para outra cota de patrocínio sem haver muito peso na decisão.

Se alguém lembrar de algo a mais, ajuda aqui, por favor :) Falhei na hora de anotar.

> > Ações para serem realizadas
> 
> Vamos criar issues para os dois itens na lista? No lado direito do texto, em cada item, tem uma opção `convert to issue`.

Issue criada para a segunda task. A primeira não acho que precise.

### Ana Cecília

> > Relatar que as o contrato será fechado na cota desejada com ordem de prioridade, se as cotas disponíveis encerrarem no decorrer do fechamento do contrato, uma renegociação seria necessária
> 
> Talvez seja mais interessante que a priorização seja por ordem de primeiro contato realizado pela empresa com a organização do evento.

O que foi discutido foi sobre a possibilidade de haver processos correndo em paralelo, concorrendo uma última cota disponível. Nesse caso, se uma patrocinadora for mais burocrática e entrar em contato primeiro, o que faríamos com a(s) outra(s)? Esperaríamos o término do processo para dar um retorno sobre a disponibilidade da cota? Por isso pareceu melhor deixar os processos correrem e se algum processo for bem sucedido no meio do caminho e o número de cotas encerrassem, entraríamos em processso de renegociação com quem ainda estivesse em andamento.

> > Entrar em contato com as empresas, sem mandar o plano de patrocínio primeiramente
> > Caso a empresa não retorne o primeiro contato em algum período definido (1 semana por exemplo), enviar plano de patrocínio
> 
> Talvez uma abordagem direta e prática dê agilidade ao processo de patrocínio. Empresas costumam ter limite de investimento anual para esse setor, então boa parte da tomada de decisão é saber quanto de grana precisarei colocar no evento e se a contra partida faz sentido para o valor investido.

A justificativa discutida para não enviar o plano de patrocínio de imediato seria não dar margem para ambiguidades e interpretações. Mas esse argumento também é bem relevante. O que acham @pythonbrasil/time-patrocinio e @tiidadavena?

**Comment by cecivieira** [comment]
@pythonbrasil/time-patrocinio 

>O que foi discutido foi sobre a possibilidade de haver processos correndo em paralelo, concorrendo uma última cota disponível. Nesse caso, se uma patrocinadora for mais burocrática e entrar em contato primeiro, o que faríamos com a(s) outra(s)? Esperaríamos o término do processo para dar um retorno sobre a disponibilidade da cota? Por isso pareceu melhor deixar os processos correrem e se algum processo for bem sucedido no meio do caminho e o número de cotas encerrassem, entraríamos em processso de renegociação com quem ainda estivesse em andamento.

Acho interessante os processos correrem em paralelo, mas precisa ser comunicado explicitamente para a empresa que começou primeiro que outra está concorrendo a mesma cota dela. O que pode causar ruído na comunicação, mas acho mitigável se vocês acompanharem os patrocínios mito de perto e determinando data para resposta.

>A @tiidadavena explicou o raciocínio para essas duas questões e salvo engano era por razão de mais de uma empresa ter interesse em dar o maior patrocínio em experiências passadas e permitirmos isso. Ao mesmo tempo, diminuir as distâncias entre as cotas tornaria mais fácil de uma empresa migrar para outra cota de patrocínio sem haver muito peso na decisão.

Acredito que diminuir distância entre cotas de patrocínios desestimula empresas a pegarem a cota maior, pois o custo benefício do dinheiro investido reduz.

>A justificativa discutida para não enviar o plano de patrocínio de imediato seria não dar margem para ambiguidades e interpretações.

A linguagem do plano de patrocínio, especificamente na página da tabela de cotas, foi alterada visando retirar ambiguidades e subjetividade. A ideia é que a linguagem seja aplicada nos slides seguintes que detalham cota a cota.
No primeiro contato o plano pode ser enviado e a equipe informar que está a disposição para reunião, caso a empresa se interesse ou deseje mais informações. Isso vai reduzir o tempo gasto em reuniões e otimizar o tempo da equipe na gestão dos contatos.

**Comment by rougeth** [comment]
@giuliocc comentei na outra issue os dois pontos que você sugeriu. Sobre diminuir a diferença entre as cotas, concordo com o comentário da Ceci.
