### ISSUE TITLE
Agendar criação de issue para reunião de forma automática

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#77]
### Descrição
Utilizar o GitHub Actions para agendar a criação de issues para a reunião geral.
https://docs.github.com/pt/actions/managing-issues-and-pull-requests/scheduling-issue-creation

### Requisitos para a atividade ser considerada como concluída

Criar uma issue de reunião toda quarta-feira às 19:30 (fuso manaus)

**Comment by alencarftc** [comment]
Qual o título, descrição e labels esta issue automática deve ter? 
Além disso, deve estar incluindo todos os membros, certo?

**Comment by rougeth** [comment]
> Qual o título, descrição e labels esta issue automática deve ter?

- Título: `[Reunião] Geral: {dia} de {mês} de {ano}`
- Labels: `reunião`
- Descrição: Nós criamos um template para as reuniões, dá uma olhada no [conteúdo aqui](https://github.com/pythonbrasil/pybr2022-org/blob/main/.github/ISSUE_TEMPLATE/reuniao.md), lá tem todo o texto que precisa ir para a issue.

>  Além disso, deve estar incluindo todos os membros, certo?

Não sei se entendi, mas se for a lista de participantes da reunião (exemplo #76), deve ser uma lista vazia mesmo, nós preenchemos essa lista no começo da reunião com as pessoas que estão participando.

**Comment by julianyraiol** [comment]
[Aqui](https://github.com/pythonbrasil/pybr2022-org/issues?q=is%3Aissue+label%3AReuni%C3%A3o+label%3APr%C3%A9-Evento) a gente tem a lista das últimas reuniões.

**Comment by alencarftc** [comment]
Subi o arquivo com o workflow para a criação automática dos issues. Agora é só aguardar e ver se nas quarta-feiras às 19h30 um novo issue será criado.

**Comment by rougeth** [comment]
Commit para referência: https://github.com/pythonbrasil/pybr2022-org/commit/824b899fb0b55707345e1dd619d76493abaff7a7

---

Valeu @alencarftc, não conhecia o issue-bot, eu acho que eu teria tentado por um caminho muito mais complicado. Alguns comentários sobre o workflow:

- (importante) Muda o schedule pra criar a issue na quinta feita pela manhã. A gente tem o costume de ir comentando na issue durante a semana os tópicos que serão discutidos.
- Eu percebi que a @julianyraiol tava pinando as issues das reuniões, talvez usar a opção `pinned` faça sentido aqui.
- Eu li na descrição da action [imjohnbo/issue-bot](https://github.com/imjohnbo/issue-bot), que é possível usar os templates de issues que já existem. Poderia dar uma olhada? Se der trabalho, pode deixar para um segundo PR.
- Uma dica, você pode adicionar `workflow_dispatch` como trigger da action para executá-lo manualmente na interface do Github - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch.

O primeiro comentário é o mais importante, os outros podemos ver em um segundo momento. Se puder, manda um PR na próxima vez que fica mais fácil pra revisarmos .

**Comment by alencarftc** [comment]
Legal, @rougeth, descobri o issue-bot agora também. Sobre os comentários:

> (importante) Muda o schedule pra criar a issue na quinta feita pela manhã. A gente tem o costume de ir comentando na issue durante a semana os tópicos que serão 
A issue deve ser criada na quinta-feira pela manhã marcando a reunião anterior, certo? Ex: No dia 24/02 irá ser criada a reunião do dia 23/02.

> Uma dica, você pode adicionar workflow_dispatch como trigger da action para executá-lo manualmente na interface do Github.
E quais os parâmetros devem ser solicitados no momento da criação?

Beleza, e sobre o PR, tranquilo, pode deixar!

**Comment by julianyraiol** [comment]
O workflow anterior estava falhando, então fiz uns ajustes:
- Ajustei a posição do [GITHUB_TOKEN](https://github.com/pythonbrasil/pybr2022-org/commit/804f1e094d4fe6b7293e4b01a859d0bab26a6904). A tag env já tinha sido declarada, daí estava [conflitando](https://github.com/pythonbrasil/pybr2022-org/actions/runs/1927946227/workflow).
- Adicionei o `workflow_dispatch` para testar o job manuamente.

Funcionou bacana, mas acredito que precisamos só ajustar algumas coisas :smile: 

cc: @alencarftc  

![image](https://user-images.githubusercontent.com/9119004/156663731-e647304e-b307-4181-a83c-0e025140562f.png)
