### ISSUE TITLE
Parceria com a Jornada Colaborativa

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#78]
Foi agendada uma reunião com  a [Jornada Colaborativa](https://jornadacolaborativa.com.br/) para o 17.02.

- Que horas seria?
- Qual a plataforma que será utilizada?
- Quantas pessoas precisam participar? 
- Como seria a parceria? 
- Existe a possibilidade de remarcar para apresentarmos o Plano de Patrocínio concluído?

**Comment by rougeth** [comment]
https://jornadacolaborativa.com.br/

**Comment by guigasque** [comment]
Adiei a reunião, remarcamos para quando o plano de patrocínio estiver pronto

**Comment by guigasque** [comment]
- Existe a possibilidade de remarcar para apresentarmos o Plano de Patrocínio concluído?

Feito

Sobre os pontos abaixo, a ideia é alinharmos ele na nossa reunião
- Que horas seria?
- Qual a plataforma que será utilizada?
- Quantas pessoas precisam participar?
- Como seria a parceria?

**Comment by wasp-lahis** [comment]
@guigasque @giuliocc Atualizei o slide da Jornada (slide 17): [link](https://drive.google.com/drive/folders/15X0G28DFKuPCVA3OZhdXD5lUpKWtAGN5?usp=sharing)

**Comment by rougeth** [comment]
Olá @wasp-lahis, a parceria foi fechada? Vi os slides e a planilha, mas não entendi os benefícios para pybr na parceria com a Jornada Colaborativa. Eu não estive na reunião passada, mas como não nada na issue https://github.com/pythonbrasil/pybr2022-org/issues/123, estou assumindo que não foi conversado.

**Comment by rougeth** [comment]
Achei a ata da reunião do dia 18/03/2022: https://docs.google.com/document/d/1OdWpJ365VWEt1isD0SFn5Cnh5abM41ta5tsVcN7m0eM

**Comment by rougeth** [comment]
Deixei alguns comentário lá, mas to perdido.

**Comment by wasp-lahis** [comment]
Oie @rougeth! Ainda não foi fechada. Não participei da última reunião com a Jornada. O @guigasque e o @giuliocc podem te explicar melhor.

Na primeira reunião com eles, ficamos de montar uma proposta de colaboração com base nos pontos discutidos. De retorno p Jornada vamos divulgar a comunidade, livros e cursos deles. O retorno para Python Brasil seria:

- o networking que eles já possuem, poderiam direcionar contatos de empresas por exemplo; 
- uma % em cima dos valores do slide 17

Aqui explicamos como chegamos nos valores: [link](https://drive.google.com/drive/folders/15X0G28DFKuPCVA3OZhdXD5lUpKWtAGN5?usp=sharing)

**Comment by rougeth** [comment]
> vamos divulgar a comunidade, livros e cursos deles

Importante isso ser bem detalhado, podemos usar os benefícios do patrocinador bronze (20k) como balança.

> o networking que eles já possuem, poderiam direcionar contatos de empresas por exemplo;

Essa parte ainda esta aberta ou já temos algo mais concreto? Eu acho que simplesmente fazer a ponte com empresas é muito pouco, o risco fica todo no nosso lado, já que não tem nenhuma garantia de que essas empresas fechariam patrocínio. Várias das empresas listadas na página deles já patrocinaram a Python Brasil e, para as outras, que usam Python, acho que conseguiríamos alcançá-las usando ajuda da própria comunidade Python.

> uma % em cima dos valores do slide 17

Também acho que o risco está todo no nosso lado. No plano, são pacotes adicionais, não há nenhuma garantia para que as empresas os contratem (achei os benefícios não convincentes), o que pode gerar nenhum retorno financeiro para o evento.

Outro ponto que achei estranho é atrelar as duas comunidades no plano de patrocínio, minha sensação é que estamos oferecendo muito por muito pouco (ou nada, considerando os riscos - no final, podemos não receber/ganhar nada com a parceria).

Desculpem só estar comentando sobre isso agora, só estou conseguindo voltar a ver as coisas da Python Brasil essa semana.

**Comment by giuliocc** [comment]
@guigasque a atualização dessa issue da Jornada Colaborativa com a definição da Parceria e a ata da última reunião do dia 24 vão tirar muitas dúvidas, como está o andamento?

@rougeth atualizei a #123 com o link do HackMD que a @julianyraiol havia deixado. Discutimos essa parceria na reunião e baseado nela levamos a proposta pra Jornada Colaborativa de como poderia ser a parceria.

O @guigasque tem mais domínio já que está responsável pelo contato com a Jornada, mas dando um apanhado geral em como estão as coisas até onde vai meu conhecimento:
- Os pacotes da Jornada seriam opcionais e nossa intenção é reforçar esses pacotes principalmente com as empresas que já conhecem a Jornada
- Oferecemos contrapartidas para as empresas ao contratar os pacotes (apydrinhamento com livro e sorteio de curso no estande da empresa, pras que tem estande, melhoram o post pós-evento da empresa e chamam pessoas para o estande da empresa, respectivamente), mesmo não conhecendo a Jornada os pacotes são interessantes
- A Jornada irá buscar um patrocínio pra ela patrocinar o evento com uma tiragem de pelo menos 200 livros (a empresa que patrociná-la recebe uma parte dos livros com a logo da empresa e a da pybr e o resto seria doado para participantes do evento)
- A Jornada teria um estande para venda dos materiais em um dia do evento (sábado ou domingo) e a organização receberia comissão pelas vendas (acharam melhor ficar presencialmente apenas um dia mesmo e nos outros dias deixarmos a possibilidade de ver o catálogo com um QR Code ou alguma solução semelhante)

Quanto a atrelar as duas comunidades no plano de patrocínio, acredito que ganhamos com isso já que as comunidades se apóiam. E como são pacotes opcionais, são interessantes para quem os desejar mas não atrelam nenhuma obrigação.

**Comment by guigasque** [comment]
Ata do dia 24/03

https://hackmd.io/VVyuR0uAQlS2fn09GFRNGw
