### ISSUE TITLE
[Reunião] Onboarding - Lahis e Luiz: 14 de fevereiro de 2022

### ISSUE THREAD

**Issue by wasp-lahis** [pythonbrasil/pybr2022-org#79]
# Reunião - Onboarding  Lahis e Luiz

- Data: 14/02/2022  
- Participantes:
  - Juliany Raiol (@julianyraiol )
  - Lahis Almeida (@wasp-lahis)
  - Luiz Bentes (@luizbenttes) 

## Ata

O objetivo da reunião foi realizar o Onboarding da Lahis e Luiz, discutir alguns desafios do evento e pensar em próximas atividades.

- Há poucas pessoas aqui em Manaus colaborando com o evento.
   - Há pelo menos uma pessoa de Manaus em cada Grupo de Trabalho.
   - As pessoas da APyb são responsáveis em dar suporte e não em propriamente puxar tarefas.
- A issue de Onboard é a #69 
   -  Precisa de colaboração
- Para melhorar organização, devemos listar as prioridades. Dessa forma, poderemos sentir que estamos avançando/evoluindo com as atividades do evento.
   - É importante definir grupo de trabalho, adicionando informações de quantas pessoas e quem está em cada uma delas (isso pode ficar no slide de Onboard, para que os novos integrantes se sintam + confortáveis) 

### Ações para serem realizadas

- [x] #80
- [x] Alimentar slides de Onboard (qtas pessoas/quem por grupo de trabalho)
- [x] Chamar mais pessoas ( @wasp-lahis e @luizbenttes) )

**Comment by julianyraiol** [comment]
Issue para listagem de atividades
https://github.com/pythonbrasil/pybr2022-org/issues/80
