### ISSUE TITLE
Criar cartilha com recomendações importantes para vir até Manaus

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#8]
- Incentivar a vacinação 
- Falar sobre temperatura 
- Lista de restaurantes, supermercados, hospitais, delegacias próximas ao local do evento

**Comment by lskbr** [comment]
Nós vamos seguir todas as regras em vigor na época, regras de Manaus.
Ao abrirmos as chamadas, já teremos que ter uma ideia para avisar os participantes do que é preciso: vacinas, testes, etc.

**Comment by julianyraiol** [comment]
Adicionar contatos importantes na cartilha de acordo com esta [issue](https://github.com/pythonbrasil/pybr2022-org/issues/30)
