### ISSUE TITLE
Patrocínio da Contabilizei

### ISSUE THREAD

**Issue by giuliocc** [pythonbrasil/pybr2022-org#81]
### Descrição
Acompanhamento das tarefas relacionadas ao possível patrocínio da Contabilizei.

### Requisitos para a atividade ser considerada como concluída

- Contrato assinado
- Patrocínio recebido em caixa
- Pendências pós evento concluídas

Ticket #8011 - Contabilizei <> Python Org Brasil

**Comment by giuliocc** [comment]
Resposta enviada em 15/02/22 (levando em conta que só seguiremos com os contatos após a finalização do plano de patrocínio):

```
Olá, *****!

Sou o Giulio e faço parte da organização da Python Brasil 2022.

Ficamos muito animados com o interesse da Contabilizei no evento!

No momento ainda estamos fechando o plano de patrocínio. Posso te dar um retorno assim que estiver pronto e então marcarmos a call?

Atenciosamente,

Giulio Carvalho.
```

**Comment by giuliocc** [comment]
Nova mensagem recebida em 21/02/22:

```
Bom dia Julio, tudo bem? 

Claro, podemos marcar essa semana? 

Fale 3 horários que você tiver disponível.
```

Resposta em 22/02/22:
```
Oi, *****!

Esta semana não conseguimos pois ainda estamos realizando os últimos ajustes no plano.
​
Posso te dar um retorno sobre data até a sexta dessa semana?
```

**Comment by giuliocc** [comment]
Espero poder já marcar pra semana que vem. Mas na reunião geral de amanhã podemos bater esse martelo

**Comment by julianyraiol** [comment]
oi @giuliocc, nós prosseguimos com esse contato?

**Comment by giuliocc** [comment]
@julianyraiol Tivemos a reunião inicial e até agora não tive resposta. Mandei dois emails pedindo updates. Semana que vem completa um mês e aí acho que podemos fechar.
