### ISSUE TITLE
Montar uma planilha de prospecção de empresas

### ISSUE THREAD

**Issue by giuliocc** [pythonbrasil/pybr2022-org#82]
Como iremos realizar busca ativa para patrocínios, uma planilha será criada para mapearmos as empresas que entraremos em contato.

**Comment by giuliocc** [comment]
@pythonbrasil/time-patrocinio, montei aqui a planilha baseada na que a @tiidadavena compartilhou com a gente na reunião de kick off que foi utilizada em 2021.

[Link da planilha](https://docs.google.com/spreadsheets/d/1KOyOn9LWJu0QkClooNxW8ZLj5sFDTCZOLlzYs2SIPzY/edit?usp=sharing)

A planilha contém não só prospecção (colocando o "Status" do contato como "A contatar") como também várias coisas para irmos organizando o contato com as empresas e o fluxo de caixa dos patrocínios.

Acham que tá ok ou já enxergam modificações necessárias?

**Comment by wasp-lahis** [comment]
Ficou bem bacana! Como sugestão: colocar um hiperlink com o email da pessoa da empresa responsável. Acho q facilita o trab se precisarmos procurar no futuro. Seria mais p concentrar essa informação na planilha mesmo.

Acrescentei três grandes institutos aqui de Manaus. Eles tem outros sites pelo país também, mas cm possuem site aqui em Manaus coloquei na categoria Regional mesmo.

**Comment by giuliocc** [comment]
Podemos fechar a issue? Acho que finalizamos
