### ISSUE TITLE
Inserir bot GitHub no Discord

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-org#85]
### Descrição
Incluir canal destinado a acompanhamento das issues no Discord, através de notificações do bot do GitHub.

### Requisitos para a atividade ser considerada como concluída

- Incluir bot do GitHub no Discord
- Configurar para que notifique sobre criação de novas issues e novos comentários em issues

**Comment by cecivieira** [comment]
Essa issue parte do entendimento de que o Discord é uma das ferramentas de comunicação da organização (https://github.com/pythonbrasil/pybr2022-org/issues/69#issuecomment-1046100911).

**Comment by rougeth** [comment]
Pedi acesso ao Discord para o @renan-assis-santos, configuro assim que puder.

**Comment by rougeth** [comment]
Feito.
