### ISSUE TITLE
Passar experiência da Trilha de Espanhol para novos voluntários

### ISSUE THREAD

**Issue by wasp-lahis** [pythonbrasil/pybr2022-org#86]
### Descrição
Passar a experiência da Trilha de Espanhol dos anos anteriores para novos voluntários (@IKVillanes).

### Requisitos para a atividade ser considerada como concluída

- Marcar reunião com integrante da Trilha de 2021 e novos integrantes
- Gerar Ata

**Comment by cecivieira** [comment]
@wasp-lahis integrei a trilha de espanhol do ano passado, por isso me coloquei como participante dessa issue. =D

**Comment by julianyraiol** [comment]
oi @cecivieira, podemos marcar uma reunião com a @IKVillanes para você passar como foi a experiência para ela? :smile_cat:

**Comment by julianyraiol** [comment]
issue relacionada #52

**Comment by cecivieira** [comment]
Posso sim.
Pode ser a partir de 03 de março no turno da manhã?

**Comment by IKVillanes** [comment]
Olá bom dia, 
pode ser sexta-feira 04 de março ? 8:30-9:00am ou 12m -12:30(Hora Manaus)

**Comment by cecivieira** [comment]
@IKVillanes posso dia 04 março as 12h30 (horário Manaus). 
Fazemos uma vídeo chamada no Discord do evento.

**Comment by rennerocha** [comment]
Olá, eu posso ajudar na trilha em espanhol. Pode compartilhar aqui o link para o Discord do evento? A reunião no dia 4 de março vai acontecer mesmo?

**Comment by cecivieira** [comment]
Oi @rennerocha essa reunião será para eu passar a experiência do ano passado para a liderança desse ano. Não será uma reunião de organização.

Acredito que ela vai abrir umas issues novas ou informar quando começar a organizar a trilha.

**Comment by rennerocha** [comment]
Ok, pelo que entendi da sua resposta, não faz sentido eu participar dessa reunião mesmo que eu queira ajudar com a trilha, certo?
