### ISSUE TITLE
[Reunião] Geral: 31 de outubro de 2021

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#9]
# Reunião Geral

- Data: 31 de outubro de 2021

- Participantes: 
  - Alice Adativa
  - Fabio da Luz
  - Juliany Raiol
  - Marco Rougeth
  - Nilo Menezes
  - Paulo Sérgio
  - Renan Sebastião

## Ata
- Definir canal oficial de organização (continuaremos no telegram? migrar para o discord?)
- https://github.com/pythonbrasil/pybr2022-org/issues/1
- Post mortem 2021 (o que funcionou, o que deu errado?) 
- https://github.com/pythonbrasil/pybr2022-org/issues/7
- https://github.com/pythonbrasil/pybr2022-org/issues/13
- https://github.com/pythonbrasil/pybr2022-org/issues/6
- Avaliação e priorização de issues/próximas ações

## Itens discutidos

- Discord ou telegram?

- Post Mortem 2021
  - Problemas com o discord / problemas de credenciamento. Bots bugados, testar antes para evitar aperreio na hora da conferência
  - Ferramentas para submissão de palestras
  - Script de anonimização de submissões
  - +/- 300 submissões - 93
  - Pesos por gênero/origem/primeira vez
  - Palestrantes que somem (pedir telefone)
  - Banco de reserva - vagas
  - CDC: quanto mais pessoas, melhor, pessoas com experiência
- Treinamento CDC
  - Mostrar durante a inscrição
  - Enviar por email
  - Completar/adicionar clausulas caso necessário
  - Equipe independente 
- Melhorias no logo do evento
  - Artes prontas, usaram Canvas
  - Paulo Sergio -> vai ajudar com design
  - Marco -> vai passar contato da design (Camila Dias) de 2020/2021
  - Precisamos de um designer

- Covid
  - Monitorar a situação do Covid em Manaus até Fevereiro
  - Ambulancia/Bombeiros (pelo número)
  - Pedir cartão de vacina

- Priorização de issues
- Próxima reunião
  - 13 de Novembro? 15:00 + 30 min Manaus

Issues a criar:
- Criar Servidor Discord para Python Brasil 2022
- Criar um Servidor Discord separado para organização
- Redes sociais
- Quantos PMs
- Template dos emails de submissão
- Textos pro site
- Bots do Discord - recuperar os de 2021, heroina

# 1 - Criar plano de patrocínio

Quem pode realmente ajudar?
- Obtendo informações
- Fazendo as tarefas
- No dia / mais perto do evento

O que deu certo/errado em 2021?

Feito
- Pedido do centro de convencoes
- Stub do projeto do frontend

**Comment by lskbr** [comment]
Ata disponível em: https://hackmd.io/qSI9RoyKTxmF0ZrgvB5wog
e em nosso Google Drive, pasta atas
