### ISSUE TITLE
Definir sistema de inscrição

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#92]
### Descrição
Verificar o uso do sistema utilizado pela PyConUS como ferramenta de inscrição para a Python Brasil
https://github.com/PyCon/registrasion

### Requisitos para a atividade ser considerada como concluída

- [ ] É prático para a criação de formulários?
- [ ] O que é necessário para colocarmos no ar?
- [ ] Podemos obter um csv das pessoas inscritas?
- [ ] Qual o banco de dados?
- [ ] É possível pagar pela plataforma?
- [ ] Existe outra ferramenta melhor?

**Comment by rennerocha** [comment]
A PyConUS utilizou esse ano o https://pretalx.com/ para fazer o seu sistema de submissão de propostas de palestras e atividades. É um sistema open source que dá para termos total controle e tem todas funcionalidades para receber submissões e também para a análise delas.

Acredito que é um sistema bem mais robusto que o speakerfight que os eventos Python no Brasil costumam utilizar.

**Comment by julianyraiol** [comment]
oi @rennerocha, valeu pela sugestão :smile: 

estamos analisando essa ferramenta inclusive #48

**Comment by julianyraiol** [comment]
Oi @cecivieira, você poderia verificar como funciona a integração Pretalx e [Registrasion](https://github.com/PyCon/registrasion) na PyConUS?

**Comment by anadulce** [comment]
Pontos importantes para escolha de uma ferramenta de inscrição:
* Criação de perguntas personalizadas;
* Envio de e-mails em massa;
* Agendamento de e-mails;
* Sistema de check-in prático para o credenciamento (credenciamento já é meio caótico, a ferramenta tem que cooperar);
Bônus:
* Possibilidade de mais de um idioma;
* Envio de certificados de participação;

**Comment by cecivieira** [comment]
Sistema de registro (branch atual): https://github.com/PyCon/registrasion/tree/pycon
Site: https://github.com/PyCon/pycon.org

Talvez esses dois links ajudem, enquanto não tenho resposta

**Comment by cecivieira** [comment]
Contato realizado com:
PyCon US
ewdurbin
Bernardo (berin)

Essas duas últimas pessoas fizeram commites nas ferramentas, daí falei com elas pra saber se sabem como tá a implementação.

**Comment by cecivieira** [comment]
@julianyraiol quem tá tocando essa tarefa?
Bernardo pode conversar sobre o tema.

**Comment by TalissaMoura** [comment]
@cecivieira Oie! Cê teria algum email do Bernardo da PyConUs para eu conversar com ele sobre como tá sendo feito o registration por lá?

**Comment by TalissaMoura** [comment]
@cecivieira Oi Ana! sou eu que to levando essa tarefa pra frente. To tentando entrar em contato com o Bernardo da PyCon US para tentar marcar uma reunião para ele explicar mais sobre o registration. Enviei um email e to aguardando a resposta. Se possível, não queria participar sozinha e se desse para alguém fazer a reunião junto comigo seria bacana (mas se não der beleza, também ;) )

**Comment by cecivieira** [comment]
Já já @berinhard aparece por aqui falando a disponibilidade do horário. 

@TalissaMoura amanhã tem reunião geral do evento, seria perfeito que tu aparecesse para colocar que tas precisando de alguém mais nessa área.
Também é legal participar para acompanhar como tá a organização de forma geral e trazer as dificuldades sobre o que tu tas fazendo, pedir ajuda, etc

**Comment by TalissaMoura** [comment]
Beleza! Semana passada eu tive um imprevisto mas amanhã acredito que deva participar =)

**Comment by berinhard** [comment]
Como falei com a @TalissaMoura por email, antes de mais nada, obrigado por voluntariarem-se a fazer a Python Brasil acontecer! 

Posso qualquer dia mais pro meio/fim da tarde e início da noite. O que for melhor para vocês =)

**Comment by berinhard** [comment]
Já adianto que o mais complexo do registrasion é entender a sua modelagem e, depois disso, a customização. O problema dele é que boa parte dos forms usa o crispy forms para renderizar, o que significa ter que mexer no backend para mudar no frontent (sim, loucura como pode ser visto [aqui](https://github.com/PyCon/registrasion/blob/pycon/registrasion/forms.py#L523)). 

Além disso, o projeto hoje **não é mantido** e meio que o código "oficial" dele para a PyCon está num branch separado, chamado, advinhem, [pycon](https://github.com/PyCon/registrasion/tree/pycon/registrasion).

**Comment by julianyraiol** [comment]
opa, eu também! posso participar da reunião. @TalissaMoura quando vc pode?

**Comment by TalissaMoura** [comment]
Olha meus horários são parecidos com o de @berinhard! Qualquer dia mais lá pro meio/final do dia tá ótimo

**Comment by TalissaMoura** [comment]
Pra próxima semana, os melhores dias pra mim são a segunda (02/05), terça (03/05) e quinta (05/05). A partir das 15:00 to livre. Qual desses dias é melhor para vocês? @berinhard @julianyraiol

**Comment by berinhard** [comment]
A segunda e terça da semana que vem funcionam melhor pra mim.

**Comment by julianyraiol** [comment]
vamos então na segunda (02/05) às 19h (fuso manaus - GMT-4)? @berinhard @TalissaMoura

**Comment by TalissaMoura** [comment]
Por mim, esse horário tá ótimo :)

**Comment by berinhard** [comment]
Opa, achei que tivesse respondido! Foi mal, mas pra mim dá também! Em 10 min né?

**Comment by TalissaMoura** [comment]
Isso! Acho que dá pra ser no nosso discord https://discord.gg/NcryeRZh

**Comment by TalissaMoura** [comment]
Então, hoje 02/05, conversei com Bernardo sobre o sistema de inscrição da PyCon 

Então, lá é um grande sistema chamado registrasion, onde ele controla, toda a parte 
"de perfil" dos participantes do evento: tipo de ingresso (se é estudante, empresa privada etc), região demográfica, 
controle de compra de tutoriais. Ele é bem completo!!

Dentro dele tem o registration (link do [git](https://github.com/PyCon/registrasion/tree/pycon) dele) que é quem controla justamente a inscrição dos participantes 
(junto com a bibloteca django-allauth). No caso, o proprio Bernardo passou os códigos dele, porque o acesso dele
no github não tá público. 

Dito isso, o registrasion têm bastantes funcionalidades mas muitas delas não atendem nossas necessidades
então, teria que passar um pente fino na aplicação para verificar o que poderíamos usar ou não. Contudo,
pro registrasion funcionar bem, algum desses produtos precisam está juntos (então é mais complicado escolher quem retirar).
Além disso, esse app não tem uma forma de enviar certificados e envio de email em massa. 

Por causa disso, achei melhor procurar outras alternativas pro evento (como Sympla e Eventbite).

**Comment by cecivieira** [comment]
@TalissaMoura ano passado fizemos um comparativo entre Eventbrite e Sympla.
Dá uma olhada e vê se te ajuda na escolha.

https://github.com/pythonbrasil/pybr2021-org/issues/98
