### ISSUE TITLE
Criar formulário para coletar informações da empresa patrocinadora (@time-patrocinio)

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#93]

**Comment by cecivieira** [comment]
Seguem os formulários para serem usados como inspiração:

es - https://docs.google.com/forms/d/1X-0CK7IficTeuf2oRQSxLpfx0SBApL44wCX3EluHVFk/edit?usp=sharing
en - https://docs.google.com/forms/d/1HFbQomVthsngHeEbMqY9T25g3MzIWmdAe2aBfek_ps4/edit?usp=sharing
pt - https://docs.google.com/forms/d/1uRG7yt7D8PgwMvTP3wjCSRPRTFn0idvu0sGCCRetdOA/edit?usp=sharing

**Comment by julianyraiol** [comment]
formulário no drive: https://drive.google.com/drive/u/3/folders/17VeisT-ub16NN1kz5Rp6rmmsrfqekJGD

**Comment by wasp-lahis** [comment]
** Oganização dos Formulários de coleta de dados das empresas (Nacional/Regional/Internacional (Inglês)):**

> Pasta: https://drive.google.com/drive/folders/17VeisT-ub16NN1kz5Rp6rmmsrfqekJGD?usp=sharing

Sobre a planilha que é gerada com os dados da empresas, elas estão funcionais! Entretanto, o ideal é que gerassem menos colunas, mas não consigo resolver isso ainda hj.

@pythonbrasil/time-patrocinio Se puderem revisar pls  (principalmente o inglês) o/

**Comment by cecivieira** [comment]
@wasp-lahis revisei o formulário e trouxe pra área inicial os campos que são comuns a todas as cotas.
https://docs.google.com/forms/d/1suQ1JnE95F7xvlpKI0M5MVRLkhsZbaE-i9ZoqyUEr40/edit

Mas, ainda assim existem campos repetidos em algumas das cotas, por não pensei em uma solução melhor.
