### ISSUE TITLE
Patrocínio do Eldorado

### ISSUE THREAD

**Issue by wasp-lahis** [pythonbrasil/pybr2022-org#97]
### Descrição
Acompanhamento das tarefas relacionadas ao possível patrocínio do [Instituto de Pesquisas Eldorado](https://www.eldorado.org.br/).

A planilha de prospecção das empresas pode ser visualizada em #82 

### Requisitos para a atividade ser considerada como concluída
- Contrato assinado
- Patrocínio recebido em caixa
- Pendências pós evento concluídas

Ticket:

**Comment by julianyraiol** [comment]
oi @wasp-lahis a issue tá duplicada né? posso fechar? https://github.com/pythonbrasil/pybr2022-org/issues/132

**Comment by wasp-lahis** [comment]
Oie @julianyraiol, tá sim. Pode! vlww
